### ISSUE TITLE
Nutrition Goals

### ISSUE THREAD

**Issue by HamBoneGreen** [wger-project/wger#1003]
Wife is using me as a test subject to see if she likes coaching/training. I decided to use this as a dashboard to 'report' to her. Her number one concern for it was the inability for a trainer to set Nutrition Goals for a user. She can set a calorie count, but she would like a way to highlight how much of each Macro I should shoot for, ie Protein, Carbs, etc.

I would like to suggest adding 'Goals or Limits' to the Macros in the Nutrition Planning Section.

Examples
- Daily eat this much protein.
- Stay below this many Carbs.

**Comment by rolandgeider** [comment]
Hi! You are right that at the moment it's not possible to set any kind of goals. I have some other ideas on what to improve with the nutrition tracking in general, adding this issue to the next release

**Comment by HamBoneGreen** [comment]
I do not want to speak out of ignorance, but it might be worth talking to 5-6 personal trainers to find out what they use now for their clients/selves and how the current solution lacks.

I'd be willing to do that if you'd like.

**Comment by rolandgeider** [comment]
That would be very useful! We can open an info dump issue/discussion and then sort the things that we can do from there

**Comment by FelixJohnsson** [comment]
I'd love to help with this as well, and I know personal trainers that I can talk to.

**Comment by rolandgeider** [comment]
Sure!!

**Comment by HamBoneGreen** [comment]
> I'd love to help with this as well, and I know personal trainers that I can talk to.

Don't take this as me telling you how to talk to people, I'm not trying to be pushy just sharing/reminding what I've learned.

Ask questions like:
- What do you use now? > Can you show me?
- What does the current solution for you excel at? Why did you choose it? > What is your biggest pain?

Rather than looking for requirements find out the value pieces and we can extract them.

**Comment by rolandgeider** [comment]
Any updates? :)
