### ISSUE TITLE
Improve muscle recognition

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1009]
While the latin names are nice and kinda universal... they are also pretty opaque. We could add a new field to the muscle model with a common description (like "shoulders" or "butt") in English that can be translated with the infrastructure we already have in place or do something completely different.

**Comment by ImTheTom** [comment]
Hey,

Was having a look at this. Noticed this recent commit https://github.com/wger-project/wger/commit/879a54f46a4be1f9c1fbd68e751fa2fa73309136.

Reckon I should try to follow a similar path to that by adding a exercises_musclesalias table. If it's too hard fall back to just another column in the exercises_muscle table?

**Comment by rolandgeider** [comment]
Yeah a new column is enough, perhaps we can call it something like `name_en`. When this is done, we need to extract the names so they can be translated like the rest of the strings on weblate, that's done in `extract-i18n.py` (that's perhaps not the most elegant way of handling internationalization, but it's only for a handful of strings that are saved in the database).

I would suggest we show the translated name in parenthesis (if it's available, not all muscles will have a "translation", only the most important ones, this is also something we need to consider when extracting them in the script).

**Comment by ImTheTom** [comment]
Yeah cool. Thanks for the insight.

**Comment by rolandgeider** [comment]
We'll also need some data migration for existing instances btw. If you want to work on this I can prepare a list with the names

**Comment by ImTheTom** [comment]
Yeah sure, I'll give it a go.

**Comment by rolandgeider** [comment]
| ID  | Latin                       | English    | 
|-----|-----------------------------|------------|
| 1   | Biceps brachii              | Biceps     |
| 2   | Anterior deltoid            | Shoulders  |
| 3   | Serratus anterior           | -/-        |
| 4   | Pectoralis major            | Chest      |
| 5   | Triceps brachii             | Triceps    |
| 6   | Rectus abdominis            | Abs        |
| 7   | Gastrocnemius               | Calves     |
| 8   | Gluteus maximus             | Glutes       |
| 9   | Trapezius                   | -/-        |
| 10  | Quadriceps femoris          | Quads      |
| 11  | Biceps femoris              | Hamstrings |
| 12  | Latissimus dorsi            | Lats       |
| 13  | Brachialis                  | -/-        |
| 14  | Obliquus externus abdominis | -/-        |
| 15  | Soleus                      | -/-        | 
| 16  | Erector spinae              | Lower back |

How about this? I wasn't sure about gluteus maximus, "Booty" is probably too informal 😅

**Comment by ImTheTom** [comment]
Looks perfect man :)
