### ISSUE TITLE
Cache API responses

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1011]
We should cache the different exercise overview responses from the API, since they will rarely change:

* `exercise`
* `exerciseinfo`
* `exercisebaseinfo`

https://www.django-rest-framework.org/api-guide/caching/

**Comment by ImTheTom** [comment]
Hey,

Just to clarify. The outcome of this issues is that requests to urls such as

https://wger.de/api/v2/exercise

are cached. With invalidating that cache when exercises are updated is a nice to have.

**Comment by rolandgeider** [comment]
Exactly. Since the exercises rarely change we can live with just caching the response for a certain time
