### ISSUE TITLE
AllowVideoUpload can't be set in an Docker Environment

### ISSUE THREAD

**Issue by DunklerPhoenix** [wger-project/wger#1013]
See https://github.com/wger-project/wger/issues/994#issuecomment-1088483792

**Comment by rolandgeider** [comment]
Yes you are right, while it's possible to mount a custom settings.py and change it accordingly, this is not documented anywhere

**Comment by DunklerPhoenix** [comment]
Yeah this was just the "new" issue you wrote in the other issue just as a note for later :D Wasn't sure if you forgot it to create.

**Comment by rolandgeider** [comment]
This should be possible now
