### ISSUE TITLE
Show history with changes to exercises data

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1055]
We want to give admins an overview of changes made to the exercises. At the moment we use django activity stream to log high level events such as "user 123 created exercise 100" and django simple history to track the changes made to the content. What is needed is some overview that somehow combines both list so that we can see when did what change by whom. Also there should be a button that allows the admin to revert the changes made (the simple history app already has this functionality).

Both activity stream and simple history allow to store some additional data, activity stream can save a JSON object and simple history has a "reason" field which could be (mis)used to store some IDs or similar.

Another thing is that currently the activity stream entries are done manually in the api endpoints (e.g. perform_create in ExerciseBaseViewSet), but it might be cleaner to move this to a signal (but we don't have access to the request there so it might not be possible). If we can do this with only simple history and detect when an object was newly added instead of updated, then we can remove the dependency on activity stream (this might be useful in other places to show the user their last  actions, but that would be another issue)

The current overviews:
- http://localhost:8000/exercise/history/overview/
- http://localhost:8000/exercise/history/overview-history/

**Comment by ImTheTom** [comment]
Yeah for sure man. :)

**Comment by rolandgeider** [comment]
yeah exactly
