### ISSUE TITLE
Getting too many 503 - Service is unavailable

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1060]
It seems the cache introduced for the rest api causes sometimes strange 503s on wger.de.

Need to investigate this, till then they will be commented out

**Comment by ImTheTom** [comment]
Ahh, sorry for the breakage.

**Comment by rolandgeider** [comment]
Yeah, don't worry. I only noticed because the docker images didn't always build successfully when pulling new exercises. It's also a strange behaviour because I couldn't always reproduce. Also, why would this happen in the first place???

**Comment by rolandgeider** [comment]
We need to fix this before releasing the react version of the exercise pages

**Comment by rolandgeider** [comment]
it seems this was a misconfiguration on my side, closing 🤞🏻
