### ISSUE TITLE
Add Resistance Bands as Equipment

### ISSUE THREAD

**Issue by Keddyan** [wger-project/wger#1071]
... so users can add exercise variations of the ones with machines/weights

motive:
decided to go back to exercising but this time at home with Resistance Bands, some exercises don't vary much front the OG ones but there's still a difference

Extra:
Ilustrations are very important for these types of exercises because these are more "flexible", shouldn't there be an option to add them so someone that checks the exercise can know what to do instead of having to check for the proper "configuration"?

**Comment by ImTheTom** [comment]
Hey Keddyan,

Wger allows the admin to add new equipment. Going Training -> Equipment when logged in as an admin.

Pretty sure the default log in for the admin if you haven't seen yet is username: admin with the password: adminadmin.

The admin user can also add images and videos for the exercises as well.

Is this what you're looking for?

**Comment by Keddyan** [comment]
Hi

well, that might explain it, that requires my own instance, right? I don't have one, I log in on the default one

**Comment by ImTheTom** [comment]
Yeah my comment was under the assumption that you were running your own instance.

Not too sure what the recommendation is around using https://wger.de/ I've personally only ever seen it as a demo site like other projects have such as firefly iii.

**Comment by Keddyan** [comment]
damn, that's a bummer, i can't self-host it right now so I guess I'll have to find another thing.... this was the best app I could find on fdroid

**Comment by rolandgeider** [comment]
Hey! wger.de can be seen as a demo, but it can be used for the general public as well (and in fact the default server used in the flutter app is wger.de)

We're currently reworking the way users can submit and correct new exercises, we can add the resistance bands to the "official" db when we're done there (after all, having them in the list of equipment but having no corresponding exercises would be a bit pointless)

**Comment by rolandgeider** [comment]
Closing issue, resistance bands will be in the default DB/instance once we release the new exercise stuff
