### ISSUE TITLE
No protection against bruteforce attacks on login page

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1096]
At the moment there is no protection against brute force attacks on the login page, while not a priority it would be nice if we could do something about it.

* https://github.com/jazzband/django-defender
* https://github.com/jazzband/django-axes

**Comment by RohanKaran** [comment]
@rolandgeider , If this issue is still relevant, I would like to work on this.

**Comment by rolandgeider** [comment]
Go ahead 👍🏻

**Comment by RohanKaran** [comment]
Is redis is used in production server ? Because then we can use the cache for monitoring login attempts which can provide better performance

**Comment by rolandgeider** [comment]
Yes there's a redis server, also on the provided docker compose, we can just use it
