### ISSUE TITLE
System language (or at least easy access to switch to english)

### ISSUE THREAD

**Issue by HackaN** [wger-project/wger#1108]
The app doesn't seem to use system language. Instead it's... Well, I don't know what language it is. This happens on the first run of newly installed app (1.4.1) from f-froid.
![Screenshot_20220813-042939_wger](https://user-images.githubusercontent.com/26646/184465161-113be2f9-da69-422c-9a5e-d34282d1f8e9.png)

**Comment by rolandgeider** [comment]
Hi! That is sadly a bug in flutter, sometimes it doesn't load the system language but the first one alphabetically which happens to be Amharic. Have you installed English as an available language?

**Comment by HackaN** [comment]
Amazing! I added English to my system languages and now it's displayed in English :-)
