### ISSUE TITLE
Rework landing page

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1112]
From the figma page

![image](https://user-images.githubusercontent.com/2280729/192362883-4753deba-9872-46e5-ad07-c13bdd1460f1.png)

**Comment by Mithilesh8** [comment]
What kind of changes are expected on landing page?

**Comment by rolandgeider** [comment]
Hi! Basically implement the design from the screenshot to replace [the current version](https://wger.de/software/features).

Since we'll be updating the version of bootstrap, this is a good oportunity to do it (even if it'll break the rest of the app, that will be another issue). I will have to get the individual images used but till then we can just use some placeholders

**Comment by Mithilesh8** [comment]
Okay,  I would like to work on it.

**Comment by rolandgeider** [comment]
It's yours!

**Comment by 12people** [comment]
@Mithilesh8 Here's the Figma link: https://www.figma.com/file/5APvN3X7Lb1LQkechUPNbg/wger-design?node-id=408%3A1709

Might be useful for getting specific values. :)

**Comment by 12people** [comment]
Here's a quick mobile version: https://www.figma.com/file/5APvN3X7Lb1LQkechUPNbg/wger-design?node-id=812%3A10906

Note that I'm winging it with sizes and distances in certain places, so feel free to adjust those as you see fit.

Also, there are a lot of illustrations that consist of several elements. You don't need to implement those as separate elements, they can be inside one image (which I assume could make the development a lot easier).

**Comment by 12people** [comment]
Also, it'd be great if the top bar could be made to appear while scrolling up — that's just a nice-to-have, though.

**Comment by rolandgeider** [comment]
What was that page to generate faces @12people ?

**Comment by 12people** [comment]
https://thispersondoesnotexist.com/

but you can also use this free Flutter project, which gives you a bit more control: https://adityar224.github.io/Random-Face-Generator/#/
(source here: https://github.com/adityar224/Random-Face-Generator)

**Comment by rolandgeider** [comment]
Yes that was the one! This issue is about the web app, so no flutter packages for us

**Comment by 12people** [comment]
it's a Flutter web project, you can use it online too
(see the associated link)

**Comment by Mithilesh8** [comment]
Hi, I have created the specified design can you please check.
https://drive.google.com/drive/folders/1AkPL7ZMLigDsz7s37rJM1FH0W2yYPweS?usp=sharing

**Comment by rolandgeider** [comment]
@Mithilesh8 nice job!

**Comment by Mithilesh8** [comment]
Thank you. Can you tell me which all files are associated with the landing page?

**Comment by 12people** [comment]
Hi @Mithilesh8 

Great to see the progress!

I added a bunch of comments here, and it's of course up to you what you decide to implement: https://www.figma.com/file/5APvN3X7Lb1LQkechUPNbg/wger-design?node-id=968%3A10638

Also, here are exports of graphics used throughout the page that could hopefully be useful to you: 
[wger graphics.zip](https://github.com/wger-project/wger/files/9882191/wger.graphics.zip)

They're either SVGs or PNG exports at 2x resolution. Let me know if you need anything else. :)

**Comment by Mithilesh8** [comment]
I wanted to know the files in repository that involves the code of current landing page so that I can make the changes accordingly.

**Comment by rolandgeider** [comment]
The landing page is in wger/software/templates/features.html
