### ISSUE TITLE
Preferences birthdate quite bad interface usability

### ISSUE THREAD

**Issue by deddc23efb** [wger-project/wger#1121]
## Steps to Reproduce

1. ... Current version 2.1a3.dev0 docker image
2. ...create account, go to preferences, try to enter birthdate.
3. ...

I expect to be able to enter a birthdate in a format suitable for my locale.  I'm in Canada, YYYY/MM/DD is what we use.

The interface errors on most formats including standards US and Canada (DD/MM/YYYY, DD/MM/YY, YY/MM/DD, MMM DAY YEAR ) The error message is completely useless and no hint is given as to what format is acceptable.  To add insult to injury it's impossible to save the preferences with an empty birthday field, which is a strange restriction.

<details>
  <summary>Logs</summary>

```bash
```

</details>

**Comment by rolandgeider** [comment]
Yes, the preferences will get reworked for the next version, there is a lot of cruft there that is not useful anymore

**Comment by rolandgeider** [comment]
-> #1126
