### ISSUE TITLE
New user preferences shouldn't require a birthdate to save other preference values

### ISSUE THREAD

**Issue by deddc23efb** [wger-project/wger#1122]
## Steps to Reproduce

1. ...Current version 2.1a3.dev0 Docker
2... go to Preferences, try 

**Expected results:** Modify desired preferences (Units for example) press save and expect the changes to take effect.

**Actual results:** Nothing saves unless a birthdate is entered. 

A birthdate shouldn't be a mandatory personal preference.

```bash
```

</details>

**Comment by rolandgeider** [comment]
-> #1126
