### ISSUE TITLE
No way to change or edit an body weight record after creating it

### ISSUE THREAD

**Issue by deddc23efb** [wger-project/wger#1123]
## Steps to Reproduce

1. ... Current version 2.1a3.dev0 Docker

**Expected results:** If I make an error (ie in the units, which aren't displayed, when I enter a weight record, I expect to be able to eit the entry (or at least delete it and add a new one.)

**Actual results:** There appears to be no way to edit a body weight record.  I had to delete the user and recreate the account to get rid of the database entry.

</details>

**Comment by rolandgeider** [comment]
Hi! You can edit the weight entries, just go to the weight overview page and click on the arrow next to the entries
