### ISSUE TITLE
Document API with  OpenAPI 3

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1127]
The general API documentation won't win any prices, we should improve (so it becomes usable) with something like [drf-spectacular](https://drf-spectacular.readthedocs.io/en/latest/)

**Comment by Onesco** [comment]
I would love to work on this @rolandgeider if the task is till open.

**Comment by rolandgeider** [comment]
Hi @Onesco ! Sure, the issue is yours

(also note that drf-spectacular is just a suggestion, something else might be better)

**Comment by devilkiller-ag** [comment]
Hi @rolandgeider, I also want to work on this issue if you allow.

**Comment by rolandgeider** [comment]
Hi @devilkiller-ag ! @Onesco is already working on this, but you might be able to help each other?

**Comment by Onesco** [comment]
alright, @devilkiller-ag just push your changes more frequently so that we will not have a lot of conflicts to fix. Thanks!

**Comment by Leptopoda** [comment]
Any news on this issue?

Is there at least a valid spec that could be published?
I'm interested in writing my own client while using the spec to generate the client side lib. This would be independent of the server side code generation so if there already is a spec I'd love to hear.

**Comment by rolandgeider** [comment]
Hi! Sadly not. At the moment your best shot is to take a look at the browsable api, most of the entries ~are~ should be self explanatory. What exactly did you want to interact with? (exercises, workouts, etc.)

**Comment by Leptopoda** [comment]
I wanted to rewrite the flutter client.

I and a friend of mine want to redo a lot of things (offline first, ios, new design, as  much code generation and static analysis as possible ...) 
No offense but we don't think the current code is in a state where it makes sense to reuse it, thus we wanted to rewrite it from scratch. Obviously it'll be open source so when this becomes a thing we can give the code back to this org if desired.

Having a spec would let us generate the code so we'd basically only need to write UI code and some glue code.

**Comment by rolandgeider** [comment]
that's a huge undertaking! 😅

In any case I still have two weeks of vacation that I need to take in march, so I'll have some time to take drf-spectacular for a spin, we might be lucky and it'll work for most things out of the box.

**Comment by Leptopoda** [comment]
> that's a huge undertaking! sweat_smile

Yes it is :upside_down_face: 
Nevertheless working a lot with code generation lately I don't think this is impossible.

Thanks for having a look into it.

**Comment by Leptopoda** [comment]
That's awesome to hear!

keep me updated once something usable emerges

**Comment by rolandgeider** [comment]
I have installed the current version on the preview server. There's still some warnings and other fine tuning to do, but I think this can be already tested:

[Schema file](https://wger.rge.uber.space/api/schema/)
[Swagger UI](https://wger.rge.uber.space/api/schema/ui/)
[Redoc](https://wger.rge.uber.space/api/schema/redoc/)
