### ISSUE TITLE
Collect all authors for exercise base

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1137]
At the moment the different parts of an exercise have separate author histories (base, translation, images, videos, comments) thorugh the magic of `AbstractHistoryMixin`. We should collect all these separate infos for the base and expose it as a separate property and endpoint since for the end user there only the exercise. While this is an expensive operation DB wise, the results are cached anyway so this should be OK

**Comment by AdamPetik** [comment]
Hey @rolandgeider, I would like to help with this issue, can I start working on it?

**Comment by rolandgeider** [comment]
Hi @AdamPetik , sure go ahead. This is in the `feature/exercise-crowdsourcing` branch

**Comment by AdamPetik** [comment]
Hi, this is my first issue on this project, so I am a bit lost to be honest. Do I understand it right that I should collect some information related to ExcerciseBase model, provide them through a separate property (all of the collected information will be available through one property?) and HTTP endpoint? If so, what Information do I need to collect and how should HTTP response look like?

**Comment by AdamPetik** [comment]
Hi @rolandgeider, this is my first issue on this project, so I am a bit lost to be honest. Do I understand it right that I should collect some information related to ExcerciseBase model, provide them through a separate property (all of the collected information will be available through one property?) and HTTP endpoint? If so, what Information do I need to collect and how should HTTP response look like?

**Comment by rolandgeider** [comment]
hehe, don't worry, this has become a pretty big project!

The current author is saved in the `license_author` field. This together with a history app that records changes to the model, allows us to get a history of all the different users/authors that contributed to an exercise. Internally this exercise is separated into different models, but this is irrelevant to the user, which should just get the total list of authors. There is a property provided by `AbstractHistoryMixin` , `author_history`which iterates over this history and simply returns a list of strings with the names.

In this issue, we want to simply collect these lists (sets actually) from the exercise base, all translations, images and videos and return them as a new property, e.g. total_author_history. This can then be easily exposed over the api by adding a new field to `ExerciseBaseInfoSerializer`
