### ISSUE TITLE
mobile app out of sync and missing data

### ISSUE THREAD

**Issue by abienz** [wger-project/wger#1152]
I noticed that after creating a workout with all my exercises for each day through a week it eventually went blank.

I decided to use the website and logged my workout and created a schedule.

The mobile app only displays the workout name but no exercises and be log of previous day's.

I have cleared the cache and saved data but problem persists.

**Comment by rolandgeider** [comment]
Hi! Have you updated the app these days? We recently pushed an server side update, but you should have gotten a notification about that. Also, did you install from the Play Store or from f-droid?

**Comment by abienz** [comment]
Installed through F-Droid version 1.4.1 added on 21/01/2022, I installed this on Monday

**Comment by rolandgeider** [comment]
ah that explains it, we can't currently push new releases to f-droid since a dependency on the play services slipped in. There's already an issue to remove it, but I can't tell you when this will be ready. As a workaround you can install from the play store, that version works
