### ISSUE TITLE
Descriptions UI is broken

### ISSUE THREAD

**Issue by mohammadrafigh** [wger-project/wger#1190]
## Steps to Reproduce

When contributing a new exercise on web, at descriptions stage the UI is completely broken something is not loaded correctly.

1. Contribute a new exercise
2. Continue steps through descriptions
3. You see the UI is broken

![202282006-33bae82b-ba4f-451e-ab57-7e61fa3cd80c](https://user-images.githubusercontent.com/6737508/202936559-d8fdcdad-b0f8-40e2-8ca7-f48e0b6bdaeb.png)

**Comment by rolandgeider** [comment]
Have fixed the editor. We should think about how to avoid such bugs in the future, but for the moment this works again


<img width="914" alt="Bildschirm­foto 2022-11-21 um 12 27 22" src="https://user-images.githubusercontent.com/2280729/203039641-402f349c-5c15-4794-8b86-13b14ea5cd8a.png">
