### ISSUE TITLE
F-Droid version is not the latest version

### ISSUE THREAD

**Issue by EthanLatimerGB** [wger-project/wger#1241]
Currently on the F-Droid store, the latest wger version is 1.4.1, instead of 2.1. Surprised this has not been brought up as an issue before. Since the F-Droid version will be almost a year out of date.

**Comment by rolandgeider** [comment]
Yes, a dependency on the play services slipped in, till we remove it we won't be able to update the f-droid version: wger-project/flutter/issues/152. We definitely want to get a current build published again!

(closing here)
