### ISSUE TITLE
Update body weight tab

### ISSUE THREAD

**Issue by jakeau** [wger-project/wger#1248]
Change from body weight to 'Body tab' 

Not just have body weight, but also include the ability to track muscle size (ie waist, arms, quads). 
Include body fat tracking.
Body progress pics ability to appear on weight graph to view weight vs body progress.

**Comment by rolandgeider** [comment]
Like in the app with the measurements? There's already an issue for that, the backend and everything is ready

https://github.com/wger-project/react/issues/13
