### ISSUE TITLE
Data consistency issues

### ISSUE THREAD

**Issue by rocket357** [wger-project/wger#1253]
## Steps to Reproduce

1. Deploy docker via production compose yaml file. Ensure SITE_URL and CSRF_TRUSTED_* is set
2. Put behind reverse proxy
3. Create user with unique password.
4. Login via web browser, add workout schedule, nutrition plan, etc...
5. Install wger android app on phone.
6. login to my instance via android app using created user with unique password.
7. No data?!?
8. Add data via android
9. Verify android data + web browser data is visible in web browser!
10. Add new data in web browser.
11. Still only the android data shows in android!??

**Expected results:** Expected to see browser-added data in android app as well.

**Actual results:** Unable to see data added via the web browser in android app.

<details>
  <summary>Logs</summary>

(Note: DJANO_DEBUG is true in config/prod.env, but doesn't seem to be logging anything additional)

docker01:~/docker-wger# docker-compose up -d
wger_db is up-to-date
wger_cache is up-to-date
Recreating wger_server ... done
wger_nginx is up-to-date
docker01:~/docker-wger# docker logs -f wger_server
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 13.84s.
yarn run v1.22.19
$ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
Done in 6.31s.
Performing database migrations
Operations to perform:
  Apply all migrations: actstream, auth, authtoken, axes, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight
Running migrations:
  No migrations to apply.
  Your models in app(s): 'config', 'core' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Set site URL to https://wger.$REDACTED
Using gunicorn...
[2023-02-08 20:18:51 +0000] [73] [INFO] Starting gunicorn 20.1.0
[2023-02-08 20:18:51 +0000] [73] [INFO] Listening at: http://0.0.0.0:8000 (73)
[2023-02-08 20:18:51 +0000] [73] [INFO] Using worker: sync
[2023-02-08 20:18:51 +0000] [74] [INFO] Booting worker with pid: 74

```
docker01:~/docker-wger# docker-compose exec web python3 manage.py makemigrations
Migrations for 'config':
  wger/config/migrations/0003_delete_languageconfig.py
    - Delete model LanguageConfig
Migrations for 'core':
  wger/core/migrations/0016_alter_language_short_name.py
    - Alter field short_name on language
docker01:~/docker-wger# docker-compose exec web python3 manage.py migrate
Operations to perform:
  Apply all migrations: actstream, auth, authtoken, axes, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight
Running migrations:
  Applying config.0003_delete_languageconfig... OK
  Applying core.0016_alter_language_short_name... OK

```
Issue persists after migrations, so I'm a bit at a loss here.  Any help is appreciated.

</details>

**Comment by rolandgeider** [comment]
Hi! The only explanation could give you is that the app is logging into a different server. Do you see in the docker logs calls to /api/v2/stuff when using the app? Also, when you log out and in again on the app do you still see everything you entered before?

**Comment by rocket357** [comment]
This gets weirder and weirder.

I added a workout plan via the app, then verified I could see it in the browser.  In the browser I added a workout to the workout plan, then verified it showed up in the app.

It's acting as if the top level data containers aren't visible in the app if they were created in the browser.

api/v2 shows up from my cell phone's IP in the nginx logs.

**Comment by rolandgeider** [comment]
🧐

that's really weird, the api just exposes all your objects. Are you using the app from the play store? The one from fdroid can't be updated because of a dependency and might have problems.

**Comment by rolandgeider** [comment]
on the other hand, there might be some local caching in the app

**Comment by rocket357** [comment]
Yes, the app was installed via the play store (however I do have some f-droid applications on this phone...).  Interesting.

Is there a way to clear the app's cache and force it to update?

**Comment by rolandgeider** [comment]
Logging out and in should clear it

I'll try to see if I can reproduce this, if it is indeed a cache it should be easy to fix

**Comment by rocket357** [comment]
I logged out in the app and logged back in, and the data was missing.

Data is still visible via the browser (both added from the app and added from the browser).

I tried logging out and back in on wifi/4g, using the created username + the email as the username, none of the data is showing up in the app now (but still there according to the browser).  Something is definitely wrong with my app install.

**Comment by rocket357** [comment]
https://github.com/wger-project/flutter/issues/260#issuecomment-1278002563 seems to be related to what I'm seeing.

**Comment by rolandgeider** [comment]
I think I know what's happening, I'll try to roll out a fix the next days

**Comment by rolandgeider** [comment]
Have added a pull to refresh to the different lists to manually trigger an update. Otherwise everything should be fetched when re-opening the app

**Comment by rocket357** [comment]
Just updated the app to 1.5.2.  Everything is resolved.

Thank you for the quick response and fix!
