### ISSUE TITLE
Timer  exercises

### ISSUE THREAD

**Issue by clafalco** [wger-project/wger#1256]
## Proposal

hello, it would be convenient to insert a timer in the timed exercises.

**Comment by rolandgeider** [comment]
You mean like in the app? Or rather a countdown?

**Comment by clafalco** [comment]
Countdown

**Comment by rolandgeider** [comment]
ah yeah. We will definitely do something like that in the future, but I'm closing this issue as there is already one for that: wger-project/flutter/issues/305
