### ISSUE TITLE
Site not connect

### ISSUE THREAD

**Issue by clafalco** [wger-project/wger#1258]
## Steps to Reproduce

1. ...Are there any problems on the site?
2. ...
3. ...

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```bash
```

</details>

**Comment by rolandgeider** [comment]
Hi! Should be running again, somehow the webserver shut down

**Comment by clafalco** [comment]
it restarted for a while, then went off again 🥺

**Comment by rolandgeider** [comment]
You're right, strange. I'll keep an eye on it

**Comment by clafalco** [comment]
ok it started again, today without this fantastic application, during training I felt lost!!!😭😭😭

**Comment by rolandgeider** [comment]
😂😂😂

I've tweaked a bit the server config, should re-start on its own now (hopefully, as I won't be able to login to the server till I'm back home on Friday)
