### ISSUE TITLE
Wger using american style of dates which not used almost anywhere else

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [wger-project/wger#1260]
## Steps to Reproduce

1. Start to enter dates anywhere in web ui. issue visible immediately

**Expected results:** 

I prefer to see normal date format like it used everywhere in world. 

**Actual results:** 

I see dates in format month-day-year. whitch used only in USA and another 5 countries . Most of countries in world using 
day-month-year. 

Logs not needed because it is implementation bug. 
![ksnip_20230220-131335](https://user-images.githubusercontent.com/22169129/220105988-aa06fdab-c30e-4360-bb62-352ee4f03f82.png)

I suggest to make possible to configure prefered date format. So usa people will use USA format and all another will use format they like.

**Comment by rolandgeider** [comment]
Hi! Yes you are right, currently when using the app in English, it loads all date and number formats for en-US, without any possibility of changing it.

This is beeing handled in #1245 so I'm closing here, but that's something that will be fixed in the future
