### ISSUE TITLE
Conversion Bug

### ISSUE THREAD

**Issue by RegalMonkey** [wger-project/wger#1300]
Looks like one of a few issues between KG and LBS, the plate calculations displayed on the android app calculate only to a 20 (unit) bar, presuming it as KG for the baseline. 

As an example, putting 225 LBS should calculate out as 2 * 45 LBS on each side with a 45 LBS bar standard. The app however lists out 6 X 15 + 1 X 10 + 1 X 2.5 per side, leaving 20 left over which would make sense for a 20 KG/45 LBS bar, but the plate stacking actually results in 245 LBS if one where to use the plates proposed with a standard bar and figured them in the lbs measure.

Tough to write out, but short form the app appears to presume KG even if LBS are set as the unit when calculating plates.

**Comment by rolandgeider** [comment]
Hi! Good catch. You are right, the plate calculator currently assumes a 20 (kg) bar. There is an issue to make this configurable (https://github.com/wger-project/flutter/issues/46), but in addition to that we will need to actively change the pre set weights based on the weight units

**Comment by rolandgeider** [comment]
just updated the other issue mentioning that the calculation should change accordingly, closing here so that it doesn't get cluttered
