### ISSUE TITLE
Bugged search results, extremely hard to find routine excersises

### ISSUE THREAD

**Issue by wolfred24** [wger-project/wger#1317]
## Steps to Reproduce

1. ... Search for an excersise when creating a routine, for example pull ups
2. ... Just "pull ups with machine" appear at search results.
4. ... So, write Pullups, (nothing appears).
5. So what in the world should i search to find pull ups? well i should write Pull-ups to find pull ups, and yea , its a hell to find any excersise, could you guys pls improve the search function?

**Expected results:** 
Pull ups should appear at search results even if i write "pull ups" or "pullups" or "pull-ups" or anythyng related to "p u l l u p s"

**Actual results:** 
Nothing appear at search results when searching for excersises if you dont write the excercise name "EXACTLY"

<details>
Tested on desktop linux app and on web app.
Also it will be nice if u add a picture preview of the excercise at search results on web version.

**Video:**

https://user-images.githubusercontent.com/25995755/236281745-166ad2a3-a136-447a-8110-3983515e606b.mp4

</details>

**Comment by rolandgeider** [comment]
yeah you are right, it also doesn't help that there are potentially many different names for the same exercise and while aliases is something we can already track, it has the same matching problems as with the regular names. There's already an issue to use full text search in the database for this, #652, and is planned to be included in this release but can't tell you when exactly

Closing here to keep the issue list manegable
