### ISSUE TITLE
Reset Password Link in E-Mail is wrong

### ISSUE THREAD

**Issue by DunklerPhoenix** [wger-project/wger#1320]
## Steps to Reproduce

1. set up example docker compose
2. replace SITE_URL=http://localhost/ with SITE_URL=https://mydomain.com
3. use reset password

**Expected results:** 
In E-Mails the links should all start with https://mydomain.com

**Actual results:** 

Maybe the mail template is wrong or the SITE_URL shouldn't be entered with https://, but the link to recover a password starts with `https://https/://` 

```
Diese E-Mail wurde aufgrund einer Anfrage zum Zurücksetzen des Passworts auf der Website https://mydomain.com/ versendet.

Bitte öffne folgende Seite, um dein neues Passwort einzugeben:

https://https/://mydomain.com/de/user/password/reset/check/Mw/bnvnrc-f691b9c43e49dd4c4ba0b73e7a1d2a78


Dein Benutzername, falls du ihn vergessen hast: test

Vielen Dank, dass du unsere Website benutzt!

Das Team von https://mydomain.com/
```

**Comment by rolandgeider** [comment]
you're right, there's some duplication going on somewhere
