### ISSUE TITLE
v2 not found 

### ISSUE THREAD

**Issue by joa793** [wger-project/wger#1329]
## Steps to Reproduce

I am making a simple request to the api with https://wger.de/api/v2/exercise/?limit=10 but it tells me error that v2 is not found

**Expected results:** 

HTTP 200 OK
                    
                        Allow:
                        GET, HEAD, OPTIONS
                    
                        Content-Type:
                        application/json
                    
                        Vary:
                        Accept
                    
                
{
    "count": 1223,
    "next": "https://wger.de/api/v2/exercise/?limit=10&offset=10",
    "previous": null,
    "results": [
        {
            "id": 345,
            "uuid": "c788d643-150a-4ac7-97ef-84643c6419bf",
            "name": "2 Handed Kettlebell Swing",
            "exercise_base": 9,
            "description": "
Two Handed Russian Style Kettlebell swing",
            "creation_date": "2015-08-03",
            "category": 10,
            "muscles": [],
            "muscles_secondary": [],
            "equipment": [
                10
            ],
            "language": 2,
            "license": 2,
            "license_author": "deusinvictus",
            "variations": [
                345,
                249
            ],
            "author_history": [
                "deusinvictus"
            ]
        },

**Actual results:**  --> 

.ts:16  ERROR {body: {…}, url: 'https://wger.de/api/v2/exercise/?limit=10', headers: HttpHeaders, status: 404, statusText: 'Not Found'}body: {error: "Collection 'v2' not found"}headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}status: 404statusText: "Not Found"url: "https://wger.de/api/v2/exercise/?limit=10"[[Prototype]]: Object
handleError @ core.mjs:8416

**Comment by rolandgeider** [comment]
Hi! Everything seems to be working fine?
