### ISSUE TITLE
MAX rep show this

### ISSUE THREAD

**Issue by MorugaSkorpion** [wger-project/wger#1337]
![image](https://github.com/wger-project/wger/assets/69608049/88032e0f-ad3e-4acb-b0df-6a5bff3b194d)

Hi, on app this don't appear. 
Thx guys for this app. 
i use firefox

**Comment by rolandgeider** [comment]
Oh yes, it seems instead of using English as a fallback, it is just outputting the translation key

**Comment by rolandgeider** [comment]
Alright, should be fixed
