### ISSUE TITLE
User is allowed to enter an invalid exercise to a training day

### ISSUE THREAD

**Issue by chanalv** [wger-project/wger#1357]
## Steps to Reproduce

1. When adding an exercise to a training day, leave the "Exercises" field blank or type in an invalid exercise that is not on the list of exercises.
2. Click "Save".

**Expected results:** 
I expected the "Exercises" field to be required and to be prevented from submitting the form.

**Actual results:** 
The form is submitted despite the blank or invalid exercise entry and creates an anomalous exercise under the training day, as seen in the image below.

![image](https://github.com/wger-project/wger/assets/91583603/3f0a3763-6830-47c7-a626-3243616e5a98)

**Additional notes:**
This issue can be reproduced in both the live system on https://wger.de/ and when running a development build (Git SHA-1: aaa822e4afc739cb664d016ce1b1a8a683957ae6). I tried implementing a quick fix by making the "Exercises" field required, as shown in the image below. It successfully prevents the user from submitting a blank or invalid exercise entry, but I couldn't get an error message to appear and it failed two of the tests, which makes me curious if there's a functional reason for the field to remain optional?

![image](https://github.com/wger-project/wger/assets/91583603/d496ae08-db8b-4a5c-81d3-b28699abcc85)

**Comment by aditi-dsi** [comment]
Hey, I am taking up this issue.

**Comment by AggelosK26** [comment]
Hey, can I be assigned this issue?
