### ISSUE TITLE
Upper scaling of y-axis in weight overview chart

### ISSUE THREAD

**Issue by voszp** [wger-project/wger#137]
The upper scaling of the y-axis derives from the max weight ever recorded. Therefore the graph seems to be cut by the chart frame sometimes. 

Upper scaling of y-axis should include some 1-3kg extra.

Found on selfhosted dev-version and wger.de-version

**Comment by rolandgeider** [comment]
I think there is an extra 1kg or so, but it can be that it's only on the lower y-axis, will check.
