### ISSUE TITLE
Request: Show total daily calories on nutrition plans

### ISSUE THREAD

**Issue by voszp** [wger-project/wger#138]
For comparision the calculated amount of total daily calories could be displayed on the nutrition plans overview ("Your nutrition plans") and on every detailed nutrition plan. In last case "Energy" and "Total daily calories" should be organized in tiers.

Link the value of "Total daily calories" to the calculator page.

**Comment by rolandgeider** [comment]
Yes, good idea.

What do you mean with organizing the energy and daily calories in tiers?

**Comment by voszp** [comment]
The should be displayed one upon the other like doing a pen-and-paper calculation

**Comment by rolandgeider** [comment]
Ah, OK
