### ISSUE TITLE
Bug: "Edit set" Dialogue

### ISSUE THREAD

**Issue by voszp** [wger-project/wger#140]
Adding a exercise via the "Add exercises to this workout day"-button and leaving the repetitions boxes blank causes the wger to add the exercise to the workout and display an "edit-them-now" button. Clicking this button opens the "Edit set" dialogue, which only shows one box for repetitiions. Number of boxes should be equal to the "number of sets" set before.

Bug observed on self-hosted dev-version and wger.de version

**Comment by rolandgeider** [comment]
The edit dialog is indeed a bit awkward, specially when there are no repetitions (which won't be allowed anymore after #165 is done). Also the way django's formsets (basically, a multi-form display) are currently rendered by the application is very much not optimal

**Comment by PolarFox** [comment]
Numbers of sets shown here is number of sets -1? Or that's how I observed this. 3 sets shows 2 sets in edit box.
