### ISSUE TITLE
CSS mismatch in localized web pages

### ISSUE THREAD

**Issue by milotype** [wger-project/wger#1401]
## Steps to Reproduce
1. Please take a look at the screenshot

![unordered list button and text align](https://github.com/wger-project/wger/assets/43657314/5b5ee102-73fc-4040-8f30-1b10c64c8ddd)

**Expected results:** 
All localized web pages should use the same CSS styles.

**Actual results:** 
Several localized web pages don't use the same CSS styles.

Please also check the issue "Justification of unordered lists #1380 "

**Comment by rolandgeider** [comment]
We are definitely not using different CSS for different languages 😅 ! However, the landing page is cached, so this might be something related to that?

**Comment by milotype** [comment]
I don't know what you mean with cached landing page. When I reload the websites the issue still remains.
Firafox browser: 78.15.0esr (64-bit)

**Comment by milotype** [comment]
Thank you for checking.
I'm not a programmer, and I cannot update my Firefox 78.15.0esr (64-bit) because of my Mac OS 10.11.6.
But when I use "Safari" on my iPhone 13 (version 16.5.1 (c) the "bullet" in the English page doesn't appear. But all three languages still use `text-align: justify`
