### ISSUE TITLE
Add language dependant decimal separators

### ISSUE THREAD

**Issue by milotype** [wger-project/wger#1402]
## Steps to Reproduce
1. ... Open https://wger.de/en/software/features
2. ... Open https://wger.de/hr/software/features
3. ... Open https://wger.de/de/software/features

## See screenshot
![wger decimal separators](https://github.com/wger-project/wger/assets/43657314/8baa6b42-fd49-4df9-b397-3de7a694fb7d)

**Expected results:** 
The counts should have decimal separators

**Actual results:** 
The counts don't have decimal separators

Take a look at https://en.wikipedia.org/wiki/Decimal_separator

**Comment by rolandgeider** [comment]
good idea! this should be easy to implement with django's helper functions

**Comment by rolandgeider** [comment]
note that this should be also done to other large numbers, such as the kcal values (I don't think we have other places where we use number with more than 4 digits)

**Comment by milotype** [comment]
@rolandgeider Yes! This should be implemented wherever numbers/counts are used!

**Comment by Brandon-Lu737** [comment]
Hi I'm working on this guys! Should be up in one or two days.

**Comment by rolandgeider** [comment]
![image](https://github.com/wger-project/wger/assets/2280729/f560028c-ab68-4b65-a75a-ee799f8ac2b9)

django now correctly handles large numbers (thanks @Brandon-Lu737 ), this still needs to be done in react

**Comment by rolandgeider** [comment]
Russian
![image](https://github.com/wger-project/wger/assets/2280729/b8312513-44a2-4e69-8576-a617eae7cd06)

German
![image](https://github.com/wger-project/wger/assets/2280729/227fa5d3-0cb2-430c-acd8-dbfb1d7c30e7)

Closing issue (will be available on master once I finish a couple of little things)
