### ISSUE TITLE
psycopg2 needs a installed libpq.so.5 library

### ISSUE THREAD

**Issue by bbkz** [wger-project/wger#1409]
The [commit](https://github.com/wger-project/wger/commit/02697acdf0d1129100b3a6c243ac883c0e64af53) removed the `libpq5` library from the final image, but i think this is needed for psycopg2.

At least for me on x86_64 i get the following error:

```bash
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: libpq.so.5: cannot open shared object file: No such file or directory
```

## Steps to Reproduce

Run the latest `master` image and watch the logs.

**Comment by rolandgeider** [comment]
yes, just ran into this as well

**Comment by rolandgeider** [comment]
alright, should be fixed

this evening I'll fix that we were pushing the images to master and were ignoring latest and 2.2 😅
