### ISSUE TITLE
Bug: Auto completion of newly created exercises

### ISSUE THREAD

**Issue by voszp** [wger-project/wger#141]
After creating a new exercise it won't appear in the auto completed lists of search fiedls. This pertaines the following search fields:

- Exercises -> Search field
- "Add exercises to day" - dialogue  -> Exercises

Observed on self-hosted dev-version 1.601-dev

**Comment by rolandgeider** [comment]
New exercises have do be approved by an admin first. If an administrator adds the exercises they should appear immediately. Will check this.

**Comment by rolandgeider** [comment]
I just tested this, new exercises (added by admin) show correctly in the autocompleter(s) using the last version from master. I'm closing the issue to keep the list manegable, but if you still see this in your local installation, just re-open it!

**Comment by w00p** [comment]
I have the same problem. Running versjon 1.7, production with Apache2. Any clue how i can troubleshoot this? The search form and autocomplete works fine if i enter Exercises and using the search form on the right side. But not on Add exercises to day modal form.

**Comment by rolandgeider** [comment]
@w00p thanks for finding this bug, I'll take another look at this. Which version of python are you using? Did you install 1.7 stable or are you using master?

**Comment by w00p** [comment]
Thank you
I am using the stable from 28 Feb. 
Python 2.7.11+
OS: Ubuntu 16.04
Apache2: Apache/2.4.18

**Comment by w00p** [comment]
Hi, i also did a test on latest version. 1.8a2-dev.
Python 2.7. Ubuntu 16.04
You can take a look at [http://ut.kaffetur.no](url)
Any clue what is wrong?

**Comment by rolandgeider** [comment]
@w00p I just took a look at the current git master, there was indeed an error there. If you do a git pull (and since you are using apache, a ```python manage.py collectstatic``` after if), the autocompleter should work again

**Comment by w00p** [comment]
Ahh sweet now it works. Thank you guys. Love the work of Wger.
I will continue to translate into Norwegian.

**Comment by rolandgeider** [comment]
thanks!!

I saw you started translating it on transifex, if you have questions about the strings, just ask (I can also install the translations to the preview server so you can see them in context).

I'm closing this issue again
