### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by rabywastaken** [wger-project/wger#1413]
## Steps to Reproduce

1. Go to https://wger.de/ 
2. ???
3. Profit!

**Expected results:**

I expected the site to not be down and be able to create an account.

**Actual results:**

![image](https://github.com/wger-project/wger/assets/31973406/4f1d4588-d2f7-45cf-890b-0f9df6d6095e)

![image](https://github.com/wger-project/wger/assets/31973406/f5a821ca-7bf9-4c2d-82c8-b9022aa2b45c)

EDIT: Added another picture to prove it's not just me having the issue.

**Comment by rolandgeider** [comment]
You can go now back to profit, just restarted the server. Will try to find out later what happened
