### ISSUE TITLE
wger flatpak app not working

### ISSUE THREAD

**Issue by manikandancode** [wger-project/wger#1435]
OS: Ubuntu 23.04 Wayland

After 

> flatpak run de.wger.flutter

UI
![Screenshot from 2023-09-25 17-13-34](https://github.com/wger-project/wger/assets/46480489/991e728f-6990-4f01-b245-b2177d6b8733)

Terminal log:

![Screenshot from 2023-09-25 17-16-47](https://github.com/wger-project/wger/assets/46480489/5ae5c092-78a9-4cef-9318-e416128416e3)

**Comment by bbkz** [comment]
Hi,

there is already a issue in the flutter repository for this:

* https://github.com/wger-project/flutter/issues/424

The used library for the barcode scanner isn't supported on linux.

**Comment by rolandgeider** [comment]
(closing here)
