### ISSUE TITLE
Verify email fails

### ISSUE THREAD

**Issue by prevail90** [wger-project/wger#1436]
1. Recieve email for email verification.
2. Click the link in email
3. Recieve an error occurred. Something happened that caused an error.

**Comment by rolandgeider** [comment]
Hi! Is this on your own instance? Is there any other error or message in the logs?

**Comment by prevail90** [comment]
No this is from wger.de

**Comment by rolandgeider** [comment]
ok, then I should be able to find something

**Comment by rolandgeider** [comment]
mhh, it just worked fine. Can you try again? Does it always result in an error?

**Comment by rolandgeider** [comment]
nevermind, I found it. It seems it's possible to register twice with the same email... You had two users, "prevail90" and "chevylover1001", should I delete the second one, the last login was in may.

I will also open an issue about the registration thing, that obviously shouldn't happen

**Comment by prevail90** [comment]
Yes please

**Comment by rolandgeider** [comment]
Alright done

**Comment by rolandgeider** [comment]
(closing the issue, feel free to reopen if this still doesn't work)
