### ISSUE TITLE
Invalid literal for int

### ISSUE THREAD

**Issue by ados8** [wger-project/wger#1498]
Installation of brand new dockers on Unraid.
Installation was postgres 12.5 and then new postgres 15.

Expected dockers to run and begin setup of platform.

Postgres docker runs fine but Wger docker stops shortly after runnning.
Issue appears in the Wger build itself.
`ValueError: invalid literal for int() with base 10: ''`
`ValueError: invalid literal for int() with base 10: ''`
![image](https://github.com/wger-project/wger/assets/49982433/26a7821a-110a-4cbb-9c01-e4ee65382a70)
Database check confirms created
![image](https://github.com/wger-project/wger/assets/49982433/afea784a-448e-4fba-b28b-817568f363be)

I'm thinking this is a bug in Wger.

**Comment by ados8** [comment]
Found the issue is the Unraid template.
Removing all env values to just the port and it builds.
However this is the web portal.
![image](https://github.com/wger-project/wger/assets/49982433/8e9edb8b-3073-4885-8d69-a2273b03a9cd)
Multiple browsers and both internal IP as well as external domain has the same issue.
In this configuration no external SQL database is being used.

**Comment by ados8** [comment]
So, if you remove all the email env entries from the template it builds.
Problem is somewhere in there but then the portal doesn't load.
![image](https://github.com/wger-project/wger/assets/49982433/d891b626-6c3d-49a9-af82-9c16ef044808)

**Comment by rolandgeider** [comment]
discussed this on discord, closing here
