### ISSUE TITLE
Registration problem

### ISSUE THREAD

**Issue by ninefix** [wger-project/wger#1504]
## Steps to Reproduce

1. Open the registration web page (https://wger.de/en/user/registration)
2. Fill out the fields
3. Click on the Register (green button)

**Expected results:

I expected to receive a feedback message and the receive an email with verification link

**Actual results:

Nothing happen, the page doesn't reload or give feedback

<details>

I've tried with different SO: Windows, Linux, MacOsX

I've tried with different browser: Chrome, Firefox, Brave, Safari

</details>

**Comment by rolandgeider** [comment]
hi! Thanks for the bug report, you are right, there was a problem with the reCaptcha javascript, should be fixed now, can you try again?

**Comment by ninefix** [comment]
Hi, now it works perfectly

I've received the confirmation email and now I'm logged in

Solved!! Thanks

**Comment by rolandgeider** [comment]
🙌🏻
