### ISSUE TITLE
Widget for selecting muscles

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#154]
There should be a form widget to select muscles, this can be useful e.g. in the exercise edit view.

The widget could be just the same multi-select box with a diagram similar to the one in the muscle overview that highlights the selected entries.

**Comment by rolandgeider** [comment]
If #171 is implemented, the angularJS libraries will be available and could perhaps be used here.

**Comment by gudvinr** [comment]
Hello.

I tried adding new exercises and found out that muscle selection process isn't very convenient. And wanted to suggest this kind of widget but you already got this idea.

Interactive widget would be most convenient solution but it is also not a trivial thing to do. And it is also tricky to make this right and not to do an unusable mess.

However, there is still a room for relatively simple improvements:
* Split muscles into groups: arms, legs, upper body, lower body, etc. There could be multiple levels. 
* Add static image with muscle names. With muscle groups there could be multiple images with highlighted areas.

**Comment by rolandgeider** [comment]
It's definitely not trivial 😅

Another more easy alternative could be to give each muscle an optional common name so that "gluteus maximus" can be also displayed as "butt" and "biceps femorii" would be just "biceps"
