### ISSUE TITLE
Add custom form redirect

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#157]
Right now, all the forms have a default redirection target. Since some of them can be accessed from different pages, it would be useful to be able to add a `next` parameter to the the form to control where to send the user. Perhaps there are already django apps that could be used for this.

**Comment by ehmadzubair** [comment]
@rolandgeider happy to take on this task. Is it still relevant?

**Comment by kuggaa** [comment]
Yes I think it is

**Comment by rolandgeider** [comment]
Hi! Yes it is, feel free to give it a try

Am 19.10.2017 um 12:51 schrieb Ehmad Zubair:

**Comment by namankhurpia** [comment]
Hi i will try to solve it, kindly accept my pr for hacktoberfest

**Comment by rolandgeider** [comment]
Hi there! Sure, go for it
