### ISSUE TITLE
"Workout plan" image linked in README is missing

### ISSUE THREAD

**Issue by thecashewtrader** [wger-project/wger#1591]
[Not a problem with the wger software itself, I picked the issue type which I thought fit best]

It currently links to https://raw.githubusercontent.com/wger-project/wger/master/wger/software/static/images/workout.png which throws a 404.

I just found wger, from what I checked, I think https://raw.githubusercontent.com/wger-project/wger/master/wger/software/static/images/screens-3.png is what it should link to.

**Comment by rolandgeider** [comment]
you are right, should be fixed now
