### ISSUE TITLE
Add USDA food import

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1640]
We need an import script similar to the one for open food facts:

https://fdc.nal.usda.gov/download-datasets.html

* Foundation Foods
* Branded

There are currently some ingredients in the database that were originally imported from USDA, but we have neither the import script not the original dataset, so we would need to either remove all the ones not used in a nutritional plan or log, or try to match them by name in a first step.

We currently use the `code` field for OFF products as a foreign ID to later allow for easier updates of the entries. USDA has generic products as well as branded ones, do these also have a known barcode? In any case it might be a good idea to add a proper foreign_id field where we would store the `fdcId`

Also, since these exports are updated just twice a year, I don't think we need any automatic process

**Comment by Dieterbe** [comment]
when these items show up in wger, will it be clear where the information comes from? e.g. will it mention USDA, or maybe a web link to the USDA item?
