### ISSUE TITLE
goals on nutritional plan remain set

### ISSUE THREAD

**Issue by Dieterbe** [wger-project/wger#1641]
## Steps to Reproduce

1. create nutritional plan
2. under edit, "add goals to this plan"
3. add a number under protein
4. save
5. edit the plan again, and UNCHECK "add goals to this plan"
6. save again
7. open "edit" again. "add goals to this plain" is still checked with the goal intact. it should be unchecked

i think the proper fix is, when you uncheck the "add goals", is to unset all goals fields - that's what the flutter app does.

**Comment by IlyasOsman** [comment]
Hey, I would like to work on this.

**Comment by Dieterbe** [comment]
Go for it! thank you. let me know if you have further questions (you can also find me on our discord)

**Comment by IlyasOsman** [comment]
Thank you. I'll contact you for any further questions.

**Comment by Ganesh96** [comment]
Hey, I am new to python development and thought I should work few real-time projects to get experience.
can you guys guide me?

**Comment by rolandgeider** [comment]
Hi! This would be actually a react thing since it's part of the frontend. Also, @IlyasOsman might be working on this?

**Comment by sanjanaimandi** [comment]
hey i would like to work on this problem!

**Comment by svetozar12** [comment]
Hello I would love to work on this issue, if it isn't already taken by someone.

**Comment by rolandgeider** [comment]
@svetozar12 go ahead!

**Comment by rolandgeider** [comment]
@svetozar12 heads up, I saw that you cloned this repo but that nutrition part is done in react: https://github.com/wger-project/react

**Comment by svetozar12** [comment]
@rolandgeider thank you so much, I was wondering where is the react :D

**Comment by svetozar12** [comment]
one quick question, I should make my pr to https://github.com/wger-project/react right ?
