### ISSUE TITLE
Don't allow empty sets

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#165]
At the moment there is no validation when adding a new exercise to the workout without any repetitions.

When working on this issue it's probably a good idea to refactor the logic for this and let django do more of the heavy lifting.

**Comment by Yevs** [comment]
Hi there. I seem to be new one here but I think I can fix this bug.

**Comment by rolandgeider** [comment]
Awesome! Sure, go ahead!

PS: I will probably have no internet this weekend

**Comment by Yevs** [comment]
oops, wrong commit, so sorry. let me fix this real quick
