### ISSUE TITLE
[BUG] "Download as PDF" option does not work

### ISSUE THREAD

**Issue by Maniues** [wger-project/wger#1658]
## Steps to Reproduce

1. Log in and enter to your workout routine 
2. Click on `Options` and `Download as PDF`
3. Set your settings and confirm

**Expected results:** 
The PDF with the table or log starts to download.
**Actual results:** 
An error occurs.
<details>
  <summary>
</summary>

```Page not found
The page you requested does not exist.
```

</details>

**Comment by rolandgeider** [comment]
good catch! The problem was that (like all numbers in templates), theIDs used for the form were localized, so instead of getting to /pdf/1000/... this would output /pdf/1.000/... which obviously doesn't exist.
