### ISSUE TITLE
Website is incredibly slow lately

### ISSUE THREAD

**Issue by sTiKyt** [wger-project/wger#1690]
## Steps to Reproduce

Open the website
Go to workouts, pick one, open it

**Expected results:** 
It should load
**Actual results:** 

Stuck like this for minutes till it loads:
![image](https://github.com/wger-project/wger/assets/35602029/39b8277d-bd86-44ba-9012-c02a26385694)
![image](https://github.com/wger-project/wger/assets/35602029/62b328fd-fe08-43b9-8af7-37206a656635)

It loads so slow i could literally do 1/8 of my entire workout before the site loads it...

**Comment by rolandgeider** [comment]
Hi! yes, I have noticed it too. This is very probably due to the increased number of ingredients, I'm trying to weed out the places that are causing this load on the system

**Comment by rolandgeider** [comment]
alright, it should feel (and be) faster now
