### ISSUE TITLE
Add filter possibility for body weight chart

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1696]
At the moment the body weight chart shows all the entries, which can be a lot if they were imported. We should only show the last year (?), and provide some toggle buttons to show all / last year / last six months (or other useful ranges)

**Comment by ChrisUlicny** [comment]
Hi, can i work on this ?

**Comment by ChrisUlicny** [comment]
This issue is addressed by https://github.com/wger-project/wger/pull/1808 and https://github.com/wger-project/react/pull/988.

**Comment by Dieterbe** [comment]
> We should only show the last year (?)

one approach i added into the flutter app is to make it density aware.
e.g. if you would like to see at least 20 datapoints on the chart, but not (say) more than 100 to avoid getting too much noise, you can figure out the best datarange programatically.
(what i built for the flutter dashboard widget is a bit more simplistic but achieves more or less the same)

however, this means you first get all entries, and then filter them.

another useful approach IMHO (and what i also implemented in the weight view of flutter) is go by whatever is the date range of the currently active nutrition plan.

i think these two techniques are more pragmatic and relevant than predefined ranges that don't have a particular meaning to the user.

**Comment by rolandgeider** [comment]
that's a good idea, I've opened a new issue for the "smarter" charts (but let's keep this one since it's an improvement over the current state)
