### ISSUE TITLE
version 1.7.1 on f-Droid not compatible with server

### ISSUE THREAD

**Issue by taiyoko** [wger-project/wger#1703]
## Steps to Reproduce

1. Install version 1.7.1 (released 6/1/24) from the fdroid store 
2. Attempt to log in to account with wger.de

**Expected results:** account logged in and able to use the app

**Actual results:** message saying "this version of the app is not compatible with the server" 

![Screenshot_20240620-190316](https://github.com/wger-project/wger/assets/2172235/1efb7a4f-bbcf-4ca4-b347-4a43a26ba784)
![Screenshot_20240620-190448](https://github.com/wger-project/wger/assets/2172235/33ee6678-ea1e-43e3-bd42-c51418e660a6)

**Comment by rolandgeider** [comment]
fdroid has been updated in the meantime, closing here
