### ISSUE TITLE
API returns empty data

### ISSUE THREAD

**Issue by suche-cz** [wger-project/wger#1705]
## Steps to Reproduce

Follow https://wger.de/cs/software/api

```
def get_data(access_token):
    result = requests.get(
        'https://wger.de/api/v2/workout/',
        headers={'Authorization': f'Bearer {access_token}'}
    )
    result.json()

```
And get empty data
`{'count': 0, 'next': None, 'previous': None, 'results': []}`

**Comment by JPrata02** [comment]
are you passing the username and password of your wger account?

![image](https://github.com/wger-project/wger/assets/133051531/9260a742-138e-4a5a-8f4b-760537202a75)

**Comment by JPrata02** [comment]
![image](https://github.com/wger-project/wger/assets/133051531/f5529094-ca9e-484a-8a02-73d181a7f7b2)


![image](https://github.com/wger-project/wger/assets/133051531/5ddb8ce9-22a3-447c-a4db-f394b2b5a7db)


![image](https://github.com/wger-project/wger/assets/133051531/b4f59a54-5c03-412b-8fdd-970c49f6dfce)


mine is working fine

**Comment by rolandgeider** [comment]
Also, you would get an error if the auth was wrong

**Comment by suche-cz** [comment]
ok, I am sorry, I should send it as post not get.

**Comment by suche-cz** [comment]
ok, I am sorry, I should send it as post not get.
