### ISSUE TITLE
Use angularJS for timer page

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#171]
The timer page is the perfect example of a SPA, instead of the current JS mess, this should be rewritten with angularJS. There is a current work in progress in the angular_timer branch.

Implementing this issue would also pave the road to fixing #64

**Comment by rolandgeider** [comment]
NB: the timer is only available in the mobile version as it doesn't make much sense to use this other than in smartphones. To force this mode, just append ``?flavour=mobile`` to any URL (``?flavour=full`` to go back) and remember to make the window small!

**Comment by rolandgeider** [comment]
Hey @rlaszlo! Did you get a chance to take a look at this?

**Comment by murphyalexandre** [comment]
I might look at this and the other angular issue. Is it because you are not quite familiar with angular ?

I am and I would be happy to setup some base for you. However, we would greatly benefit from the PR #226 if we would to use angular.

**Comment by rolandgeider** [comment]
Yes, that's the reason. I always start, leave this for whatever reasons some months and then I have to start learning angular from the beginning. **However**, I have a new year resolution, energy and 2 weeks of vacations so if you start working on it, I'd try to get up to speed with angular and see that it doesn't get wasted again :)
