### ISSUE TITLE
expose remote_id, source field on /ingredientinfo/ api

### ISSUE THREAD

**Issue by Dieterbe** [wger-project/wger#1713]
goal: display OFF url's and USDA urls for an ingredient in the UI

**Comment by Dieterbe** [comment]
actually, why do we even need 2 api's, ingredientinfo and ingredient ? they are very similar, can we just simplify and have just 1 endpoint?

**Comment by rolandgeider** [comment]
I had already commited this, didn't even open a ticket: https://github.com/wger-project/wger/commit/bb99d6ec5f5f68a0af346e7e939adf081d7f8351

The *info endpoints are all read-only, while the others that map directly to db objects are writable
