### ISSUE TITLE
Log with more than 999 entries fails to load

### ISSUE THREAD

**Issue by Swell61** [wger-project/wger#1728]
## Steps to Reproduce
Have a workout with enough log entries to make the data request be split into chunks (more than 999 log entries) and attempt to view the log.

## Results
**Expected results:** 
Log shows all results, or at least shows as many as possible before giving a useful error.
**Actual results:** 
Infinite loading wheel, no log entries and no error.

## Details
It looks like when the number of logs reaches more than 999, it requests more log entries in subsequent requests. These requests are sent over HTTP, rather than HTTPS, which seem to be blocked by Firefox, but wouldn't be passed through my reverse proxy anyway, causing the loading wheel to show indefinitely. I've tested in Chromium too, same result.

### Error case
In the case it can't load all of the logs, it should request the newest log entries first (since those are likely to be the most relevant) and then display as many entries as it can until it hits a problem, and then show a useful error message.

### Normal case
These requests should be sent over the protocol currently being used (HTTPS, not HTTP).

## Logs
Since the requests aren't hitting the server, I have no server logs. But I do have network request logs from Firefox when attempting to load the pages.

**Firefox with default settings**:
![wger issue](https://github.com/user-attachments/assets/a1af5a69-1613-4a3d-b240-3b8cd84d4275)

**Firefox when I disable site protection**:
![wger problem disable protection in firefox](https://github.com/user-attachments/assets/58351d64-2b3b-4e47-9ae9-bfecb6c0f022)

**Comment by rolandgeider** [comment]
where does the http come from? Can you open api/v2/workoutlog/ and check that the `next` key correctly uses https?

**Comment by Swell61** [comment]
It is using HTTP
![Capture](https://github.com/user-attachments/assets/a933d843-a551-4454-b62c-ce37612000e7)

**Comment by rolandgeider** [comment]
this comes from django, _I think_ it's the `SITE_URL` setting, try pointing it to the https address

**Comment by Swell61** [comment]
The entry for `SITE_URL` in `config/prod.env` is `http://localhost` but the one in `config/wger-local.env` is `https://<myDomain>`. I've grepped for all uses of `http` in the docker folder and the only hit is `proxy_pass http://wger;` in `config/nginx.conf`. If I run `echo $SITE_URL` in the container it prints `https://<myDomain>`.

Anything else I can try?

**Comment by rolandgeider** [comment]
I had to take a look at the config for wger.de (which uses the docker setup), the only thing that is different is 

X_FORWARDED_PROTO_HEADER_SET=True
SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO

Could you add those two and see if it works?

**Comment by Swell61** [comment]
:open_mouth: adding `X_FORWARDED_PROTO_HEADER_SET=True` worked! It was commented out. Thank you :smile: 

How come that only impacts this part of the website and not the whole thing?

**Comment by rolandgeider** [comment]
🙌🏻🙌🏻

Yeah it's not consistent. Some use the specific site url from the settings and other parts read the host from the request (and here you have to tell it that it is indeed behind a reverse proxy and does use https, even if Django itself doesn't see any of that). In any case, I'll update the readme.

Closing here
