### ISSUE TITLE
Unable to edit exercise

### ISSUE THREAD

**Issue by seyfeb** [wger-project/wger#1742]
For some exercises that I created I am not able to edit them anymore.

## Steps to Reproduce

1. Go to an exercise page
2. Select Edit

**Expected results:** 

The exercise editor form with previously input values.

**Actual results:** 

A blank page only with the surrounding layout (page navigation etc.).

Four errors are logged in the browser:

<details>
  <summary>Browser console errors</summary>

  ```
  TypeError: n.data.find(...) is undefined
      getOptionLabel https://wger.mydomain.com/static/CACHE/js/output.1cfcbf2246c6.js:1
      // ...
  
  
  TypeError: e is undefined
  // ...
  
  TypeError: e is undefined
  // ...
  
  TypeError: n.data.find(...) is undefined
      getOptionLabel https://wger.mydomain.com/static/CACHE/js/output.1cfcbf2246c6.js:1
      // ...
  
  ```

</details>

The container does not log very much

<details>
  <summary>Container logs</summary>

  ```
  wger_nginx          | 172.18.0.6 - - [26/Jul/2024:12:52:55 +0000] "GET /api/v2/check-permission/?permission=exercises.delete_exercisevideo HTTP/1.1" 200 15 "https://wger.mydomain.com/en/exercise/1220/view-base/lateral-raise-machine" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0" "91.3.121.228"
  wger_nginx          | 172.18.0.6 - - [26/Jul/2024:12:52:55 +0000] "GET /api/v2/check-permission/?permission=exercises.delete_exerciseimage HTTP/1.1" 200 15 "https://wger.mydomain.com/en/exercise/1220/view-base/lateral-raise-machine" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0" "91.3.121.228"
  ```

</details>

This may be related to exercises that are not saved correctly during creation, see #1738 

wger version 2.3.0a2

**Comment by kris-gs** [comment]
Hi, I have this problem too - did you find a fix?

**Comment by rolandgeider** [comment]
yes, there was a very dumb bug here, this is fixed and the docker images should be built soon
