### ISSUE TITLE
Unable to Register

### ISSUE THREAD

**Issue by RunForItMarty** [wger-project/wger#1773]
Newb Alert! Not a developer..

"An Error Occurred - Invalid Token Header. No Credentials Provided"

Not sure if it's symbols (-) in my email address?

Why does there need to be a login anyway?

Thanks!

**Comment by rolandgeider** [comment]
hi! sorry for not ansering earlier. This was an issue that I was never really able to reproduce on android, but recently got to the root after talking to someone that was (trying to) use the ios app. This is now solved
