### ISSUE TITLE
Invalid token error when registering account

### ISSUE THREAD

**Issue by Afnyc252** [wger-project/wger#1792]
## Steps to Reproduce

1. ... I clicked register new account
2. ... I filled in all fields
3. ... clicked 'submit' or whatever it is
4. Error screen 

**Expected results:**  next step in verification process

**Actual results:**  error
Token not found. See attachment![Image](https://github.com/user-attachments/assets/040047bb-94dc-4aca-970a-9fc11edb47b9)

<details>
  <summary>Logs</summary>

```bash
```

</details>

**Comment by kmoy1** [comment]
Could be transient? Registering works in the English version at least.

![Image](https://github.com/user-attachments/assets/4c84b09d-2893-4158-8655-bd18f7272d29)

**Comment by kmoy1** [comment]
Can confirm this also happens in the English version

**Comment by rolandgeider** [comment]
hi! This was an issue that I was never really able to reproduce on android, but recently got to the root of after talking to someone that was (trying to) use the ios app. This is now finally solved
