### ISSUE TITLE
Install wger to a non root URL

### ISSUE THREAD

**Issue by svengineer** [wger-project/wger#180]
I tried to install wager on my server to a non root URL like www.example.org/fitness. I think that my apache config works fine. I can reach my other sites (php) without any problems. Going to /fitness I will be redirected to /de/fitness. There is nothing so I get a "Not Found". After that I tried to go to /fitness/de. That works. Now I can click through the menus. But when I want to change the language, something strange happens again: /fitness/de -> click English -> /entness/de :D

I can create a new Workout but when I try to add a Exercise, I cannot find any items of the equipment. It's the same for meals. There are no Ingredients.

**Comment by rolandgeider** [comment]
Yes, django's URL rewriting for the language will get confused if the application doesn't run under the root URL. Also, the REST API calls would stop working.

I'm moving this to the 1.7 milestone, as it should not be too difficult to add a configuration option, but would need time to make sure that everything still works.

**Comment by rolandgeider** [comment]
It seems django has a setting for this, [FORCE_SCRIPT_NAME](https://docs.djangoproject.com/en/1.8/ref/settings/#force-script-name). The REST API calls from javascript probably still need manual work

**Comment by rolandgeider** [comment]
It seems the consensus in the django world is that this is a bad idea, if you host your applications on different paths, they are able to access each other's cookies, since those are tied only to hostnames.
