### ISSUE TITLE
Setting preferred weight unit to "Imperial (pound)" still defaults to kg for exercise units when creating workouts

### ISSUE THREAD

**Issue by slipperybeluga** [wger-project/wger#1803]
## Steps to Reproduce

1. Set preferred weight unit to Imperial (pound) in My preferences
2. Go to Workouts, select one. Click the "+" button to add an exercise to a workout day
3. Select a lift (eg Bench Press). Set reps, etc. Now have to manually update unit from kg to lb for each rep. 

**Expected results:** Default unit would be lb

**Actual results:** Default unit is kg

**Comment by kmoy1** [comment]
looking into this

**Comment by rolandgeider** [comment]
This is done in via the linked PR as well as in the coming refactoring
