### ISSUE TITLE
POST /workout and PUT/PATCH /workout/id is not working - it is giving 200 OK but not getting updated results

### ISSUE THREAD

**Issue by vanshaj-pahwa** [wger-project/wger#1813]
## Steps to Reproduce

1. Make a `POST` request to `/workout` with the following payload:
   ```json
   {
     "name": "Morning Yoga",
     "description": "morning yoga"
   }


**Expected results:** The POST /workout endpoint should save the data correctly and return an updated response reflecting the newly created or updated workout.

**Actual results:** The endpoint returns 200 OK but the data does not appear to be updated or saved.

Screenshot for the PATCH call - ![Image](https://github.com/user-attachments/assets/7066ca30-a51e-4bf1-b251-7dd3cc48bac6)

**Comment by rolandgeider** [comment]
hey! That looks alright, the only thing I can see is that the `/` at the end is missing. In any case the server responds with the new or updated object so if that is correct, the data was definitely saved to the database

**Comment by vanshaj-pahwa** [comment]
Hey! Thanks for the input. I checked, and even with the / at the end, the GET API is still not returning the updated response. It seems like the data is saved correctly in the database, but the API isn't reflecting the latest changes.

**Comment by rolandgeider** [comment]
that's weird, there is no caching here or so. Do you see the correct data when you open the URL in the browser?
