### ISSUE TITLE
Frontend error when adding a weight entry

### ISSUE THREAD

**Issue by mateus2k2** [wger-project/wger#1816]
## Steps to Reproduce

Run wger/server:latest image 
click the add button to add a weight entry 

**Expected results:** The screen to add a weight entry

**Actual results:** A console error and the column for weight is missing 

<details>

There is no error in the backend container logs, so I think this is just a frontend problem 

Before
![Image](https://github.com/user-attachments/assets/3cf65c9e-82c9-4d77-8671-6e3962175b74)

After
![Image](https://github.com/user-attachments/assets/b0a2b2ea-4cfc-4478-856f-d15ffba1723b)

</details>

**Comment by rolandgeider** [comment]
you are right, there's something broken here

**Comment by rolandgeider** [comment]
latest images should have the fix
