### ISSUE TITLE
<h1> element with "addasd" text on main Gym Page

### ISSUE THREAD

**Issue by navyjosh** [wger-project/wger#1844]
## Steps to Reproduce

1. Make sure you are using latest version because this issue came from recent commits
2. Create  new Gym (or go to default Gym)
3. See random `<h1>` element with static text: "addasd"

**Expected results:** 
Some meaningful text there like "Member List" or something

**Actual results:** 
Meaningless ugly text

![Image](https://github.com/user-attachments/assets/32b37f83-4d8c-4c96-a443-d7746bdd2aca)

**Comment by navyjosh** [comment]
PR#1843 Created to fix this

**Comment by rolandgeider** [comment]
yeah, this isn't supposed to be there 😄
