### ISSUE TITLE
Remember category in add set form

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#200]
When adding exercises to a workout day _in the mobile version_ (to force it, add `?flavour=mobile` to any URL or use a user agent switcher), the user has to first select a category, then an exercise from that category. Since one usually adds more than one exercise per category for each day, it would be useful if the system could remember the previously selected category.

Check status of #199 before starting on this issue.

**Comment by purplebird** [comment]
I get an ERROR 500 when trying to add an exercise.

**Comment by rolandgeider** [comment]
Can you post the traceback? There was a problem with django 1.8.6 but that should be fixed by now

**Comment by XOyarz** [comment]
Hi, I'd like to give this one a try, is it still available? It would be my first contribution, so any help/guidance you can give me to get this done would be much appreciated.
