### ISSUE TITLE
Cache nutritional values for plan

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#246]
Found during #241, dummy generator for nutrition plans: if a user has many plans (approx. more than 25), the overview renders slowly and too many DB-queries are fired just to calculate the total calories. Some caching of the values is probably the easiest solution, similar to the `canonical_representation` for workouts.

Steps:
- cache the `nutritional_info` dictionary in `NutritionPlan`s
- add signals that delete the cache key everytime a `NutritionPlan`, `Meal` and `MealItem` is added, edited or deleted.

**Comment by andela-brotich** [comment]
@rolandgeider is this issue still a priority? I would love to take a stab at it based on some of the work done by the folks at @andela

**Comment by rolandgeider** [comment]
Hi @andela-brotich! yes, while this is not priority 1A, I still want to solve this issue

**Comment by andela-brotich** [comment]
@rolandgeider cool. Will start on this on the weekend and update ASAP

**Comment by rolandgeider** [comment]
👍 Great!

**Comment by rolandgeider** [comment]
Cherry picket from https://github.com/andela/wg-millennium-falcon/pull/29
