### ISSUE TITLE
Allow creation of users via REST API

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#251]
It should be possible to create new users via the API. External apps might need to register accounts on behalf of their users without having to send them over to the wger instance. I am not completely sure about the security implications of this so I would suggest a workflow like this:
- Apps register as a regular user to get an API key
- By default, users aren't allowed to create new accounts over the API, this has to be explicitly allowed
- Users created with this key are marked somehow so it is later possible to identify them, I am thinking about adding a new OneToOne table to the user table "metadata" or such

**Comment by rolandgeider** [comment]
Simple idea for a basic protection against being spammed to death with new users:

* REST API consumers that want to create users need a special right that has to be given on demand.
* Users generated like have a special flag so that it's possible to see who created them

**Comment by rolandgeider** [comment]
Note that it's probably easier and faster to add a new command for this (instead of a new element in the GUI). Something like ``add-user-rest-api`` and ``list-user-rest-api`` would be enough

**Comment by KrMantavya** [comment]
Hi, I want to work on this. It is my first time. what do i do after i am done forking and cloning?
