### ISSUE TITLE
Move away from proprietary software Transifex

### ISSUE THREAD

**Issue by ywecur** [wger-project/wger#266]
Since wger is fully open source software, I believe depending on closed source software is, to a certain extent, unethical and should be avoided if possible.

I've looked at [several FOSS alternatives](http://alternativeto.net/software/transifex/?license=opensource) and of these, [Pootle](http://pootle.translatehouse.org/index.html) seems like the best one.

If you agree with me, I'd be glad to help with the transition.

**Comment by rolandgeider** [comment]
You are right that it doesn't feel completely right. When I chose transifex I saw that it had the [source in github](https://github.com/transifex/transifex) with GPL2 as the license, but I didn't catch that the open version was no longer being developed or maintained.

I am open to trying pootle or other alternatives, but my main concern is to make the switch for the translators that have already an account in transifex as painless as possible. I plan to make a release till the end of February, but we can see that we find a solution for 1.8.

**Comment by Bopchy** [comment]
Hey @rolandgeider 

You had contacted me before regarding some inappropriate changes I'd made and the intention that we have for wger, I hope the answer provided was sufficient. I'm actually handling a ticket on this specific issue, and I thought I should ask for your input. I've noted that Pootle does not have support for Python 3, so I wondered if there's another non-proprietary translation API that you had in mind

**Comment by rolandgeider** [comment]
Hi @Bopchy !

First of all, those were not inappropriate changes :) Excuse me for not answering there, I was (and still am) quite busy at the moment. As for pootle, you are right, it doesn't seem to support python 3. I have looked a bit around and it seems that the latest beta of Translate Toolkit (which seems to be a core component of pootle) does have python 3 support, but I can't say how much work is left. I haven't really researched other alternatives, pootle always seemed to be the most feature complete.

**Comment by Bopchy** [comment]
Ooh, thank you. I think I'll give the latest Translate Toolkit version a try

**Comment by 12people** [comment]
I'd also suggest taking a look at [Weblate](https://weblate.org/en/), which I find the most friendly out of the different FOSS offerings. It offers [free hosting for open-source projects](https://weblate.org/en/hosting/#libre).

**Comment by rolandgeider** [comment]
Weblate looks nice and it supports ARB files which we'll use for the flutter app. Do you know of a project that uses it for translation? I'd like to check the UI

**Comment by 12people** [comment]
Pick any project here: hosted.weblate.org/

**Comment by rolandgeider** [comment]
I've been playing around with weblate a bit and I quite like it. As soon as the mobile app is released, I'll see that I migrate the main django translations

**Comment by rolandgeider** [comment]
I've decided to move this ahead so that we don't have two systems in parallel. All the strings can now be translated with weblate 🙌🏻

https://hosted.weblate.org/engage/wger/
