### ISSUE TITLE
DivisionByZero error on Dashboard

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#269]
Just got this by mail:

```python
Internal Server Error: /en/dashboard
Traceback (most recent call last):
  File "/home/rge/www/venv-wger-production/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rge/www/venv-wger-production/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/rge/www/wger-patched/wger/core/views/misc.py", line 131, in dashboard
    template_data['nutritional_info'] = plan.get_nutritional_values()
  File "/home/rge/www/wger-patched/wger/nutrition/models.py", line 147, in get_nutritional_values
    result['per_kg'][key] = result['total'][key] / weight_entry.weight
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

**Comment by Trey50Daniel** [comment]
So I'm assuming the action in models.py on line 147 is where the division by zero happens, which is this code:  

result['per_kg'][key] = result['total'][key] / weight_entry.weight

**Comment by Trey50Daniel** [comment]
And would you happen to know what action caused this problem?

**Comment by rolandgeider** [comment]
Yes it's that place in models.py, this was triggered when the user opened the dashboard. I can try to get some more info from the database later today (I'm currently in the train), but I'm not sure I'll find anything

**Comment by Trey50Daniel** [comment]
Okay, thank you

**Comment by rolandgeider** [comment]
OK, I have taken a look and I think I've found the problem. There was a weight entry with the value of 0, that's why in models.py we run into the exception even after checking with

```python
if weight_entry:
    for key in.....
```
that an entry exists. I'm still not sure how this value could be saved to the database since there's a MinValueValidator in the models.py of the weight app.

**Comment by rolandgeider** [comment]
Ah, I found it! It is possible to do this by using the CSV import. If you enter something like ``26.01.2016,0`` it will happily save the 0 weight to the database, it seems the validators are bypassed in this case. If we add a small check to ``parse_weight_csv`` in ``weight/helpers.py`` it should take care of the problem

**Comment by rolandgeider** [comment]
@Trey50Daniel Did you manage to take a look?
