### ISSUE TITLE
Make translations of exercises and ingredients easier

### ISSUE THREAD

**Issue by maximdushniak** [wger-project/wger#271]
IMHO it would be good to add support for multiple languages for these categories.

**Comment by rolandgeider** [comment]
Hi @maximdushniak!

There is already support for that, but it is probably a bit hidden: every ingredient and exercise has a field indicating the language, which is automatically set as the user's current language when adding them. The current list is then filtered based on this. I think I have an issue so that the user can select which languages to show, but I haven't gotten around to do it yet.

**Comment by maximdushniak** [comment]
I meant that the ingredient has a similar name to the other languages.
For example:
_[EN] Applesauce, canned, sweetened, with salt
[RU] Яблочное пюре, консервы, подслащенные, с солью_

That would not create duplicates of ingredients that are similar in nature, but with the name in another language.

**Comment by rolandgeider** [comment]
Yes, I see what you mean. This is possible when e.g. submitting new ingredients, but the process is not clear (or that it is available at all). At least for the exercises I can imagine establishing a better workflow so that it is clear that they can be translated.

**Comment by rolandgeider** [comment]
Reopening issue

TODO:

At the moment, transifex only translates the application itself. With more languages being added, it is becoming more important to translate the exercises and the ingredients as well (after all, this is one of the explicit goals of the project), which only live in the database.

One possible idea is to write a script that extracts the exercises and writes them to a PO file which could be uploaded to transifex as a different resource. Another script would then read these out and update the database. The same with the ingredients. One thing to consider is that not all exercises have a "good" description, so it we could e.g. only extract exercises that have more than a number of characters or are used the most in workout. For the ingredients, only the name needs to be translated, but the English version has many thousands of entries, so a manual filter needs to be implemented here.

**Comment by rolandgeider** [comment]
This is part of the current milestone, closing
