### ISSUE TITLE
Relation between workout log and session

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#273]
Right now the workout logs and the workout session are only linked through the date (for sessions this value is unique and enforced by the DB). This presents in some places a problem, since it's not possible to just _follow_ a foreign key relationship with the ORM like in other places.

To fix this:
- see if it's possible to define the date as the foreign key in django or
- check if adding a real foreign key from the logs to the session makes sense

**Comment by andela-rwachira** [comment]
Hi @rolandgeider, I'm part of a small team working on a forked version of Wger as a learning exercise to learn about python, django etc. I have been assigned the task of creating the link between the workout logs and workout sessions and would like to request some clarification. 

I apologize in advance if my question seems a little basic, I still have a lot to learn :)

My understanding of database relationships is that you link tables based on the type of queries you'd like to make. If the logs and sessions are already linked by date (and by workout id):

- What are we trying to achieve by creating a foreign key relationship? 

- Is there a new query you would like to be able to make?

- How would this change how a user interacts with their workout days and workout schedules?

Any help would be much appreciated, thank you!
Rehema

**Comment by rolandgeider** [comment]
Hi @andela-rwachira,

don't worry, first, everybody started one day and second, those questions are not basic :) Also, I'm really happy you chose my project to learn python.

Basically this issue is a "clean up"-issue and would not result in any new user interaction/workflow, at least not in the beginning. Currently, if you have a session and want to find all logs for it, you need so search for all logs that belong to that workout and happened on that day. If it were a foreign key, you could just _follow_ the relation with the ORM, having a cleaner data model design. Basically the difference between this
```
logs = Log.objects.filter(workout=session.workout, date=session.date)
```

and this
```
logs = session.logs.all()
```

(The same applies to the backward relation, if you have a log and want to get the session)

Also, there are performance improvements if you don't need to perform any searches, indexes on IDs are very fast.

If you have any other questions, feel free to ask!
