### ISSUE TITLE
Recaptcha is in German

### ISSUE THREAD

**Issue by rutsky** [wger-project/wger#281]
While https://wger.de/ interface is in English (by default?), recaptcha is being displayed in German language, which makes it far harder to solve for non-German speakers.
![screenshot_2016-04-08_001](https://cloud.githubusercontent.com/assets/46573/14397103/953dfbb4-fdec-11e5-8731-9613f425e9f1.png)

**Comment by rutsky** [comment]
Hm... Looks like it's not always in German, reloading page shows me captcha in other languages too:

![screenshot_2016-04-08_005](https://cloud.githubusercontent.com/assets/46573/14397211/1b816616-fded-11e5-8702-20a594425be1.png)
![screenshot_2016-04-08_004](https://cloud.githubusercontent.com/assets/46573/14397212/1fb031ae-fded-11e5-8ddf-34d199de0c12.png)

I'm using Firefox with local ISP in Saint Petersburg, Russia. Reverse IP lookup shows that I'm in Russia, so I'm unsure why random language is chosen for me.
Also I'm unsure is this Google's Recaptcha issue or its configuration.

**Comment by rolandgeider** [comment]
Thanks  for the report! This looks strange indeed, I'll take a look

**Comment by rolandgeider** [comment]
I honestly still can't understand why this is happening, I'm guessing that the reverse proxy is screwing things up, but it still seems random that there's a different language for every reload. I have now set this to English (will update wger.de later today), that's at least consistent.
