### ISSUE TITLE
Nutrition diary

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#284]
The user should be able to enter the food he/she actually ate during the day, as opposed to what was planed with the nutritional plan.

**Comment by rolandgeider** [comment]
Possible workflow:

* the user clicks on a "add diary entry" or such
* the system tries to guess what meal this is supposed to be, based on the time. The user can also either select a different one or enter custom ingredients. Perhaps also present past meals eaten at roughly the same time?
* the system shows the current daily calories as well as the difference between the plan and reality, macronutrients as well. Possibly color code this?

I think this would be enough for a first step, there are many possibilities for improvement (e.g. show a graph with the planed/actual calories together with the body weight to see how one influences the other). What do you think @ywecur ?

**Comment by ywecur** [comment]
I can think of several additions to this, but as a start to the IIFYM model it should suffice. For a minimal viable product I'd say to leave out you second point and limit it to:

- Require user to enter caloric and macronutrient presets.
- Add food entry
- System shows daily caloric goal & how much is left
- System shows daily macronutrient goal & how much is left

**Comment by ywecur** [comment]
I could upload a sketch of my UI idea if you'd like.

**Comment by rolandgeider** [comment]
Sure, sketches are always useful

**Comment by rolandgeider** [comment]
I have started working on this on the ``nutrition-diary`` branch. To keep things simple, I have started with a very simple data model: there are log entries that are associated with a plan, they have ingredients, a datetime and an optional comment. Then we can just sum up the calories for the day and compare it.

**Comment by rolandgeider** [comment]
Status here: the only thing missing for a first version is the input form. I want to use angular for this to make something faster and user friendlier than the rest of the site as well as use it as a guinea pig to see if all these technologies the cool kids are talking about are really so awesome ;)

**Comment by ywecur** [comment]
How is it coming along?

**Comment by rolandgeider** [comment]
Didn't have time to work on this the last weeks, hope that will change soon!

**Comment by muramasatheninja** [comment]
Any chance progress has been made on this?

**Comment by rolandgeider** [comment]
A simple version of this is implemented and merged in master. Improvements are always possible and will surely come in the future
