### ISSUE TITLE
Export workouts

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#285]
From user feedback: it would be useful to be able to export workouts (probably as a JSON file).

Things to discuss: is this meant to be used to transfer workouts between instances? Then we'd need an import and be clever if exercises are not available on one instance. If it is only for information then this is not an issue.

**Comment by abeworld** [comment]
Hi,
the import/export feature would be used to allow you to send your workouts to other users so they can add them in their workout schedules.
XML/JSON is indeed a great idea.

**Comment by nsomaru** [comment]
Hi,

I've been browsing through the issues and I'm wondering if this issue can be closed because it seems like you could get this JSON from the API?

**Comment by abeworld** [comment]
Hi,

You can indeed close it!
Thanks

**Comment by rolandgeider** [comment]
We're also almost done with a feature that will allow you to mark a workout as a template so that other users can copy and use them.

The REST API could be used to copy workouts between wger instances, but that's a really fringe use case

**Comment by myhrmans** [comment]
> The REST API could be used to copy workouts between wger instances, but that's a really fringe use case

I have a reason for this, but cant find how to actually achive this using the REST api. Not possible anymore?
