### ISSUE TITLE
Update muscle list

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#286]
The list of available muscles as well as the exercises could be updated

New muscles:
- lateral deltoid - 17
- Obliquus externus abdominis - 18
- Posterious Deltoid - 19
- Forearms - 20 (what is the latin name for the main muscle here?)

**Comment by rolandgeider** [comment]
New list available in branch ``update-muscles``

**Comment by Landrash** [comment]
@rolandgeider The forearms is a giant mix of muscles.
The 2 bigger ones *I think* are [Flexor pollicis longus](https://en.wikipedia.org/wiki/Flexor_pollicis_longus_muscle) & [Flexor digitorum profundus](https://en.wikipedia.org/wiki/Flexor_digitorum_profundus_muscle).
I don't think I've seen them referenced in other terms than Forearms in exercise terms on the other hand.

**Comment by rolandgeider** [comment]
Yeah, I noticed there were a lot of them. From one side I'd also prefer to just use "forearms" here, from the other it would be the only non-latin name. I'm still undecided, but also don't want to make the list less useful just to be consistent.

**Comment by leksinteractive** [comment]
Just wondering if you guys will find our open sourced exercises useful: http://gympro.github.io/prime-exercises/ - keep up the good work 👍

**Comment by rolandgeider** [comment]
@leksinteractive Nice! I've opened issue #287 for this

**Comment by rolandgeider** [comment]
@Landrash this took me a bit longer than I had anticipated, but I have added the SVGs for the missing muscles. The Obliquus externus abdominis has the ID 14, not 18 as I wrote before. We can now go through the google docs file and update the exercises

**Comment by BNolet** [comment]
Not everyone and I would go as far to say that most people don't know the scientific names of muscles. Most people use the colloquial terms (abs vs Rectus Abdominis) so I think we might want to add at least alongside the scientific names the colloquial names. 

Secondly there are _definitely_ muscles that are missing, namely hip and groin muscles (adductors abductors) among others. 

Lastly, this is much less important but, perhaps group muscles by part of the body? Legs, Torso, Back, Arms, Etc

Kinda new to working on open-source projects so umm, should I do it and submit a PR myself or is there someone specifically working on the exercise section?

Also, should I open another issue for the things I mentioned or will it suffice to keep it in here?

**Comment by rolandgeider** [comment]
Sorry for now answering earlier @BNolet, this one got buried a bit!

The idea of adding a new marker to the muscles to group them is interesting, but isn't the current diagram enough? I am also tending more and more to use common names. Perhaps the best solution is just to add a new field to the muscles with the common names, but leave the scientific one, just for completness.

It would be great if you could submit a PR with the exercise changes!

**Comment by joaonunatings** [comment]
@rolandgeider is this solved? I wanted to add the missing muscles (hip and groin). I can open a PR and work on this.
