### ISSUE TITLE
Add more images to the exercises

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#287]
Many of the exercises don't have images yet. A very nice collection (CC-0) suggested by @leksinteractive is the one used by gympro: 
http://gympro.github.io/prime-exercises/
https://github.com/gympro/prime-exercises

**Comment by leksinteractive** [comment]
Awesome! Some info, the Prime collection is based on those exercises that are the most commonly used by our members. Feel free to suggest exercises that you think would be beneficial to have illustrations over others, just so there's some sense of priority, and we will happily take those suggestions on-board as we develop the set further.

**Comment by rolandgeider** [comment]
That sounds great! At the moment I don't have a list of the most used exercises, but it's something I'd be curious to know. When I cook something together I'll let you know

**Comment by EmilAlipiev** [comment]
Guten Tag Roland,

quick question where did you get current existing images from? Is it from some open source wiki? I saw this website http://www.gymwolf.com/exercises/Chest has exactly same images but more of wger has.

**Comment by rolandgeider** [comment]
Hallo @EmilAlipiev! sorry for the late reply, I've had practically no time the last week.

Originally I used the images from [opentraining](https://github.com/chaosbastler/opentraining), which are just the ones from [everkinetic](http://db.everkinetic.com/) but is sorted a bit differently

**Comment by rolandgeider** [comment]
The Gympro repos are not available anymore

**Comment by rolandgeider** [comment]
Pinning this issue, as many exercises need pictures. The problem is not only finding images, but finding images that have a free license (creative commons, etc.).
