### ISSUE TITLE
Add a gif view on exercises

### ISSUE THREAD

**Issue by jcostamagna** [wger-project/wger#289]
I know that there are issues about excersices with out images, but i think it would be great to see, on the rigth side or like is now, a gif animated showing how to do the excersice. With the same images that are now, but showing de movement. I could try with that if you think is a good idea.

**Comment by rolandgeider** [comment]
Hi there!

You mean on the workout view? I can imagine that adding some kind of slideshow effect when the mouse is on the image would be useful here (I wouldn't want that to start automatically, that would be too much movement). If you want to implement this, go ahead! As I wrote in one of the other issues, I want to add more angularJS to the application, among other places, the workout page, so if you are comfortable with it, feel free to use it (even if it would be too big for just this task, there will be other things coming)
