### ISSUE TITLE
Indicate that search term was not found

### ISSUE THREAD

**Issue by DeveloperMal** [wger-project/wger#293]
Right now when you search for workout or an ingredient that is not found in the workouts or ingredients  pages there is no indication that it wasn't found. There is no label saying "search result not found" or the search bar doesn't turn red. It is hard to tell if the search was successful in sending or if nothing was found.

**Comment by rolandgeider** [comment]
Yes, some kind of indication would be helpful. I had planned on replacing the autocompleter anyway, this could be fixed then (but doesn't need to wait till then).

**Comment by rolandgeider** [comment]
Just fixed
