### ISSUE TITLE
Port to Ubuntu Touch

### ISSUE THREAD

**Issue by ktatar156** [wger-project/wger#294]
Hello,
could you consider porting your great app to Ubuntu Touch?

**Comment by rolandgeider** [comment]
Hi there! Glad you like the app. There is a way to package webapps for ubuntu touch, from what I did see it was easy to do, but I haven't looked in much detail into it. Do you have experience with this? If so, we could work on it together

**Comment by ktatar156** [comment]
Sorry, but I don't have :( I'm only Ubuntu Community member that helps
translating strings and reporting bugs ;) But You can ask at Ubuntu Phone
mailing list and (90% chance) you'll get necessary help/person to
cooperation.

2016-06-11 11:59 GMT+02:00 Roland Geider <notifications@github.com>:

**Comment by rolandgeider** [comment]
No worries, as I said, the process didn't look too difficult. I'll see what I can do when I finish the issues I'm currently working on.

**Comment by ktatar156** [comment]
That's great news! I will translate into Polish here
https://www.transifex.com/rge/wger-workout-manager/language/pl/
does that also translate website into PL?
Is it possible to get it working offline in smartphones? I'd love to see it in UT without using network.

**Comment by rolandgeider** [comment]
that's great! And yeah, that translates the website as well. If you have any questions about the strings just ask. Also, I can install your translations to the preview server, then you can see them in context

**Comment by rolandgeider** [comment]
Forgot to answer alt the offline mode. While it would be possible to implement the app in such a way, it would require almost a full rewrite, at the moment this is a 100% online app (since it's really a web application)

**Comment by ktatar156** [comment]
Personally, I'd prefer offline apps, but that's ok for me. :)
What will change, if You port that app in Ubuntu Touch (versus mobile website version)?
My translated strings landing in 'unreviewed', is that ok?

**Comment by rolandgeider** [comment]
Basically it will be the same as the mobile version. The application offers a REST API so it would be possible to make a full native app for the platform. But sadly I don't have the time for this

An for the "unreviewed"status, that's OK. The ststus can be used if e.g. a second translator needs to reviews the strings, then only reviewed translations could be used, but that's nothing we need :)

**Comment by ktatar156** [comment]
Quick update:
there is one thing that can be done with your app in UT - convergence mode (GUI changes with screen change (phone, tablet, TV, etc.), please look at screen https://assets.ubuntu.com/v1/6b76b7c9-tablet-developers-form-factors.jpg?w=984 ).

**Comment by rolandgeider** [comment]
Yeah, at the moment there are two main modes, "desktop" and "mobile". While there are changes that happen dynamically based on screen size, there is much more that could happen. This is something I definitely have on my radar (not sure if there's an issue for this)

**Comment by HansjoergN** [comment]
i did it:
https://open-store.io/app/wger.hansjoerg
hope you like it. its my first webapp!

**Comment by rolandgeider** [comment]
Not relevant anymore
