### ISSUE TITLE
Authors should not be a single field

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#299]
At the moment, the author field for exercises, etc. is a single text field. It would be better if each new author would get an entry to a new authors table or such. Another advantage would be that other information such as the datetime could be saved as well.

**Comment by jonte450** [comment]
Where can i find this issue someone that can apply a image?

**Comment by rolandgeider** [comment]
When a user submits an exercise, the name/username is saved to the authors field. We want to make it easier in the future to correct / expand exercises so it would be useful to see who edited it

**Comment by ImTheTom** [comment]
I'll try to action this next.

**Comment by rolandgeider** [comment]
Awesome! this would be **really** useful and something we will need for the exercise croudsourcing.

One thing to consider, since we need to distribute the authors in the fixtures we will need to keep the authors field. We can have the authors table and have a management command that updates it

**Comment by ImTheTom** [comment]
Noted :+1:

**Comment by rolandgeider** [comment]
BTW, since we removed the view to add or edit exercises you will need to find other ways to test this, e.g. via the API, I can check later if I have some scratches for PyCharm. Also currently the ingredient model also has an author field, you can leave this as it is, we will probably change this so that people contribute ingredients and products directly to Open Food Facts

**Comment by ImTheTom** [comment]
Hey Roland.

I've been having trouble updating via the API. Have you got an example of updating an exercise via API. Just like a curl example.

**Comment by ImTheTom** [comment]
Yeah works great. I was trying to do an update using a read only endpoint. Thanks for the help. 👍

**Comment by ImTheTom** [comment]
Hey it looks like that branch already has a lot of stuff around tracking changes to exercises.

To finish this task off I'm planning on making sure the authors of the changes are in the JSON response to exercise calls and that they are shown on the exercise overview pages.

And also create a management command to update the author of the exercise in the direct exercisebase table.

**Comment by ImTheTom** [comment]
Yeah haven't tried making a new table, only really starting to have a propert look at it tonight. Was planning on trying to extract it from the history one.
