### ISSUE TITLE
Charts error: Uncaught TypeError: Cannot read property 'format' of undefined

### ISSUE THREAD

**Issue by w00p** [wger-project/wger#301]
Hi,

In the latest master version i cant get charts working. I get this message in the console:
`metricsgraphics.min.js:3 Uncaught TypeError: Cannot read property 'format' of undefined`

You can see it here: [http://gym.kaffetur.no](url)

Ubuntu 16.04
Python 2.7
Apache2

**Comment by rolandgeider** [comment]
I actually couldn't get that same error, only a warning for ```#weight_diagram``` saying that no data was supplied. I have added some checks so that the charts are only drawn if there is data available, can you check if this fixes your problem?

**Comment by w00p** [comment]
Same error. Not working. Now i have 2 errors
`metricsgraphics.min.js:3 Uncaught TypeError: Cannot read property 'format' of undefined
weight.js:68 Uncaught TypeError: Cannot read property 'length' of undefined`

**Comment by rolandgeider** [comment]
mhh, interesting. Do you have stuff logged or is it a new user?

**Comment by w00p** [comment]
Both, i have logged my weigh and i also tested with different users.

**Comment by w00p** [comment]
Just some additional information. I have installed wger on 2 different brand new ubuntu servers now. But its this error in the first post everytime. Cant get Charts to work. Is it possible you can help/try installing wger on my server? I dont know what i am doing wrong.

**Comment by w00p** [comment]
I am over my head here, but the console logs `Uncaught TypeError: Cannot read property 'format' of undefined`.
And it reffering to `MG.convert.date` on line 45 in weights.js. 
Can it be some date format problem?

**Comment by w00p** [comment]
I figured it out. Sees like the problem was the d3.js file.
i replaced this: 
`<script src="{% static 'bower_components/d3/d3.js' %}"></script>` 
with this: 
`<script src='https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.0/d3.min.js' charset='utf-8'></script`

Now it works :)

**Comment by rolandgeider** [comment]
I just wanted to write that! When you install a new application, it downloads the latest version of D3, which is currently 4, because my local application was installed some time before, I still had the 3.x version. I will update the requirements file for the library to make sure the compatible version is downloaded and then there's time to make sure it works with the newer version
