### ISSUE TITLE
Add Norwegian language

### ISSUE THREAD

**Issue by w00p** [wger-project/wger#304]
I have translated wger into Norwegian. But i need to review the strings and words on a test server. Can you add it, when you have the time? or tell me how i can add it on my own server.
Thanks.:)

**Comment by rolandgeider** [comment]
Awesome!!

I can add them later today but if you want you can try to do this on your server, there are a couple of hints [on the documentation](https://wger.readthedocs.io/en/latest/i18n.html). You can ignore the steps about updating the fixtures and adding the flag icon, but you'll need to restart the server.

Do you have a twitter account? Then I can mention you there once this goes online :)

**Comment by w00p** [comment]
Cool! I think i got it, but i see a lot of word that is not translated, hmm. But they are translates in transifex. Well check later after work.

**Comment by rolandgeider** [comment]
you might need to manually compile the translation files, go to the wger folder (the one within the source code, so you are on the same level as the 'locale' folder) and do ```django-admin compilemessages```

**Comment by w00p** [comment]
Strange, that did not work. I had to manualy download the .po fil from transifex, replace django.po file. Then i used the command: `django-admin compilemessages`. And now it works fine.

**Comment by rolandgeider** [comment]
oh yeah sorry, I thought that step was obvious :innocent: I haven't commited your translations yet

**Comment by w00p** [comment]
Hehe no problem ;)

**Comment by rolandgeider** [comment]
If you didn't find any problems I'd merge your translations. Do you have a twitter account? Then I can mention you there

**Comment by w00p** [comment]
Its ok. I did a quick review. So it should be ok now :) twitter @kjetilelde

**Comment by rolandgeider** [comment]
it's online
