### ISSUE TITLE
ECONFLICT Unable to find suitable version for d3

### ISSUE THREAD

**Issue by petervanderdoes** [wger-project/wger#311]
Trying to install the development stuff but when running the `invoke bootstrap_wger` as well as Docker installation, the installation fails on `ECONFLICT Unable to find suitable version for d3`

Probably related to the pinning that happened in commit 28fb6a3 to fix issue #301

**Comment by petervanderdoes** [comment]
Digging a little more,  `metrics-graphics` was updated 12 days ago to version 2.10. This version now depends on D3 4.x. See https://github.com/mozilla/metrics-graphics#important-changes-in-v210

**Comment by rolandgeider** [comment]
Thanks for reporting this (you probably were the one that reported it on the IRC, sorry I couldn't answer you there). I'll  do some tests this evening after work and just remove the dependency on D3 v3.

**Comment by petervanderdoes** [comment]
To clarify, I haven't reported this on IRC :) But thanks for the quick response.

**Comment by rolandgeider** [comment]
Then it was someone else, even more reasons to fix this :)

**Comment by rolandgeider** [comment]
Fixed.

This issue was related to #302
