### ISSUE TITLE
Determine style guide for Javascript

### ISSUE THREAD

**Issue by petervanderdoes** [wger-project/wger#317]
Currently the project follows PEP8 style guide for the Python files but no style guide is set for Javascript.

There are several options for the javascript style, this issue should help determine which one will be adopted.

As far as Ecmascript version, I suggest to go with 5 for now. Ecmascript 6 is out but still not fully supported by "older" browsers, IE11, IOS9.

For styling guides we can choose from:

- AirBnB
- Google
- Idiomatic
- Or something completely different

Point is to choose one and stick with it :)

**Comment by rolandgeider** [comment]
I personally don't really really have a preference, for python I chose pep8 because it's kind of the more or less official style guide, so for JS I would like to use something that is similarly known and not do our own thing. Another important thing would be the availability of some kind of automatic testing tool so that we can integrate this with travis.

**Comment by petervanderdoes** [comment]
Ok, so as a test I decided on AirBnB for the style.

I created a branch on my fork to show what is done so far:

- Added `package.json` to control the needed node_modules needed.
- Use `eslint` for linting the javascript.
  - Don't error on anonymous functions
  - Work around for functions which are called from a template. `eslint` thinks these functions are unused and will throw an error. By starting these functions with wger we can tell eslint to not error.
- Use `gulp` to automate the linting. (Only `nutrition.js` is being linted right now)
- Update the `travis.yml`
  - Use Node 4
  - Use caching.
  - Use gulp to lint.
- Only the` nutrition.js` has been changed to adhere to the new styling guide.

You can see the branch here: https://github.com/petervanderdoes/wger/tree/feature/javascript
And on travis here: https://travis-ci.org/petervanderdoes/wger

Let me know what you think.

**Comment by rolandgeider** [comment]
This does indeed look great, I also like the AirBnB style, I think we can keep it :)

**Comment by petervanderdoes** [comment]
Cool, I'll keep working on it.

**Comment by petervanderdoes** [comment]
### Update

- All javascript files have been updated to the new coding style
- Gulp lints all javascript files.
- Travis lints Python first, javascript second, and Python tests last.
- Added a coding style document in the docs directory.

Tests returns some problems which I'll be looking into in the next few days.

**Comment by petervanderdoes** [comment]
All Python tests pass.

**Comment by rolandgeider** [comment]
Thanks. I've opened PR #321, I hope I'll find time to take a closer look today, as I am leaving tomorrow for a week for my vacation (I'll have internet and will be able to answer on issues, but not much more). In any case, I've added you to the developers team, that'll make things easier in the future ;)

**Comment by petervanderdoes** [comment]
Thanks for adding me. I'll not be doing any merging in the near future, at least not without talking to you about it. Enjoy your vacation.

**Comment by rolandgeider** [comment]
Fixed with #321
