### ISSUE TITLE
Picture gallery

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#319]
Implement a new gallery app/module to upload the user's pictures. This would allow for comparisons and the typical "1 year body transformations" (or lack thereof). A simple slideshow could then show this progress (perhaps even generating a downloadable video). All this could then be tied in with #218 so it would be possible to know the user's statistics at any point in time.

As an optional feature, it would be really useful if when uploading the pictures, the system could automatically aligning them so the slideshow/video mentioned above could be actually implemented. I'm not sure how difficult this would be.

**Comment by lediable** [comment]
Yeah, it is cool!

Maybe with the ability to choose the timespan as a year, six months, two months, etc.

Besides the photos you can also add other informations such as:
- Percentage of lean mass and fat mass
- 1RM of some compound exercise ( bench press, back squat, deadlift, barbell row etc. ) 
- Measurements at various points of the body (eg. waist, hips, thighs, biceps, etc.)

**Comment by rolandgeider** [comment]
Definitely!

As for the other information, there's already an issue that more or less addresses this, #218. The idea is that all that data is collected separately (e.g. via the workout logs or a future body measurement module), then they are collected and presented on one place, together with pictures or some other diagrams

**Comment by lediable** [comment]
I want so much to contribuite to this project with some code but I am really busy with work and exam until november :(

**Comment by rolandgeider** [comment]
don't worry, November is just around the corner!

**Comment by rolandgeider** [comment]
Hey there, how is it going? Have time again? :)

**Comment by rolandgeider** [comment]
This feature is already available
