### ISSUE TITLE
Adipositas is not English

### ISSUE THREAD

**Issue by petervanderdoes** [wger-project/wger#326]
The word "Adipositas" is not English, it's German. The English word is "Obesity"

Replacing this word in the source code means a whole lot of work for the translators, so maybe it just needs to be replaced in the English PO file?

**Comment by rolandgeider** [comment]
Mhhh, I could have sworn I looked it up when I was implementing this. While it is work for the translators, and I don't like to change strings for exactly this reason, in this case it is a bug and should be corrected

**Comment by petervanderdoes** [comment]
Maybe it's Latin, the official name you know. I'll do some more research. I searched for "Adipositas" and all that showed was German and some Translate German English sites.

**Comment by rolandgeider** [comment]
Then we just change it, I also don't want to use some technically-correct but very obscure word

**Comment by lediable** [comment]
I can confirm, it's Latin. There is no need to change it.

**Comment by rolandgeider** [comment]
I'll close this issue then, but it it causes confusion we can change it, I can definitely live with another word :)
