### ISSUE TITLE
Show exercise language for admins

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#327]
Administrators should be able to see (and edit?) the hidden language field for exercises and ingredients. This is important e.g. when a user submits a new exercise in French but had used the application in English.

**Comment by lediable** [comment]
For me, I find it useful, mostly the edit.

I think that it can be solve in two ways:

1) can only be added exercises in English, then the admin can translate to his language
2) if a French user adds an exercise in French it will be seen only by those who choose the French language

**Comment by rolandgeider** [comment]
Nr 2 is already the behaviour of the application! :)

The "problem" is that some users change the language of the application (as they should be able to), but then if they add an exercise and write the description in their mother tonge. As an admin, then I see the description, think "ok, an exercise in French", but then in the background the language is set to English and then the French users don't see it. That's why simply displaying it would be already a nice enhacement.

**Comment by lediable** [comment]
Ah, now I see!

Indeed, the display the exercise langauge is a good idea.

**Comment by Sidrah-Madiha** [comment]
@rolandgeider I have a question: to fix this issue, should we add a text like field to show that user used other language  in admin > Exercise Pending Review or should we preselect the language dropdown with the same language that exercise submitter has used. Please see screenshot for clarity: 
![wger1](https://user-images.githubusercontent.com/16177747/111888096-53c2bd00-89fb-11eb-956a-3e001426303d.png)

**Comment by rolandgeider** [comment]
Hi @Sidrah-Madiha ! Adding the language dropdown when admin users edit an exercise would be great. I know it's possible to programmatically modify the form, but have no idea how difficult this would be, so if you see that it's too complicated or makes the code too unclear, adding a simple text field (also visible for admins only) would be enough

**Comment by rolandgeider** [comment]
Actually, showing the info text would be useful independently of the form, you can hide the info by wrapping it in ``{% if perms.exercises.add_exercise %}``

**Comment by TrushaT** [comment]
Pls, assign this issue to me. I would like to work on it.

**Comment by ajh6** [comment]
Hi! Any chance I can try and work on this issue?

**Comment by rolandgeider** [comment]
@ajh6 sure! Just show the current language if the user has edit permissions
