### ISSUE TITLE
Document REST API endpoints for search

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#329]
There is currently no documentation for searching exercises and ingredients, since they are only used internally for the autocompleter but are something API users can also find useful. TODO:
- Document the endpoints
- Add simple filter options (e.g. the language is auto-selected, it should be possible to override this)
- Make the response returned by both the exercise and ingredient endpoints use the same structure

**Comment by fossterer** [comment]
Hello @rolandgeider ! I've started using the 'wger' app myself. I came across the https://wger.de/api/v2/ page that does show how to access 'exercises' and 'ingredients'. What is this issue asking about in particular?

Let me know if the intended documentation should exist at a different location

Thanks

**Comment by szaveri** [comment]
@fossterer 

I believe he is talking about the https://wger.de/api/v2/exercise/search API. Speaking of which I don't believe it has any way of sorting (tried https://wger.de/api/v2/exercise/search?ordering=value).

@rolandgeider To get a return JSON for the search API for exercises try https://wger.de/api/v2/exercise/search/?term=<Search Term>

**Comment by rolandgeider** [comment]
api is documented with openAPI now, closing
