### ISSUE TITLE
Add Webpack for uglification, minification, compilation of assets

### ISSUE THREAD

**Issue by illegalnumbers** [wger-project/wger#335]
I'd like to add in Webpack (https://webpack.github.io/) for uglifying, minifying, compilation of client side assets. Is that ok? It's a better option than going the standard browserify/requirejs/commonjs/grunt+gulp+etc route in my opinion and is the 'Gold Standard' now for assets. I was told to consult @petervanderdoes :)

**Comment by rolandgeider** [comment]
FYI, Peter will be offline the next 2 weeks

**Comment by illegalnumbers** [comment]
@rolandgeider and @petervanderdoes I was going to take a look at how you guys do asset handling tomorrow since I was feeling a bit better. As such I think this would be a good starting place to plug in Angular 2.0 to wger. 

Considering migrating all the templates from Django to Angular is going to be a big change and is essentially going to make the application an Angular client application with a Django REST backend what would you say would be the best place to tackle first in terms of least complexity with highest value to add to the application.

**Comment by rolandgeider** [comment]
Just a quick comment, the plan is not to replace *all* templates, but rather angularify some parts of the application (in this order: gym mode, nutrition diary, workout page, dashboard, etc). It would be Mitch work to move e.g. the licence forms to angular without many benefits, were can better invest our time in new features :)

Am 26. November 2016 02:35:24 MEZ, schrieb Ben Nelson <notifications@github.com>:
>@rolandgeider and @petervanderdoes I was going to take a look at how
>you guys do asset handling tomorrow since I was feeling a bit better.
>As such I think this would be a good starting place to plug in Angular
>2.0 to wger. 
>
>Considering migrating all the templates from Django to Angular is going
>to be a big change and is essentially going to make the application an
>Angular client application with a Django REST backend what would you
>say would be the best place to tackle first in terms of least
>complexity with highest value to add to the application.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/wger-project/wger/issues/335#issuecomment-263037748

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by petervanderdoes** [comment]
The only thing we do now with Gulp is the linting process, of both JS and Python.
If Webpack can run Flake8 and produce output of errors I might be interested. I did a quick Google search and did not find a any info on integrating Flake8 with Webpack.

**Comment by rolandgeider** [comment]
If we go the angular typescript route, we will need some way of compiling the JS files so we will need some external tool to do this as well. We can use webpack if it can integrate everything we need

**Comment by petervanderdoes** [comment]
I'm closing this issue. It's not needed until we start to have to compile Typescript or we have more JS that needs to be minified.
