### ISSUE TITLE
Add docker-compose file?

### ISSUE THREAD

**Issue by illegalnumbers** [wger-project/wger#340]
Might want to add that in. My docker experience for the most part has been limited to using composition files to compose containers, it might be overkill for you if you don't have a whole lot of services but I noted that you had a dockerfile present already so if you have at least one other service or want to run automated tests under a container or a variety of other uses it could be helpful.

**Comment by rolandgeider** [comment]
I had thought about a bit about this, but yeah, would be a bit overkill. The current images are made more with the intention to try the application than to really deploy it.

On the other hand, this is not something that I would be opposed to, having more or less tuned images would be great to have, just something that hasn't happened yet

**Comment by illegalnumbers** [comment]
I guess without delving deeper into the nuts and bolts of the services I couldn't say how much of a benefit it would give. I can look more into it though. Be nice to have an easy deploy system.

**Comment by rolandgeider** [comment]
Just to document things, I have started working on a docker compose file on the appropriately named [docker-compose](https://github.com/wger-project/wger/tree/docker-compose) branch. There are a couple of very ugly things, but it shouldn't be too difficult to finish

**Comment by hughesjs** [comment]
I've had a look at your docker-compose branch and I'll be honest, I've not too sure why it's been set up the way it has been. I've got a bit of experience with docker-compose so if you have the time to explain a little how the app architecture works (I'm really unfamiliar with django and python webapps) I could try and help here.

**Comment by rolandgeider** [comment]
I'm afraid I can't tell you anymore why it was set up like that 😅 In the meantime, the regular dockerfiles have been updated as well, so those changes should be used here as well to begin with. Another thing that I noticed is that the development was setup for development, which is probably a bit overkill, a more or less production-ready config would be more useful.

As for the architecture, we would need a database (preferably postgres), some caching for sessions etc and the webserver. As far as I remember, there was a problem with the database setup, since it needs the application to install the migrations and load the initial data, but I can't tell you more

**Comment by hughesjs** [comment]
Have you got Discord? Maybe we could have a chat on there and see if we can get it working. 

I've been chatting to the guys over at LinuxServer.io and they seem vaguely interested at adding this to their fleet if we can get something running well.

**Comment by rolandgeider** [comment]
Sorry I don't. We can use gitter, since there's already a channel there. Basically the idea is to do something [like this](https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/)

**Comment by rolandgeider** [comment]
I've beaten the docker-compose a bit into form, seems to be working enough now.

**Comment by AlexKalopsia** [comment]
Hi, I am having some issues setting up wget with docker-compose. 

What I did was to pull the entire repo, then run docker-compose.yml, but it results in a bunch of errors 

```
cp: cannot create regular file '/home/wger/src/settings.py': Permission denied
Waiting for postgres...
PostgreSQL started :)
Traceback (most recent call last):
  File "/usr/local/bin/wger", line 33, in <module>
    sys.exit(load_entry_point('wger', 'console_scripts', 'wger')())
  File "/usr/local/bin/wger", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: wger
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    setup_django_environment(get_path('settings.py'))
  File "/home/wger/src/wger/tasks.py", line 312, in setup_django_environment
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'
```

the docker-compose file in the extras folder seems to be exclusively focused on the dev environment, and I just want to have the latest release of wger running on my server. Any idea what could be the issue? I've tried following the docs but I am still a bit confused.

**Comment by rolandgeider** [comment]
I've moved this to a new issue
