### ISSUE TITLE
Improvements to building initial images db

### ISSUE THREAD

**Issue by illegalnumbers** [wger-project/wger#342]
Seems like building the docker image for all the workout images locally takes forever - could be something that needs improvement.

**Comment by rolandgeider** [comment]
It takes a lot of time because they are individually downloaded from wger.de, from that side there's nothing much that could be done. Do you know if it is possible to pass some flags to docker during build time or can this only be done when running the image?

**Comment by illegalnumbers** [comment]
I think you should be able to do that, I'd have to look more into it though.
