### ISSUE TITLE
Video reference -- feature request

### ISSUE THREAD

**Issue by plus13** [wger-project/wger#344]
Hi,
I propose a section for video references for each exercise. So everyone can get a better understanding how the workout should be in motion.

A user rated collection of links might be better then just one link to one video.

Example video: https://www.youtube.com/watch?v=6MzpiWqKhmg

**Comment by rolandgeider** [comment]
This is a good idea. I had thought about this as well, I'm not sure if there is already an issue for this, probably not. The only thing left to do is to think on how to manage new video submissions so that we're not rickrolled or worse, but besides that, this is definitely something we should implement

**Comment by mhanuel26** [comment]
You have to use a serious source of exercise video like bodybuilding.com, take a look at this

http://www.bodybuilding.com/exercises/detail/view/name/barbell-full-squat

There you have not only video but real pictures. 

You cannot relay on YouTube such the link provided, if you see the bodybuilding.com page have tons of exercise in the database and videos are well done, they go quickly into the point that shows how to do it.

**Comment by rolandgeider** [comment]
Yes, it's very important that we use high quality resources. As for the pictures, it is not easy to come across good quality images that are under a free license such as creative commons or similar. I might be able to get my hands on some, but that won't happen soon

**Comment by kuggaa** [comment]
We are adapting the workouts to lessons and practice drills for kids in sports.  These workouts need video to show the person how it is done.  Plus a video can be used to verify that an athlete is proficient at a skill and be checked off on it. 

Putting a video link embed from youtube is easy.  Where in the exercise section could one go?

**Comment by rolandgeider** [comment]
I could imagine doing it similarly to the images, a list of videos, 
perhaps with something like comment or such if e.g. the videos show 
different variations or alternatives. These videos could then be shown 
in the gym mode, etc.

As I said, showing a video is easy, finding them, not so much. If you 
say you are adapting the workouts, you probably already found some? :) 
If you do, I can look into implementing this.

Am 16.07.2017 um 00:05 schrieb Kuggaa Cuckoo Choo Choo:

**Comment by Juanezm** [comment]
It would be great to add this feature, added by youtube/vimeo link and embedded into the exercise description.

**Comment by rolandgeider** [comment]
This wouldn't be too hard to implement. Basically it's just a  new model Video with
  - url (check that it's either youtube or vimeo)
  - short description
  - foreignKey to exercise


 If someone wants to tackle this, go ahead! :)

**Comment by klu17** [comment]
@rolandgeider I'll try this one.

**Comment by rolandgeider** [comment]
Go ahead :)

But if you start, pull the code from #583, as there are some changes to the exercise model there

**Comment by ajh6** [comment]
Hi! I am a computer science student looking to contribute to an open source project. Any chance I can try to tackle this issue?

**Comment by ajh6** [comment]
also any other issues you need assistance on just let me know!

**Comment by ajh6** [comment]
Whatever you recommend is good to start with!

**Comment by rolandgeider** [comment]
@ajh6 I'd say the one with the full text search would be the most useful right now

**Comment by rolandgeider** [comment]
There is already support for (self hosted) videos, closing this issue. We can still re-open it if we see there's need for youtube/etc references
