### ISSUE TITLE
copy exercises to new workout day

### ISSUE THREAD

**Issue by antonkratz** [wger-project/wger#345]
I define a workout day with exercises, reps, weights. Now I want to add a new day to the workout. The new day might be identical, or very similar, to the first day entered. But I have to manually enter all the information again, every time. Suggestion: when adding a new day, make it possible to copy the exercises, reps, weights from any previous day into the new day, which can then be simply kept as-is, or modified. Would save a lot of user input.

**Comment by rolandgeider** [comment]
That would mean that the days within a workout have similar exercises, does this make sense? There is already an option to make a copy of full workouts because these are usually very similar. How exactly is your workflow?

**Comment by rolandgeider** [comment]
I'm closing this issue, if you still have questions @antonkratz , feel free to reopen it

**Comment by mhanuel26** [comment]
Hello,

Could you please let me know how to use the way you mention to copy the training day within the workout? Would it be great to add it to the UI as well if it's only available in the API.

Tkx in advance,
