### ISSUE TITLE
Requirement for days of the week for workout

### ISSUE THREAD

**Issue by illegalnumbers** [wger-project/wger#348]
Does it really make sense to require a day of the week for a workout? Wouldn't it make more sense to have a workout just be generated and then assign scheduling after the fact? Like you might want to try and have a 'one-off' workout or try something new or something.

**Comment by rolandgeider** [comment]
They are not strictly required. But they are accessed on a couple of places, e.g. for sorting within the workout page, on the dashboard and on the iCal-export. It would be nice to have truly flexible and understandable scheduling options, at the moment they are difficult to understand. I could have sworn there was already an issue for this, but I can't find it right now.

**Comment by illegalnumbers** [comment]
Hmm it seemed like on one dialogue they were explicitly required but yea, could use some work.
