### ISSUE TITLE
Improvements to the workout exercise adding page 

### ISSUE THREAD

**Issue by illegalnumbers** [wger-project/wger#349]
The 'Nr 1. Nr 2.' etc sets input is kind of confusing and also it would make more sense to just have sets be added on demand (maybe with like a plus icon?) same with the slider input, it is a little hard to tell offhand that that controls all sets for all exercises. Additionally, weights shouldn't appear on the page if they aren't added and are optional (ie the KG or LB designator) it adds a lot of 'noise' to the page.  

Also it might make sense to add a more advanced workout search functionality since you might not know what the exercises are called or you might want to search for particular exercises by muscle group.

Another cool feature idea would be to have a generated template workout. Something like a 5x5 workout or a P90x 'style' workout or something that you would expect from a class or a WOD or something, that would be really nice too.

**Comment by illegalnumbers** [comment]
It might make sense to move these inputs out from a modal on to their own dedicated page too - this is a pretty complex piece of functionality that seems like it should have it's own spot.

**Comment by rolandgeider** [comment]
There is definitely a lot of noise there. I haven't done much on that side because using angular on that dialog is one of the first things I want to do.
