### ISSUE TITLE
Exercise API

### ISSUE THREAD

**Issue by IronCoderXYZ** [wger-project/wger#354]
Hi!

I am doing a get request on  https://wger.de/api/v2/exercise
but it appears I am only getting a few exercises, not the whole list. 
Am I doing something wrong?

Thanks!

EDIT: Just saw there are multiple pages, is there a way to grab the whole list?

**Comment by rolandgeider** [comment]
Hi there! yes there is, you can pass a ```?limit=9999``` GET parameter, then you will get a list with, in this case, 9999 elements

**Comment by rolandgeider** [comment]
Closing issue to keep this more or less organised, feel free to reopen if this didn't work for you
