### ISSUE TITLE
Workout for Customer?

### ISSUE THREAD

**Issue by softagon** [wger-project/wger#355]
It's to possible to create workout for customer? 

Personal trainer creating a lot of workouts for customers?

**Comment by rolandgeider** [comment]
Hi there!

Yes, you can use the gym module to define trainers that create workouts for the customers and have an overview over things like last weight entry, etc. I know that the documentation is lacking a bit, but it's all possible, what exactly did you have in mind?

**Comment by rolandgeider** [comment]
I have updated the documentation, making it a bit clearer what's possible. Closing here
