### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by binxycraft** [wger-project/wger#361]
I am having trouble with the docker "demo". I had similar issues when I attempted to try out this project ~two months ago. This happens with the default command:
`docker run -ti --name wger.apache --publish 8000:80 wger/apache`
Then when I visit:
`http://localhost:8000/`
All I get is a page that displays:
```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Apache/2.4.18 (Ubuntu) Server at localhost Port 8000
```

I have tried on two different machines. Not that it should really matter with docker.

The only logs I get aren't useful but here they are:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
```

**Comment by rolandgeider** [comment]
The errors about the fully qualified name are OK to ignore, you would only need to actually set a server name if you serve a domain.

In any case, I'll take a look at the docker images, hopefully this is just a small configuration thing

**Comment by rolandgeider** [comment]
I have tested this and there is inded a problem. The WSGI process is not using the virtualenv for the application so it can't find django or any of the other dependencies, I'm not yet sure why

**Comment by rolandgeider** [comment]
The apache image is fixed now
