### ISSUE TITLE
Remove guest user and No registration

### ISSUE THREAD

**Issue by pchaganti** [wger-project/wger#367]
Modified settings.py to remove guest users and registration. Here are the relevant settings. Does not seem to have any effect at all. Also changed debug to false, but emails are not being sent, even though reset password says email was sent successfully. Anyone have any pointers? Using latest master installed from git today.

```Python
DEBUG = False
WGER_SETTINGS['ALLOW_REGISTRATION'] = False
WGER_SETTINGS['ALLOW_GUEST_USERS'] = False
```

**Comment by rolandgeider** [comment]
I could successfully turn off the registration and the guest users, do you have perhaps two settings files? (by default the bootstrap script will create one on ``.config/wger/settings.py`` unless you specify something else).

As for the emails, you need to configure an email backend in django, take a look at [its documentation page](https://docs.djangoproject.com/en/1.10/topics/email/#email-backends) to see what's available. I see that this is mentioned in the docs in passing, I'll be updating this so it's clearer

**Comment by rolandgeider** [comment]
TODO for me: move the section ``Miscellaneous settings`` to the settings page, where the wger-specific ones are mentioned

**Comment by pchaganti** [comment]
Ah. Will add the email config settings for the backend and try it out.

I am passing a settings.py to the start. Unable to turn off the reg and guest user. Will double check if there is another settings.py that is still being taken into consideration.

```
wger start --settings-path
```

**Comment by pchaganti** [comment]
For anyone else running into this. Add the following to settings.py:

```
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'urusername@gmail.com'
EMAIL_HOST_PASSWORD = 'password'
```

**Comment by rolandgeider** [comment]
Did you manage to deactivate guest users and registration?

**Comment by pchaganti** [comment]
Yes. I was able to.

thanks!

**Comment by rolandgeider** [comment]
Great, closing the issue
