### ISSUE TITLE
Password reset template

### ISSUE THREAD

**Issue by pchaganti** [wger-project/wger#368]
Where does one configure the vars used in the password reset email template? This would be things like site_name, etc.

Tried to set them in settings.py, but didnt have any effect, Not sure if I am setting them correctly.

**Comment by rolandgeider** [comment]
I can't look it right now, but I think to remember that those come from the 'sites' framework, take a look at the ``django_site`` table

**Comment by pchaganti** [comment]
That was it.

Thx!

**Comment by rolandgeider** [comment]
Glad it worked! I'm reopening the issue so that I can check that this is mentioned somewhere in the docs.
