### ISSUE TITLE
update number of set slider while using

### ISSUE THREAD

**Issue by pcuinty** [wger-project/wger#374]
Right now, when adding an exercise to the workout, the number next to the set slider doesn't update until you release the slider. Updating the number while sliding would be nice

**Comment by shreab373** [comment]
i'm new to the project and contributing in general, could i take this up? also could guide me in the right direction?

**Comment by rolandgeider** [comment]
Hi @shreab373, sure feel free to take this up!

The first thing would be to set up a development instance. This is documented on the README, but if you have worked with docker before, you could use that.

The changes to the slider are done in [the JS file](https://github.com/wger-project/wger/blob/master/wger/core/static/js/wger-core.js#L504) for the manager app. At the moment this uses the [change](https://api.jquery.com/change/) event handler, which only fires after the element loses focus. You'd need to look for something that fires immediately.

In any case, if you have questions or run into problems, just ask :)
