### ISSUE TITLE
Internal server error (500) when submitting POST to workoutsession API endpoint.

### ISSUE THREAD

**Issue by MLenthousiast** [wger-project/wger#379]
Hi, 

Im trying to save a workout session using the POST method to http://wger.de/api/v2/workoutsession/, but all I can seem to generate is an internal server error. The POST i am trying to make has the body:

```
{
    "date": "2017-04-04",
    "notes": "",
    "impression": "1",
    "time_start": null,
    "time_end": null,
    "workout": 109066
}
```

- For submitting the post I use the website API: http://wger.de/api/v2/workoutsession/
- I am logged in, and have a "workout" with id 109066, which already has some attached workoutsessions.
- Creating new workout sessions via the website user interface does work.
- The date is not used by another workoutsession yet.

Does anyone know what's going on here?

**Comment by MLenthousiast** [comment]
It seems like the following error occurs:
UNIQUE constraint failed: manager_workoutsession.date, manager_workoutsession.user_id

But I do not understand why? The workoutsession date (2017-04-04) is not used yet, so it should yield a unique constraint together with the user_id right?

**Comment by MLenthousiast** [comment]
Ok, stacktrace shows that in:
/home/wger/src/wger/manager/api/views.py in perform_create(...)

This code is called:

```
 today = datetime.date.today()   
 serializer.save(date=today, user=self.request.user) 
```

Which likely explains the error.. But I would assume that one should be able to make more than one workout sessions per day (which might have a different, unique, date however). For example when you are logging exercersises of the past week (which is also possible when you use the website).

**Comment by rolandgeider** [comment]
Hi there!

Yes, it is only possible to create a workout session per day, but you are right, that it should be possible to add sessions in the past. This is indeed a bug. I'm not sure why the today was there in the first place, if we are lucky, just removing (and perhaps adding some checks so that POSTs without a date get assigned to today) would be enough.
