### ISSUE TITLE
Enhancement Request :  More minerals can be listed in "Add new ingredient"

### ISSUE THREAD

**Issue by karunaguru** [wger-project/wger#395]
Only "Sodium" is seen/listed in Add new ingredient . But some grains and millets have additional minerals too like pottassium, calcium etc. These minerals can be listed.

**Comment by rolandgeider** [comment]
While this is true, I have kept the possible minerals close to the nutritional values listed on products to make it easier to add new ones (just copy all of them). Also, showing too much information can get confusing very fast and offers little added benefits.
