### ISSUE TITLE
Workout scheduler improvement -  decoupling needed perhaps.

### ISSUE THREAD

**Issue by mhanuel26** [wger-project/wger#399]
Hello,

I think the intuitive behavior and actually the one desired for scheduling workout sessions (at least for me) during a period is to be able to show the scheduled workout in the calendar, to explain better
I created a workout session (only one training day) that should be done on Tuesday, Thursday and Saturdays, then I schedule a workout using it for the next two weeks. But the workout isn't visible on the calendar unless I add the log, so what was the point to schedule it in first place?
Then I cannot filter by date to look at the workout for a given day easily or at least not using UI, is that available using the API? 
Also if I want to repeat the same workout three days per week (I am doing a Full body workout which consist of the same exercises) but change the weights I want to lift on each workout session it cannot be done, so you have to create six (6) training days repeating the same exercises on them to specify weights and reps, but then the scheduling behavior described is the same.

Am I missing something here or the API need some decoupling, for example it would be great to have the workout separated completely from the data (weight, reps, etc), so users can add the same workouts and change the data for a given date in the calendar.

Please let me know your thoughts,

**Comment by mhanuel26** [comment]
Hello Roland,

Did it make sense the above reasoning about workouts and scheduler?

Please let me know your comments,

**Comment by rolandgeider** [comment]
Hi Manuel,

first thing, sorry for the late reply!

You are definitely right in that the current implementation of the 
schedules is weird and not too flexible (this was actually added as an 
afterthought). This is also one of the reasons why there isn't any 
scheduling for the meals, I didn't want to do it like for the workouts.

I am open to thinking about a new system that is more flexible and 
better integrated and can be used to plan the nutrition as well. We 
could then do the weight changes as well. Do you have python experience? 
I don't think I'll be able to program much right now, plus there are 
other aspects I want to finish first, but I can definitely brainstorm 
with you the details!



Am 19.07.2017 um 18:39 schrieb Manuel Iglesias Abbatemarco:

**Comment by mhanuel26** [comment]
Hi Roland,

Thank you for your answer,

I was starting to think my comment about the scheduling was out of sense...

Yes I have experience in python, not too much with django but have used other frameworks.
I am willing to contribute here, I haven't take a look at source, I will do it asap and let you know when in doubt.

About brainstorm, first thing I would like to change is the workout, for me a "workout" is more a thing you do one day, then you can repeat the workout let's say three times a week, then you can call it "routine", so the routine is composed of a given workout performed three time per week.

More specific thing I would like to implement has to be with [HST](http://hypertrophyspecific.com/hst_index.html) training, there are two basic concepts there that I will want to take into account when talking about "workouts". HST is based on "workout cycles" and it introduces (as far as I know but other training methods might have similar concept) the concept of macrocycle and [mesocycle](https://www.bodybuilding.com/fun/ridgely1.htm), a macrocycle is composed of three mesocycles. A mesocycle is composed of a certain number of workouts, for HST a minimum of 6 workouts.
The big difference between mesocycles in HST is the handle weights during the workouts, as you can perform an HST cycle using the same exercises. For HST a mesocycle takes two weeks so a cycle can take between 6 to 8 weeks, so basically you can perform the same workout week after week with a variation in the lifted weights.

So first thing would be to create the figure of a single day workout than can be scheduled for different days, those workouts per se should not have any weight information attached, rather that will come when schedules is done. Ideally, I would like to create the mesocycle figure or in more general sense a "routine" in which I can group a number of workouts evenly spaced on a period of time.

One more thing I noticed was the lack of API to handle the workout scheduling, it seems the things you can "currently" do using the web cannot be done (at least easily or in a intuitive manner) using the API. For example, once a workout is scheduled it was difficult for me to gather the exercises of it for example to create a "view" that shows you what to do on that day. Ideally I would like to do that and immediately or in real time be able to log each exercise performed.

What do you think?
Would you have a suggestion of where to start doing the modifications ?

Please let me know,

**Comment by dometto** [comment]
> , first thing I would like to change is the workout, for me a "workout" is more a thing you do one day, then you can repeat the workout let's say three times a week, then you can call it "routine", so the routine is composed of a given workout performed three time per week.

I would second this. Another reason for it is I might not have a specific day in the week for e.g. my 'Pull' day -- it might vary between Mondays and Tuesdays, say, depending on when I have time. Are any changes to the relationships between Workouts, programs, and days scheduled?

**Comment by dometto** [comment]
Isn't this superseded by https://github.com/wger-project/wger/issues/848?

**Comment by rolandgeider** [comment]
yeah
