### ISSUE TITLE
Cannot access webpage from remote device

### ISSUE THREAD

**Issue by iwrestlethebear** [wger-project/wger#400]
Hi - 
I just deployed a "dev" instance of wger on Linux Mint. I have no problem accesing the webpage from the local machine. However, if I try to access the webpage from a remote device it will not load. Firefox is saying "connection was reset".
Looking at the output of "netstat -tupan |grep 8000" I can see that it is binded to localhost.
`# netstat -tupan |grep 8000`
`# tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN`

Taking a similar output, CouchPotato, for exemple its output is the following. We can see localhost is not binded.
`# netstat -tupan |grep 5050`
`tcp        0      0 0.0.0.0:5050            0.0.0.0:*               LISTEN`

All of that to say, and ask (politely): Where and which config file would have to be modified in order to access the webpage/website from any remote device?

Thank you for your time,
Alex

**Comment by iwrestlethebear** [comment]
Figured it out. You specifiy the socket as an argument in the command as show in the exemple
`python manage.py runserver 0.0.0.0:8000`

**Comment by rolandgeider** [comment]
Hi there!

Sorry for the late answer... Yes, you need to specify the IP when 
running the server. This is BTW the default django behavior, nothing 
specific to the project

Am 11.07.2017 um 00:33 schrieb iwrestlethebear:

**Comment by iwrestlethebear** [comment]
Thanks for the reply, I ended up reading on django and realized that!

Thank again, cheers

Alex

Sent from my iPhone

On Jul 19, 2017, at 05:23, Roland Geider <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi there!

Sorry for the late answer... Yes, you need to specify the IP when
running the server. This is BTW the default django behavior, nothing
specific to the project

Am 11.07.2017 um 00:33 schrieb iwrestlethebear:
