### ISSUE TITLE
Disable registration

### ISSUE THREAD

**Issue by elfalem** [wger-project/wger#402]
Thanks for this software. Is it possible to disable the registration form?

**Comment by rolandgeider** [comment]
Hey there!

Sure, you just need to set the 'ALLOW_REGISTRATION' Setting to False, 
take also a look here: https://wger.readthedocs.io/en/latest/settings.html

Am 18.07.2017 um 04:27 schrieb elfalem:

**Comment by elfalem** [comment]
Thanks!
