### ISSUE TITLE
Enhancement Request: Posibility to add body measurements

### ISSUE THREAD

**Issue by iwrestlethebear** [wger-project/wger#403]
Good day,

I believe it would be a good idea to add fields to add our body measurements and body fat. Currently I need to use a different app just to manage these two. I think that it goes against the grain, since I can my manage my workouts, schedule and even nutrition with Wger, but no places to enter body stats.

Thank-you,
Alex

**Comment by DandyDeveloper** [comment]
Since you haven't received a response, is there a particular location you want these? Is this per workout or purely as part of the account? 

Shouldn't be hard, but best to define requirements. 

Would be nice to get an Administrator to agree to these requirements.

**Comment by DandyDeveloper** [comment]
@rolandgeider This won't be too hard to implement. However, how would you prefer its included? Do you want a separate model of `measurements`? That seems the most reasonable. 

I see that `core` already has a weight model that is actually picking up from the latest weight. We could just add a field representing this in the new model and add other model entries representing measurements. 

You'll basically have core.Measurements model -> Measurements view as part of Core available under Preferences(?). 

Alternatively, we just add this as its own model outside of core. Let me know preference and I'll start working on it.

**Comment by rolandgeider** [comment]
There is already an existing issue for this, 
https://github.com/wger-project/wger/issues/133

The idea there was to be able to add generic "measurements", which are 
just entries that have a label such as "waist", etc. and a value (cm, 
in, etc.). There would be a couple of "system wide" (or "gym wide"?) 
labels that can't be deleted, but the user could add their own

Am 07.10.2017 um 21:42 schrieb Aaron Layfield:

**Comment by DandyDeveloper** [comment]
Where would the system wide labels sit in your opinion? Under an existing model, or a new one? I'm just trying to determine whether my PR that I'm working on might need to be removed.

**Comment by rolandgeider** [comment]
I'd add a new model in the measurements app, no need to remove the PR. It would just need a label and a reference to User and Gym, which would be both optional. The BodyMeasurementsEntry would then have a foreign key to it

**Comment by rolandgeider** [comment]
Closing issue, further discussion in #133
