### ISSUE TITLE
Is there a hosted instance that is available?

### ISSUE THREAD

**Issue by grantkemp** [wger-project/wger#407]
For those of us who want to use the system for longer than 7 days- it would be great to get a hosted instance.

**Comment by rolandgeider** [comment]
Hi there!

There is a hosted instance, https://wger.de/ The seven days you are 
referring to are only for the demo account, if you register, you can use 
the system as long as you want, nothing will get deleted.

Am 19.09.2017 um 15:14 schrieb Grant Kemp:
