### ISSUE TITLE
Setup instructions are messed up!

### ISSUE THREAD

**Issue by mwaz** [wger-project/wger#415]
How do i get create_settings command in Wger while setting up?

I am also not able to find the database.sqlite file, is there something i am missing?

**Comment by rolandgeider** [comment]
Hi there! You create the ```wger``` command by doing ```python setup.py develop```, then you can pass it different subcommands, such as create_settings. You can see where the default locations for the sqlite database and the settings files are by doing ```wger config_location```

**Comment by mwaz** [comment]
thanks, pip install wger is way better though..

**Comment by mwaz** [comment]
@rolandgeider what is the default command for using wger especially after pip install wger

i have tried both `create_settings` and `create-settings` and sometimes one just fails only for the other to work, i am not sure which is the default create settings command to use

**Comment by rolandgeider** [comment]
The behavior should be consistent, do you mean sometimes one works and sometimes the other, randomly?

**Comment by mwaz** [comment]
yea that is what i mean...
