### ISSUE TITLE
Android/iOS client

### ISSUE THREAD

**Issue by mbnoimi** [wger-project/wger#418]
Hi,

Is there any Android/iOS client(s) for wger? If not I'm planning to create a new client for mobiles & desktops using Qt (the license just like wger; AGPLv3)

The main reason of it is for making wger available offline (sync support)

**Comment by rolandgeider** [comment]
Hi there!

There is technically a client for android, but it's just WebView wrapper around the hosted instance wger.de, so not really. Did you plan to make the Qt client use the REST API or use a local database? In any case, really interesting idea, keep me posted :)

**Comment by mbnoimi** [comment]
> Did you plan to make the Qt client use the REST API or use a local database?

It'll use same database structure (clone of wger sqlite db) which will sync with online db through REST API.

**Comment by rolandgeider** [comment]
Nice, once you start writing code, send a link to the repo

**Comment by rolandgeider** [comment]
We're currently working on a flutter app for the application, closing here
