### ISSUE TITLE
Navigation menus not showing on the development version

### ISSUE THREAD

**Issue by andreww591** [wger-project/wger#420]
I installed the latest development version (cd2083ae4ff5a299ed146ac58d8329d4a476727e) in Docker, and the navigation menus don't display at all. Also, tabs such as on the Exercises page just display as regular text with no borders at all. The menus are present in the page source, so this seems to be a CSS or possibly JS issue (possibly a backwards-incompatible change in one of the dependencies; it would be a good idea to install known-working versions rather than assuming the current version of everything will always be compatible).

**Comment by rolandgeider** [comment]
Yes, this sounds like a CSS issue. There have been some improvements in the dockerfiles and in the dependency handling. I'm closing this issue now, feel free to open it again if it breaks again
