### ISSUE TITLE
Menu not visible, not able to edit workouts ... options menu not coming up

### ISSUE THREAD

**Issue by elwardipol1** [wger-project/wger#425]
Hi @petervanderdoes, @rolandgeider, I really like this marvelous piece of software, but I'm running into some trouble her:
I'm on Ubuntu 16.04 and I installed `wger` using `pip`,
When I login, I can create a new workout and add exercises to it, but I don't seem to be able to do anything else:
* There is no dashboard/workouts/exercises/... navigation menu.
* There are no move/edit/delete little icons in front of exercises.
* Clicking "options" button has no effect at all.

From my understanding:
* This could be a problem with the database?
* It also could be a problem with `bootstrap` command!

It's worth mentioning that when I run the command `pip install wger` I notice some packages are installed in python2.7 path! even though venv-django should use python3.5, is this normal?

Any help would be greatly appreciated!!

**Comment by Veltarn** [comment]
Hi @elwardipol1 
Are you trying to edit these exercices as another user as the admin one?

I ran into that trouble either and has to edit the exercices with the admin account.

**Comment by larssorenson** [comment]
I'm trying to get this running now myself and it looks like there was some issue with the JavaScript dependencies; Bootstrap's Dropdown menu feature seems to require Popper.js which wasn't installed with wget. Not sure what happened but I think the dependencies have moved while this project stayed relatively still

**Comment by rolandgeider** [comment]
CSS and JS dependencies are now managed differently, closing issue
