### ISSUE TITLE
Add minimum length to ingredient name

### ISSUE THREAD

**Issue by Wieke** [wger-project/wger#426]
So there appears to be a minimum term length (3 characters) for the ingredient search but no minimum length for ingredient names. So it's possible to create an ingredient that can't be found because the name is too short. Granted there are probably not that many ingredients with such a short name, though the default list of Dutch ingredients contains "Ui" (onion). 

The obvious solution to me seems to add minimal ingredient name length to the ingredient creation forms.

**Comment by austin-leung** [comment]
I'll look into this!

**Comment by rolandgeider** [comment]
👍🏻👍🏻
