### ISSUE TITLE
Verifying users with the REST API

### ISSUE THREAD

**Issue by shaheenkdr** [wger-project/wger#427]
Assume I create few users , with corresponding username and password, And I provide it to the users , How will I authenticate/check if the corresponding username/ password match the same credentials ? 
OR

In other words, is there a mechanism in the API to verify the username and password match/exist inside the web back-end before providing other services? 

Please do kindly help

**Comment by AlexBueckig** [comment]
As far as I understand you have to provide the API-key to the private request endpoints. You can see an example right here: https://wger.de/en/user/api-key

So to make it clear... If you are using the rest-api there is no explicit authentication method. Every user needs to generate an own api key on the page I linked after logging in with their account data. The API-Key then needs to be saved by the user themself in your application. You will then set the authorization header field with the api key and then the requests will be automatically authenticated.

Or to answer your second question... Yes, there is such a mechanism! 
- API-Key available = User verified
- No API-Key available = User not verified
