### ISSUE TITLE
Encoding Issue during Bootstrap

### ISSUE THREAD

**Issue by hibes** [wger-project/wger#428]
### Description
I am running some kind of (possibly bower related) encoding issue when bootstrapping the project from source or from pypi.

### Log output
```
 'output': <open file '<stdout>', mode 'w' at 0x7fa0cc6d1150>},
 'target': <bound method Local.handle_stdout of <invoke.runners.Local object at 0x7fa0ca1adbd0>>}

Traceback (most recent call last):

  File "/root/wger/.venv/local/lib/python2.7/site-packages/invoke/util.py", line 125, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/root/wger/.venv/local/lib/python2.7/site-packages/invoke/runners.py", line 547, in handle_stdout
    reader=self.read_proc_stdout,

  File "/root/wger/.venv/local/lib/python2.7/site-packages/invoke/runners.py", line 519, in _handle_output
    self.write_our_output(stream=output, string=data)

  File "/root/wger/.venv/local/lib/python2.7/site-packages/invoke/runners.py", line 506, in write_our_output
    string = string.encode(self.encoding)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 325-333: ordinal not in range(128)
```

### System and Versions
Running off the `1.8` tag on an LXC based `ubuntu 16.04` container.  I was having the same issue with the `stable` version as well.  It's a mostly blank system (container) with nothing else on it other than base `ubuntu 16.04` and the requirements for `wger`.

```
# python --version
Python 2.7.11+
```

I was hoping this was just an encoding issue (may still be) that would be easy to fix, so I tried this before running the bootstrap (`wger bootstrap ...`) command:
```
export PYTHONIOENCODING="utf-8"
```

Unfortunately, no such luck.

**Comment by Veltarn** [comment]
Hi @hibes 

I see you are using Python 2.7+ but wger uses Python 3+.
Among the most major changes from Python 2.X to Python 3.X, the way the language manage encoding is one of the most importants.

Try to switch to Python 3.5 and keep me informed ;)

**Comment by rolandgeider** [comment]
Hi there! Yes, I also suspect this is due to using python 2.7 (Django itself also has dropped support for 2.7)
