### ISSUE TITLE
Operational Error : unable to open database file

### ISSUE THREAD

**Issue by shaheenkdr** [wger-project/wger#429]
Trying to deploy wger in production. Followed the docs . Installed all dependencies, Apache is running fine , no errors, however when I launch the domain, It gives the error :

    Operational Error : unable to open database file

This is where the database is stored :

/home/wger/db/database.sqlite

And in order to make sure I have the permissions, I did :

chgrp www-data /home/wger/db/
chgrp www-data /home/wger/db/database.sqlite
chmod g+w /home/wger/db/
chmod g+w /home/wger/db/database.sqlite
chmod 664 /home/wger/db/database.sqlite
chmod 664 /home/wger/db
sudo chown :www-data /home/wger/db
sudo chown :www-data /home/wger/db/database.sqlite
sudo service apache2 restart

However, the issue still persist. what is possibly causing this and how to effectively resolve this ?

**Comment by rolandgeider** [comment]
I have updated the documentation and the dockerfile.

In case anybody else has the problem, both the sqlite file **and**  the folder must be writable by the apache process, in this case

```bash
chown :www-data -R /home/wger/db
chmod g+w /home/wger/db /home/wger/db/database.sqlite
```
