### ISSUE TITLE
Unencrypted HTTP traffic

### ISSUE THREAD

**Issue by Anth0rx** [wger-project/wger#431]
Wger is not automatically redirecting to encrypted HTTPS. I would recommend doing so, since it is available but Wger defaults to unencrypted HTTP.

**Comment by triDcontrols** [comment]
Use Nginx as reverse proxy.

**Comment by rolandgeider** [comment]
You mean the wger.de instance? That should be fixed in the meantime. The docker files or the installation instructions are not meant to be production-ready, you'll want to configure that a bit differently
