### ISSUE TITLE
Body Mass Index (BMI) calculator not working

### ISSUE THREAD

**Issue by LorenzoAncora** [wger-project/wger#433]
I am logged in (not anonymous) and the button to calculate the BMI does not work and I see no graphs.
The answer to the background request is:

---

#### `'AnonymousUser' object has no attribute 'userprofile'`
Request Method: `GET`
Request URL: 	`http://`<sup>[IP:PORT]</sup>`/it/nutrition/calculator/bmi/chart-data`
Django Version: `1.10.8`
Exception Type: `AttributeError`
Exception Value: `'AnonymousUser' object has no attribute 'userprofile'`
Exception Location: ``/home/wger/venv-wger/lib/python3.6/site-packages/django/utils/functional.py in inner, line 235``
Python Version: `3.6.6`

---

Can be related to #146 but the value when the page loads is different from 0 (29,1) and never changes.

**Comment by LorenzoAncora** [comment]
@rolandgeider @petervanderdoes is this an unsolvable problem? :-)

**Comment by LorenzoAncora** [comment]
@rolandgeider @petervanderdoes is this an unsolvable problem? :-)

**Comment by LorenzoAncora** [comment]
@rolandgeider @petervanderdoes is this an unsolvable problem? :-)

**Comment by Veltarn** [comment]
Hi.

I'm going to check on the code but my first intuition is that the very nature of the Anonymous User prevent it from having a writable profile.
I may mistake though :)

**Comment by LorenzoAncora** [comment]
> I'm going to check on the code but my first intuition is that the very nature of the Anonymous User prevent it from having a writable profile.
I may mistake though :)

@Veltarn a calculator should not require a writable profile. Regardless of that, the software should give a comprehensible error message or hide the unavailable functionality.

**Comment by LorenzoAncora** [comment]
> I'm going to check on the code

@Veltarn time has passed. There are updates? If you have solved the problem please set the "Resolved" label and close this issue.

For any need I remain at your disposal. :-)
Have a good time.

<sub>PS: if you have decided not to fix the problem, set the "Won't fix" label. It would be a shame since the program is very useful, but I don't like leaving the issues open.</sub>

**Comment by Veltarn** [comment]
I'm not assigned to the issue, I cannot commit on this repo and there is a lot of pending push requests that are not processed by the devs of the project.
I wasn't and won't be able to help you ;)

I forked the project several months ago tho, it's a bit different from wger now

**Comment by LorenzoAncora** [comment]
@Veltarn sorry no one is assigned to the issue and **it is not clear who is managing the repository** (which is registered under a generic "wger-project" account). :-)
In your opinion, is it the case to close the Issue?

**Comment by Veltarn** [comment]
@LorenzoAncora no problem ;)
Well, you can close this issue as I don't think it will get more answers than mine :/
I will take a look to this error on my fork, I didn't worked on nutrition yet but I will soon!

**Comment by LorenzoAncora** [comment]
>  Well, you can close this issue as I don't think it will get more answers than mine :/
I will take a look to this error on my fork, I didn't worked on nutrition yet but I will soon!

@Veltarn  well, then I close.
When my ARM board is ready, I'll try your [fork](https://github.com/Veltarn/wger-bs), which I've already starred.
Have a good time buddy. ;-)
