### ISSUE TITLE
Installation issues on windows/ pythonanywhere

### ISSUE THREAD

**Issue by ljgebman** [wger-project/wger#434]
I keep encountering issues with incompatible packages. I've tried installing through bash on pythonanywhere when I try to "invoke bootstrap"
  File "/home/ether/venv-django/lib/python3.6/site-packages/django_mobile/conf.py", line 33, in defaults
    for loader in django_settings.TEMPLATE_LOADERS:
  File "/home/ether/venv-django/lib/python3.6/site-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_LOADERS'

In windows i hit some other errors.

 building '_rcssmin' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'

    ----------------------------------------
Command "c:\python\home\venv-django\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\sqler\\AppData\\Local\\Temp\\pip-install-l2m69srk\\rcssmin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\sqler\AppData\Local\Temp\pip-record-mw64hygo\install-record.txt --single-version-externally-managed --compile --install-headers c:\python\home\venv-django\include\site\python3.6\rcssmin" failed with error code 1 in C:\Users\sqler\AppData\Local\Temp\pip-install-l2m69srk\rcssmin\

Doesn't look like the project is being maintained but any installation tips or suggested workarounds would be greatly appreciated.

**Comment by Veltarn** [comment]
Hi @ljgebman 

What's the version of django you are using?
