### ISSUE TITLE
__init__() got an unexpected keyword argument 'attrs'

### ISSUE THREAD

**Issue by Kr118218** [wger-project/wger#439]
When installing wger, I have these messages

> django-recaptcha 2.0.2 has requirement django<2.3,>1.11, but you'll have django 1.9.13 which is incompatible.
> django-filter 2.1.0 has requirement Django>=1.11, but you'll have django 1.9.13 which is incompatible.
> django-cors-headers 2.5.2 has requirement Django>=1.11, but you'll have django 1.9.13 which is incompatible.

Which version of Django am I supposed to use?

After installation, when trying to run the server I keep stucked with this error

> TypeError: __init__() got an unexpected keyword argument 'attrs'

**Comment by larssorenson** [comment]
Looks like the required dependencies are ahead of this project's Django version. If you install:
```
django-recaptcha==1.4.0
django-cors-headers==2.4.1
django-filter==1.1
```

into the venv before you run `wger bootstrap` it should work.

You can do this by running:
`pip install <package>==<version>`
