### ISSUE TITLE
Language filter for exercise comments

### ISSUE THREAD

**Issue by jegglestone** [wger-project/wger#450]
https://wger.de/api/v2/exercisecomment/?id=597&page=1

Exercise comments is currently a mix of English and German with no language id field.]

Please could you add a language field like you have in the exercise endpoint so I can get exerisecomment?id=123&language=2

Thanks

**Comment by rolandgeider** [comment]
the exercise comments have no language filter on themselves, the language is set on the exercises.

TODO: see if it is possible to add to filterset_fields foreign keys like in django's own ORM
