### ISSUE TITLE
Unavailble id filter for some endpoint with the REST API

### ISSUE THREAD

**Issue by clallavena** [wger-project/wger#452]
Hello !

I'm looking to use the filter in some endpoint and I've noticed that for some endpoints, filter with ID is not available, like `http://wger.de/api/v2/equipment?id=1` cannot give me the right equipment.

Can you pls give me hint if I do it wrong? 
Appreciate.

**Comment by rolandgeider** [comment]
Filtering for IDs for all data endpoints is a sensible feature.

TODO: make sure that 'id' is included in filterset_fields

**Comment by oconnelc** [comment]
If no one else is looking at this, I'd like to try and fix.

**Comment by rolandgeider** [comment]
Go ahead!

**Comment by rolandgeider** [comment]
I just noticed, this is actually not needed, to get the details of a single object  (equipment or something else) you call /api/v2/equipment/1/

Closing here
