### ISSUE TITLE
Docker production support

### ISSUE THREAD

**Issue by charles200000** [wger-project/wger#453]
I created a docker compose and tweak the environment to have full support for wger in docker in production. I am using it under nginx proxy pass with https, and it is working OK.
Are you interested in those config files ?

**Comment by teadur** [comment]
seems useful to me

**Comment by Pfuenzle** [comment]
yes would be nice to have, have you managed to add the /home/wger/db folder as a docker volume?

**Comment by charles200000** [comment]
yes this is exactly what I have done plus some docker optimization

**Comment by Pfuenzle** [comment]
Well I tried to do it but I for some reason wger was not able to write (maybe also to read) to the .db file, even though i gave it the same permissions as in the docker container and im not experienced enough with linux to fix it.
Can you please share your Dockerfiles? Would be great

**Comment by charles200000** [comment]
hummm yeah I had the same problem, basically when you add a folder to the docker maping system it overite the docker folder with the one from the host machine. So you need to have the db init db already in the folder. So you first run the docker without the -v command. Copy the sqlite.db place it in the folder you want to map, then use this command :

sudo docker run -d -ti -v /home/maclgadmin/wger/db:/home/wger/db --restart always --name wger.apache --publish 8000:80 wger/apache

**Comment by Pfuenzle** [comment]
Aaah now it worked. Thanks a lot dude, this was really helpful

**Comment by charles200000** [comment]
no problem haha

**Comment by AlexKalopsia** [comment]
Hi @charles200000, would you mind sharing your docker-compose file?
