### ISSUE TITLE
Incompatibility with SQLite

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#456]
There is a behaviour change with SQlite 3.26 that produces an error when the django migrations change a foreign key (there are ```_old``` table references) and is not possible to bootstrap the application. Other DBs such as Postgres work, though.

https://code.djangoproject.com/ticket/29182

Roadmap: Since the solution involves update to django 2.0 where this is fixed, with all the template and form rendering re-work needed, I'll do that, make sure the application works is installable, release 1.9 and call it a day. Any other features or open PRs will be pushed back.

**Comment by speshak** [comment]
I opened #459 to address getting my changes merged so we don't further pollute the discussion here.

**Comment by rolandgeider** [comment]
Closed with commit above, application can bootstrap an sqlite DB again
