### ISSUE TITLE
Get work from speshak:master merged.

### ISSUE THREAD

**Issue by speshak** [wger-project/wger#459]
I've been maintaining a fork with a lot of the prerequisite work for Django 2.0.  The changes should merged in as appropriate.  Because I made some changes early on to break dependencies from the original wger project, it can't be done in a single PR.  Instead I will open PRs bundling logical chunks of work.

**Comment by rolandgeider** [comment]
The two PRs are merged. I see that you have made a lot of commits and changes on your dev branch. How should we proceed with that? Is there anything you want to clean up or something? If I can help you with anything, just tell me!

**Comment by speshak** [comment]
Let me do a rebase on the updated master and see how things look.  There are some commits that shouldn't go upstream from my branch that I'm cherry-picking around.  (The changes are related to removing dependencies on this project because I wasn't sure about it's long-term status.)

**Comment by speshak** [comment]
I've opened #460 to get the last of my (useful) work merged in.  One of the new features included is the ability to host the static assets in AWS S3 with a CDN, but I probably didn't document its usage well enough for someone else to just pick up.  I'll open a issue to get that shored up so it can be useful for people other than me.
