### ISSUE TITLE
Mantain docker image

### ISSUE THREAD

**Issue by felixsanz** [wger-project/wger#470]
Hi folks. It is possible to get an official and maintaned docker image on docker hub?

**Comment by rolandgeider** [comment]
Hi there! There are images on docker hub, if you pull e.g. wger/devel it will download it from there

**Comment by felixsanz** [comment]
But wger/devel is for development isn't it?

**Comment by rolandgeider** [comment]
Then you want wger/apache, take a look at the readme on how to start it

**Comment by felixsanz** [comment]
Ok, i didn't check the Dockerfile, i just saw "Updated 3 years ago". But it's a git clone so it's ok i guess. Thanks
