### ISSUE TITLE
Total energy is not the approximate sum of the energy provided by protein, carbohydrates and fat.

### ISSUE THREAD

**Issue by modem7** [wger-project/wger#476]
Heya, 

I'm getting this particular error when trying to input the nutritional details of https://www.musclefood.com/turkey-thigh-mince-400g.html

Unsure if the issue is on my end? 

Thanks!

**Comment by rolandgeider** [comment]
Mhhh, it should be, at least as an approximation. In the models we use these values
1g of protein: 4kcal
1g of carbohydrates: 4kcal
1g of fat: 9kcal

That is summed and the result has to be within a range of +/- 15%
