### ISSUE TITLE
Feature Request: remove or edit weight entry

### ISSUE THREAD

**Issue by FranciumF** [wger-project/wger#478]
- [ ] Remove or edit weight entry

**Comment by rolandgeider** [comment]
Yes! I'm not even sure if this is already possible via the API, but the entries need to be deletable via the website as well

**Comment by rolandgeider** [comment]
- [ ] Add appropriate delete/edit views (and tests, but this is mostly copy&paste)
- [ ] Add dropdowns to the weight list in the overview page with the two options
