### ISSUE TITLE
Feature request: add possibility to (next to weight) also include RPE (rate of perceived exertion) to each set of weight lifting

### ISSUE THREAD

**Issue by doodhout** [wger-project/wger#479]
This is because not only the performed sets x reps x weight is important, the RPE is very important in the sense that it tracks the difficulty of the performed set and serves the purpose of having a complete log of the session. If RPE is missing, then the log being incomplete isn't very useful.

RPE is expressed in a number from 1 to 10; 1 being very easy and 10 being the most intense a movement could be without failing. RPE with halves is sometimes used, e.g. RPE of 7,5; 8,5; 9,5 to have slightly more values to add more nuance.

Currently the following can be defined for a set: number of reps, weight and unit of weight. I would like RPE to be added to that, with the possibility to use a number from this set: [1; 2; 3; 4; 5; 6; 7; 7,5; 8; 8,5; 9; 9,5; 10]. I realise that the numbers 1 till 5 are not very useful, but I'd add them just for completeness' sake.

**Comment by rolandgeider** [comment]
Good idea. I had also thought to add Reps In Reserve or something similar. The difficulty would be to present it in a way that is not overwhelming when somebody does not want wo use it

**Comment by rolandgeider** [comment]
Another Todo more or less related to this: streamline the log overview to be more useful

**Comment by rolandgeider** [comment]
What needs to be done here:

- [ ] change the Setting model and add a new field (either reps_in_reserve or rpe) and add the appropriate list as possible values. 
- [ ] update the crispy form to show them
- [ ] show the  values on the workout overview

**Comment by SkyNetIndustry** [comment]
Hello,
If this is still open, I'd like contribute it.

**Comment by rolandgeider** [comment]
Hi! Yes it's still open, you can go ahead

**Comment by SkyNetIndustry** [comment]
You indicated pty=True, but your platform doesn't support the 'pty' module!

Any help? The second option docker :D

**Comment by rolandgeider** [comment]
🤔🤔

which docker are you using the devel image?

**Comment by SkyNetIndustry** [comment]
I got it started :)

**Comment by doodhout** [comment]
> 
> 
> Good idea. I had also thought to add Reps In Reserve or something similar. The difficulty would be to present it in a way that is not overwhelming when somebody does not want wo use it

Yeah RPE and RIR (reps in reserve) are the same metric really, so any one of those is fine.

Thanks for starting this!

**Comment by SkyNetIndustry** [comment]
If I understand correctly, is it necessary to change this form?
![Screenshot_2](https://user-images.githubusercontent.com/53763744/95853782-43285f80-0d56-11eb-9657-336098313224.png)

**Comment by rolandgeider** [comment]
Yes, after changing the Settings and the WorkoutLog models, take a look at WorkoutLogFormHelper in manager/forms.py

**Comment by rolandgeider** [comment]
BTW, I would prefer to go with Reps In Reserve, as I find it more intuitive to say "I could have done two reps more". This only changes the possible values in the dropdown, which would go from 4.5 to 1

**Comment by doodhout** [comment]
@rolandgeider RIR is an excellent choice! Would you like to have "half" reps in reserve? It's usual to use that in RPE-scale, but in RIR-scale I don't know whether it has the same usefulness.

**Comment by rolandgeider** [comment]
Mhhh, I see what you mean. I guess it depends on what meaning you'd give to the half reps.

**Comment by doodhout** [comment]
Technically I don't think it's of use to allow half reps in reserve, because reps cannot be counted in halves. It does however adds nuance to the number, because 1 RIR can mean anything from "just barely 1" to "certainly 1 and maybe two but not sure". Meh, first-world problems.

**Comment by rolandgeider** [comment]
> 1 RIR can mean anything from "just barely 1" to "certainly 1 and maybe two but not sure". Meh, first-world problems.

Exactly. I'd vote to leave the halves in 😄

**Comment by rolandgeider** [comment]
This is merged and is available on master 🕺🏻 I'll update the server the next days

**Comment by addyhub** [comment]
> You indicated pty=True, but your platform doesn't support the 'pty' module!
> 
> Any help? The second option docker :D

Hi so I'm getting the same issue 
You indicated pty=True, but your platform doesn't support the 'pty' module!
How did u fix this?

**Comment by SkyNetIndustry** [comment]
> > You indicated pty=True, but your platform doesn't support the 'pty' module!
> > Any help? The second option docker :D
> 
> Hi so I'm getting the same issue
> You indicated pty=True, but your platform doesn't support the 'pty' module!
> How did u fix this?


Hi addyhub
I learned the docker and used it to code. Since then, only docker 😄 🐋

**Comment by addyhub** [comment]
> You indicated pty=True, but your platform doesn't support the 'pty' module!
> 
I'm having this issue any fix?
