### ISSUE TITLE
Error when searching specific exercises?

### ISSUE THREAD

**Issue by nickycdk** [wger-project/wger#495]
Hi 

First of all, thanks for this amazing api...
However, seems to be a few bugs... When doing an exercise search for "benchpress", the API returns a permission error, the same goes if i search for "press"

Take a look here: https://wger.de/api/v2/exercise/search/?term=benchpress

**Comment by rolandgeider** [comment]
Thanks!

And you are right, something doesn't seem right here

**Comment by rolandgeider** [comment]
one of the folder for the thumbnails was not writable by the apache process. Can you try again?

**Comment by nickycdk** [comment]
Beautiful - That seemed to do the trick ;)
