### ISSUE TITLE
Can't change password from admin account in docker container

### ISSUE THREAD

**Issue by Cutyno** [wger-project/wger#499]
After retrieving the docker container I tried to change the default password on the admin account but it didn't work. 
It says that I have to fill out all the necessary fields and even  after that requirement it didn't work.
I'm not sure if this error only concerned the docker container or if it is a issue for the whole application.
I use the wger/apache tagged official docker-image

Maybe I do something wrong. Please let me know if you need more information on this matter.

**Comment by rolandgeider** [comment]
No, it doesn't sound like you did something wrong. I'll take a look!

**Comment by rolandgeider** [comment]
Fixed in master
