### ISSUE TITLE
Persistent database on docker images

### ISSUE THREAD

**Issue by Cutyno** [wger-project/wger#500]
The default example on your docker image page shows no container to save user specific data.
Maybe you wan't to add some volume to keep user data through docker image updates.

A possibility to use a external database would also be nice.

**Comment by rolandgeider** [comment]
There's the docker-compose file for that :)

Perhaps the docs should be more specific about this.

**Comment by Cutyno** [comment]
There is?

where can I find it? I would add the description to the the README, for everybody.

**Comment by rolandgeider** [comment]
Yes! It's in wger/extras/docker/compose. It starts up a webserver for development, a (persistent) postgres DB and a cache service. If you checkout the code, you can just do a `` docker-compose -f ./extras/docker/compose/docker-compose.yml up`` from the root.

I hadn't intended for the docker images to be really production ready, more like an easier way to test a bit the application or get a development instance ready more quickly. But yeah, reworking the docs and the different READMEs is also in my TODO

**Comment by langerdennis** [comment]
I have actually achieved this by mapping a volume to  "/home/wger/db" --> therefore I can keep the sqlite between image updates. Definitely not production-ready, but does the trick for now ;-)

**Comment by rolandgeider** [comment]
There is now a repo with a docker compose file where the DB as well as the uploaded files are persisted: https://github.com/wger-project/docker

Closing here
