### ISSUE TITLE
User creation for gyms is broken

### ISSUE THREAD

**Issue by ivandir** [wger-project/wger#504]
Hi,

I'm getting an empty modal when trying to create a user within a gym with the latest commit.
<img width="1515" alt="Screen Shot 2020-08-29 at 12 35 00 PM" src="https://user-images.githubusercontent.com/2365911/91641681-16adc380-e9f4-11ea-8a38-d049467349a6.png">

**Comment by ivandir** [comment]
Above capability was tested in a docker container that was run with 

`docker run -ti --rm --name wger.devel --publish 8000:8000 wger/devel`

**Comment by rolandgeider** [comment]
Thanks for reporting this, I'll take a look as soon as I'm home

**Comment by rolandgeider** [comment]
Closed in master

**Comment by ivandir** [comment]
@rolandgeider was this issue addressed as well?

**Comment by rolandgeider** [comment]
Yes, this is fixed as well
