### ISSUE TITLE
Add option to log complete nutritional plan

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#506]
At the moment, it is possible to log all entries for a meal. It should also be possible to log the calories for all meals for a day.

This is really simple, instead of just adding the ingredients for a meal, we need to loop through all meals in a plan and add those (since this will duplicade code, a bit of refactoring will be needed as well).

**Comment by oconnelc** [comment]
If this is still open, I'd like to take a crack at it.

**Comment by oconnelc** [comment]
Is the plan to place a button on the "Nutrition plan" view to log the entire plan? If so, how does the total calories get logged? 

I see similar logic in the NutritionPlan's get_nutritional_values method; it appears that the method iterates over the meals and sums up all of the values. Is this doing what this ticket is describing or is this similar code that needs to be refactored?

**Comment by rolandgeider** [comment]
Yes it should be placed there. The calories are summed by the log and the plan, you only need to add the ingredients and units (e.g. 100g of bread, 2 slices of cheese, etc)

Take a look at

**Comment by oconnelc** [comment]
Awsome! I'll take a look at it today.

**Comment by oconnelc** [comment]
I just wanted to make sure I'm going in the right direction. I've added a link at the bottom of the plan to log the entire plan:

![image](https://user-images.githubusercontent.com/1112973/95026079-bd712980-065c-11eb-933d-459c56159473.png)

Right now it's just "Log this Plan". 

If this looks good, I'll go ahead and hook it up to the back end and push up a PR when I'm done.

**Comment by oconnelc** [comment]
I think I have what this ticket is asking for. I've included a gif screenshot of how to log an entire plan. If this is what is desired, then all I have left is to update the unit test. If there's anything else that needs to be done to complete this ticket, please let me know. 

![NutritionDemo](https://user-images.githubusercontent.com/1112973/95027764-1646bf00-0669-11eb-858f-226b20991ef8.gif)

**Comment by rolandgeider** [comment]
Nice work! You can open a PR after updating the tests

**Comment by oconnelc** [comment]
Pull request #540 is now available

**Comment by rolandgeider** [comment]
Hacktoberfest, I completely forgot about that! I'll clean up the issues a bit and add the tag
