### ISSUE TITLE
User permission-edit button is yielding an empty modal.

### ISSUE THREAD

**Issue by ivandir** [wger-project/wger#511]
When clicking the gear edit permission button for a user I get an empty modal.

This can be reproduced with the latest commit.
<img width="809" alt="Screen Shot 2020-09-04 at 11 52 01 AM" src="https://user-images.githubusercontent.com/2365911/92259487-384ff480-eea5-11ea-863a-b57fb26be15e.png">

**Comment by rolandgeider** [comment]
Thanks for reporting this! I'm guessing it's a problem with the form, I'll take a look tomorrow

**Comment by rolandgeider** [comment]
Fixed in master
