### ISSUE TITLE
Allow nutritional plan diary entries for other dates

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#520]
At the moment, the nutritional plan entries are saved for the current day, with no possibility of changing the date. It would be useful if the user could change this (but today would still be the default).

TODO: add a date + time picker (the value is a datetime in the DB) and set the current time as default. Also make sure this also works with different languages, as the dates are then formatted differently and this might get make problems with the widget

**Comment by rolandgeider** [comment]
Something to think about: the current system is very fast, just click on a link and you're done. We should not always present the user with a form with a date that he has to confirm again (another click) --> keep the one-click-links but make it obvious that you can do it otherwise?

**Comment by ImTheTom** [comment]
I'll see if I can solve this now.
