### ISSUE TITLE
Deleting the default gym crashes the application

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#539]
If the default gym is deleted, the application crashes. Either

- don't show the delete Buttons if the gym list has only one entry

- see which foreign key makes problems when there are no gyms in the DB

**Comment by aitorres** [comment]
Hello! May I take this issue? I can work on it during today and tomorrow, and submit a PR

**Comment by rolandgeider** [comment]
It's all yours :)

**Comment by aitorres** [comment]
I just did the following:

1. Downloaded and set up the repository's development environment, pulling from `master`
2. Bootstrapped the app
3. Log in as admin / admin
4. Went on to Administration > Gyms
5. Deleted the "Default gym" and confirmed the deletion
6. The gym was deleted smoothly, I didn't receive an error or crash, and now the list properly says that no gym has been found

I couldn't replicate the issue :-( let me know if I am doing something wrong or more information on how to get this error if you have

**Comment by rolandgeider** [comment]
I'll try to reproduce it and go back to you
