### ISSUE TITLE
Return image URL on muscle endpoint

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#547]
The muscle endpoint should also return the URLs for the muscle images and the backgrounds (probably the exercise endpoint as well). Needs to check whether we can access the URL when the static files are hosted on AWS or such

**Comment by rolandgeider** [comment]
To get the URL: 

```python
url = request.build_absolute_uri(static('images/path/foo/bar.svg')),
```

**Comment by rolandgeider** [comment]
A better place would a property in the model itself that returns the URL, then it can be used in the endpoint and templates e.g.

**Comment by gengkev** [comment]
Hi, I would be interested in looking at this issue!

**Comment by rolandgeider** [comment]
Hi! I have heard that @lydiaxing wanted to do this

**Comment by lydiaxing** [comment]
Hi! I'm already working on another issue so Kevin can take this one!
