### ISSUE TITLE
When editing exercises the name is lost

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#548]
When editing an exercise, the text input for the name is not filled in.

![image](https://user-images.githubusercontent.com/2280729/98530969-ef8b3200-227f-11eb-9dbd-ad72ec133a78.png)

**Comment by austin-leung** [comment]
I'd like to take a look at this! 😃

**Comment by rolandgeider** [comment]
Go on!

I saw this on the website, the local development environment seems to work fine, so if you don't find anything, don't waste too much time

**Comment by austin-leung** [comment]
I'm trying to reproduce editing an exercise on the website.

Is this the same thing as making a correction to an exercise? Or would I need admin privileges to edit an exercise?

**Comment by rolandgeider** [comment]
Yes, you need admin privileges to edit them, but the  correction form should work the same. Like I said, if you don't find anything, let's close the issue

**Comment by austin-leung** [comment]
Yep, didn't find any issue locally or in production so I think we can close this issue. 👍

**Comment by rolandgeider** [comment]
Thanks for testing this!
