### ISSUE TITLE
Improvement to ingredient form

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#550]
The ingredient form could be improved a bit by placing the carbohydrates/sugar and fat/saturated fat next to each other:

```
name
energy
carbohydrates    sugar
fat              saturated fat
[...]
```

TODO: create a crispyforms helper and add the fields to a column (would look similar to UserPreferencesForm)

**Comment by mrsid18** [comment]
@rolandgeider Hi! Can I work on this?

**Comment by rolandgeider** [comment]
Sure!

**Comment by mrsid18** [comment]
Can you navigate me to the problem, as I'm unable to find it. 
If you're talking about the Nutritional Data table, I think it is intended to be that way so as to know the amount of sugar in carbs. If not then guide me.
![Screenshot_2020-11-18 Nutrition plan](https://user-images.githubusercontent.com/23372739/99487414-4d103480-298c-11eb-9600-87a06e710ef1.png)

**Comment by rolandgeider** [comment]
I meant the form for adding or editing new ingredients


![Screenshot_20201118-101203](https://user-images.githubusercontent.com/2280729/99509850-9eb5c080-2986-11eb-8c3e-1357bc51b0d0.jpg)

**Comment by harlenesamra** [comment]
My team will work on this thank you!
