### ISSUE TITLE
Check name similarity when adding exercises

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#551]
When adding exercises, we should check if there is already an existing one with a similar name, e.g. with the Levenshtein distance between it and the names already in the database. 

Ideally, we would show the possible matches and ask the user if he really wants to continue, but it's ok to just show an error for now.

TODO: update the exercise model's name_clean() and show an error message. We would need to experiment a bit on what distance is appropriate. Perhaps 4 oder so? Important: check only against other exercises with the same language

**Comment by lydiaxing** [comment]
Hi, I'd like to work on this!

**Comment by rolandgeider** [comment]
Hi there! It's all yours :)
