### ISSUE TITLE
Fix uneven width of exercise images on overview

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#554]
The width of the image on the overviews should be the same for all exercises:

![image](https://user-images.githubusercontent.com/2280729/99917427-7fb18880-2d10-11eb-8f1c-a7ba03dc5741.png)

**Comment by sandilsranasinghe** [comment]
Hi! I'm new and looking to contribute to projects. Can I work on this?

**Comment by rolandgeider** [comment]
Sure, go ahead!

**Comment by sandilsranasinghe** [comment]
thanks. 
Should the height of the image be the same for all exercises too?

**Comment by rolandgeider** [comment]
I'd say the width
