### ISSUE TITLE
Group exercise variations

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#555]
For a lot of exercises, there are different variations (wide grip, narrow grip, reverse, etc. etc.). It would be nice if this could be modelled and presented to the user.

We would basically only need a new many-to-many table, linking all the exercises together, most of the work here would be to go through the DB and actually group them together. Perhaps some text similarity script could help

**Comment by ryowright** [comment]
Hello, this would be my first open-source contribution ever and I would definitely like to try and resolve this issue.

**Comment by rolandgeider** [comment]
That's great! If you have any questions or problems setting up the application, just ping me or write in the discord server

**Comment by rolandgeider** [comment]
You just got your first ever contribution merged, congratulations 🥳

**Comment by ryowright** [comment]
Thanks so much! This was a lot of fun to do.
