### ISSUE TITLE
Prettify the autocompleter

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#556]
The autocompleter should get a bit of design love

![image](https://user-images.githubusercontent.com/2280729/99918315-54319c80-2d16-11eb-91d7-a60335e31bbb.png)

**Comment by ryowright** [comment]
Hi @rolandgeider. I can work on this one.

**Comment by rolandgeider** [comment]
It's all yours

**Comment by logan-bobo** [comment]
@rolandgeider Looks like an interesting first issue for me to pick up.

**Comment by rolandgeider** [comment]
Hi @logan-bobo ! Thanks for the interest, but this issue is no longer relevant, we're re-implementing the exercise pages with react and using a better autocompleter (I guess I should take some time and cleanup the issues 😅 ):

![image](https://user-images.githubusercontent.com/2280729/185589713-077176b9-ebf7-4c91-8e09-8a56b790f6d7.png)

What kind of issues were you interested in doing?
