### ISSUE TITLE
Add kilojoule values to ingredient

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#568]
While the ingredients store the energy in kcal, it would be nice to also show the value in kilojoule. This can be accomplished easily with a property in the ingredient model.

1 kcal are 4,184 kJ

**Comment by rolandgeider** [comment]
Hi! Sure, go ahead

**Comment by nopinter** [comment]
Hi, my partner, @derekli17, and I are also looking into this!

**Comment by JuanFML** [comment]
Hi! Sure go ahead I am a little bit stuck with creating the property in _wger\nutrition\views\ingredient.py_, although I got to edit the view in _\wger\nutrition\templates\ingredient\view.html_
