### ISSUE TITLE
Allow users to upload pictures of themselves

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#572]
Users should be able to upload picutures to better track their progress. Along with the current date, a short (optional) description is probably useful.

Other things to consider are the security/privacy implications for this. It is probably better to let django check the logged in user and serve these files, even if it is a bit less efficient than letting the webserver do it like with all other static files.

**Comment by klu17** [comment]
@rolandgeider I would be interested in working on this. Does a similar feature currently exist? What does implementing this entail?

**Comment by rolandgeider** [comment]
This would actually be really useful to have!

In a first step users should just be able to upload pictures that would be shown in a gallery. Since we have a date we can later do some other useful things such as perhaps present this information on the weight graph or such. We already allow to upload pictures for the exercises, so that part would be the same.

And for the privacy implications, giving the image a UUID as the filename would prevent people without this information from accessing it and I would say is probably secure enough (I know, I know, it wouldn't really "prevent" it, just make it highly unlikely to access it). That's why part of implementing this would be to research a bit what possibilites there are or what other people recommend using.

**Comment by klu17** [comment]
Ok. I can work on this one.
