### ISSUE TITLE
category for back squat is incorrect

### ISSUE THREAD

**Issue by ryanwtyler** [wger-project/wger#576]
in the exerciseInfo endpoint.  should be {id: 9, name: Legs}  i don't know how many places you have to update that.  At least in exercise and exerciseInfo

```
 "id": 637,
            "name": "Back Squat",
            "uuid": "0fd6154d-fb53-4b24-acc0-1c5c05b57ebc",
            "category": {
                "id": 8,
                "name": "Arms"
            },
```

**Comment by rolandgeider** [comment]
That was obviously wrong :) Thanks for reporting this, it's fixed now
