### ISSUE TITLE
Show nutritrional values per meal

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#581]
At the moment, we present the values for the individual ingredients, which is probably not _that_ interesting. It would be better to show the values for each meal and make the ones for the ingredients less prominet by giving it the CSS class text-muted or such.

![image](https://user-images.githubusercontent.com/2280729/102079168-79449700-3e0c-11eb-8421-ddd90563d65e.png)

**Comment by nopinter** [comment]
@derekli17 and I will do this!
