### ISSUE TITLE
How can i help to translate it to spanish?

### ISSUE THREAD

**Issue by javix64** [wger-project/wger#586]
Hello wger-project team.
I'm interested in translate it to spanish language. It's partially translated, but i can help to translate it. Every help is good.

**Comment by rolandgeider** [comment]
Hi there! The strings are translated on transited

https://www.transifex.com/rge/wger-workout-manager/

**Comment by rolandgeider** [comment]
(had closed this before I finished writing the answer)

**Comment by rolandgeider** [comment]
Also, Ii's not very obvious, but you can click on the thunderbolt icon and the text will be automatically translated with google translate. It's often rubbish, but it saves time :)

**Comment by javix64** [comment]
ey @rolandgeider i was watching transifex, and there is 695 words without revission, 
i added two: "by category" and a long string , but i'm still watching it in english.

**Comment by rolandgeider** [comment]
Yes, I still have to manually copy the translations and update the server. When I have time I'll try to automate this

**Comment by javix64** [comment]
Okay that's fine. Thanks for your time @rolandgeider ! have a good day!
