### ISSUE TITLE
Allow specifying styles for images

### ISSUE THREAD

**Issue by 12people** [wger-project/wger#589]
I would love for Wger to become the central database that all FOSS projects pull workout information from. However, workout apps tend to use very different art styles — wger itself uses line art, [openWorkout](https://github.com/oliexdev/openWorkout) uses 3D animation, [Feeel](https://gitlab.com/enjoyingfoss/feeel) uses low-poly images.

It'd be great if volunteers could upload graphics in any of these styles and annotate their uploads so that developers could choose which style of illustration to display in their apps.

To achieve this, here's my rough idea of two attributes that could be added for the _exerciseimage_ type:

**Style** — an enum that could have these values:

- line art
- 3D
- low-poly
- photo
- other

**Animated** — a boolean specifying whether the image is static or animated (somewhat related to #289)

As for the **style** attribute, the idea is that more styles could be potentially added depending on the needs of the projects using wger. Aside from the styles used by the FOSS projects listed above, I also propose adding a "photo" style, as photos are arguably the easiest for volunteers to submit and can serve as a starting point for both line art and especially low-poly illustrations.

**Comment by rolandgeider** [comment]
Hi! This is actually a nice idea that would not require many changes in the DB. I should have code somewhere to allow for users to submit images, must check on that.

**Comment by vinayassrao** [comment]
I would like to work on this issue.Can anyone guide me...

**Comment by rolandgeider** [comment]
Sure! We need a new field "style" on `ExerciseImage`. Since we only allow only the values above, we need to pass them to the `choices` attribute (take a look e.g. at the gender field in the user profile). We also need to expose the value to the API, but that's just adding the new field to the list in `ExerciseImageSerializer`

**Comment by LucasSD** [comment]
> Sure! We need a new field "style" on `ExerciseImage`. Since we only allow only the values above, we need to pass them to the `choices` attribute (take a look e.g. at the gender field in the user profile). We also need to expose the value to the API, but that's just adding the new field to the list in `ExerciseImageSerializer`

Hi @rolandgeider and @12people . I've configured my dev environment and it's all working and 1211 tests pass and one is skipped. I can get this issue solved and add tests. Please can you assign it to me? Thanks :)

**Comment by rolandgeider** [comment]
All yours!

**Comment by LucasSD** [comment]
> All yours!

Thank you!

**Comment by LucasSD** [comment]
Hi @rolandgeider. Please can you let me know your preferred blank, null and default field options for the new style field?

**Comment by rolandgeider** [comment]
The current pictures are only line art, so that should be the default in the migrations. As for new submitted ones, I would say "photo"

**Comment by LucasSD** [comment]
Cool, I've opened a PR :)
