### ISSUE TITLE
Remove CC BY-NC-ND as a license option

### ISSUE THREAD

**Issue by 12people** [wger-project/wger#590]
Unlike the other license options provided for exercises, the CC BY-NC-ND is a [proprietary license](https://en.wikipedia.org/wiki/Creative_Commons_license#Seven_regularly_used_licenses). Given that there's a move to [consolidate exercise data](https://github.com/wger-project/wger/issues/448), I'm concerned about this license for a few reasons:

1. A translation under the BY-NC-ND license could prevent others from contributing a translation under an open license (if translations are restricted to one per language).
2. Contributions licensed this way would be unusable for projects that don't allow proprietary licenses (e.g. Wikipedia) and commercial open-source projects. Depending on how it's included in source files, it might not even be usable in [GPL-licensed projects](https://opensource.stackexchange.com/questions/6253/can-a-video-game-have-a-gpl-licensed-engine-and-gpl-incompatible-licensed-assets).
3. The license prevents corrections or adjustments from being made. That both annoys contributors who can't correct mistakes and also requires a special mode for content under this license that prohibits editing.
4. Since the license prevents derivatives, they prevent changes to the exercise structure like #448 (unless each attribute was licensed separately). Whenever the structure would change, all ND licensed content would have to be removed or be maintained under the old structure.

I would therefore propose that this license is removed as a license option, especially since #448 will require getting rid of or relicensing current BY-NC-ND content anyway (which I only realized while researching this).

Is there a reason why it was included originally?

**Comment by rolandgeider** [comment]
Good catch, you are right. I also just checked and there are neither ingredients nor exercises under that license, so removing it is easy

**Comment by rolandgeider** [comment]
Removed
