### ISSUE TITLE
Add UI for uploading exercise images

### ISSUE THREAD

**Issue by 12people** [wger-project/wger#599]
Looking at the Wger web interface at wger.de, there is a way to add and edit exercises, but not a way for users to upload images corresponding to those exercises.

It'd be great if users could upload images right from the web GUI.

**Comment by rolandgeider** [comment]
Definitely. This and the other colaboration focused issues will be (one of) the focus for the next release

**Comment by sophialr** [comment]
working on this with @emuth

**Comment by rolandgeider** [comment]
To clarify, there is currently a UI to upload images to exercises, but only for administrators. Regular users should be able to do this as well. To avoid spam, there needs to be a process before the images go "live". At the moment an administrator needs to manually OK every submitted exercise and does not scale. We could add a flag to the user profile to indicate whether the user is more trustworthy, e.g. after successfully having submitted an exercise or if the account is older than X days

**Comment by emmaamuth** [comment]
@rolandgeider thank you for the clarifications! So are you thinking then if the user isn't "trustworthy" yet then that process of an admin manually OK-ing the image should still apply? Any preference on how many days before an account is considered "old enough"?

**Comment by rolandgeider** [comment]
yes exactly.

And for the preferences, I would say 3 weeks? In order to allow for more flexibility we could add a property to the preferences model, that way we can add other checks in the future (such as "already submitted an exercise"). I'm thinking about something along the lines of


```python
@property
def is_trustworthy(self):
    joined_days_ago = datetime.today() - self.user.date_joined
    return joined_days_ago > 21
```

**Comment by emmaamuth** [comment]
@rolandgeider perfect, that all makes sense. Thank you again!
