### ISSUE TITLE
"DoesNotExist at /en/software/features" on startup

### ISSUE THREAD

**Issue by serge1peshcoff** [wger-project/wger#602]
I've started the app with docker-compose, then got this: 
![image](https://user-images.githubusercontent.com/1060257/106468135-9a417400-64ae-11eb-9af1-da51e6a679fd.png)

Not sure what is this related to, how can I fix this?

Thanks in advance!

**Comment by rolandgeider** [comment]
It seems the languages (and probably other things as well) didn't get saved to the DB. You can either delete the DB and start the container again or exec into web and do wger bootstrap.

But this looks like a build problem, I'll take a look

**Comment by serge1peshcoff** [comment]
Removing the DB indeed worked, thanks!
