### ISSUE TITLE
Save button on /workout/day/{id}/log/add/ is always in German

### ISSUE THREAD

**Issue by qagoose** [wger-project/wger#609]
### Summary
Text on the site is usually translated into the language the user is viewing the site in, but the "Save" button on the "New weight log" page is always displayed in German (Speichern).

### Recreation steps

**Given** I am logged in (any user should work, whether User or Admin etc)
**And** my selected language is anything except Deutsch (e.g. English)
**And** I have created a workout
**And** I am on the dashboard page (/dashboard)

**When** I click the 'Add new log' button
**And** I click a day to add the log to

**Then** the form that loads should be translated into my currently selected language (English)
**Instead** the "Save" button at the bottom of the page is in German, and displays as "Speichern"

![untranslated](https://user-images.githubusercontent.com/38165285/109395577-f91ad180-7924-11eb-98a9-d69db67e601e.png)

**Comment by rolandgeider** [comment]
Good catch!
