### ISSUE TITLE
"Number of sets" slider often adds the wrong number of rows to the form

### ISSUE THREAD

**Issue by qagoose** [wger-project/wger#610]
### Summary
The "Number of sets" input on the "Add exercises" form is styled to look like a slider.  This encourages users to hold down the "handle" of the slider, and move it to the position they wish to set.

If the slider is used in this way, the number of sets that are added to the form becomes unpredictable.  E.g. setting to 9 sets, and then down to 1 set will often show 5 or 6 sets rather than 1.

### Recreation steps

**Given** I am logged in as a User
**And** I am viewing a workout /workout/{id}/view/

**When** I click "Add exercises to this workout day"
**And** I search for and add an Exercise, e.g. Barbell Ab Rollout
**And** I click and drag the "Number of sets" control to a higher value e.g. 8
**And** I click and drag the "Number of sets" control back to a lower value e.g. 2

**Then** it should always show the correct number of set rows.
**Instead** there is often more set rows than there should be. 

**Note**: you can see this consistently if you click the handle and just "shake" the value between 2 extremes.  The javascript struggles to keep up with the alterations it is being told to make to the page.

Occurs on Chrome 88 (Windows 10) and Firefox 85 (Windows 10).  Likely to occur on other browser/OS combinations too, these are just the two I have immediate access to.

If the video isn't working, use the seek bar to go a few seconds into it, and it seems to work after that.  Not sure why!

https://user-images.githubusercontent.com/38165285/109400107-a77f4080-793e-11eb-807d-ae0cfffffde3.mp4

**Comment by qagoose** [comment]
So the issue here is probably going to be that changes to the set rows are occurring on `input` https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

This means code associated with this event is triggered each time the value of the slider changes.  Moving from value 1-9 is triggering multiple events.  The code updating the form rows is using an async call to an API, and I think those calls are not guaranteed to be responded to in the order they are made, hence sometimes the number of form rows is wrong.

I think a reasonable solution would be to only update the text (`Number of sets: X`) on `input` and to update the actual set rows on `mouseup`, so that the form rows are only updated once.

**Comment by rolandgeider** [comment]
Nice report! And that sounds indeed like an easy solution/workaround for this bug. In general I would like to replace this page with a modern JS framework, but that will have to wait a bit

**Comment by qagoose** [comment]
Thanks!

I had a go at altering this to what I suggested above, but noticed that it excluded people from using the keyboard to interact with the slider.  While there probably aren't that many people using the keyboard, I wouldn't be happy introducing accessibility issues.

I'll try debouncing this instead, so the "set rows" only update after the user has settled on a value for ~250 millis.  This will add a slight delay, but I think that's better than this bug existing.

**Comment by rolandgeider** [comment]
Uff you are right. I honestly haven't tested much how  accessible the application is with only a keyboard, but that doesn't mean we shouldn't care about it. If your solution works, open a PR
