### ISSUE TITLE
Correcting an Exercise

### ISSUE THREAD

**Issue by AManNamedGaurav** [wger-project/wger#615]
![image](https://user-images.githubusercontent.com/39320731/109572123-51330e80-7ab2-11eb-84b3-18b8f8d00702.png)

I could not submit a correction to the exercise "Jumping Jacks". It currently belongs to no category. I tried to change it to "none/bodyweight" but received this error

**Comment by rolandgeider** [comment]
That is the logic to prevent duplicate exercises, it seems it's blocking the corrections as well. Thanks for reporting this, I'll correct the exercise as well

**Comment by AManNamedGaurav** [comment]
You're welcome. Happy to help.
