### ISSUE TITLE
default username and password not working

### ISSUE THREAD

**Issue by tomasrojasc** [wger-project/wger#624]
Hi, I followed the install guide in the docs and for some reason I cannot login as admin like suggested. Any ideas?

**Comment by rolandgeider** [comment]
Hi! What password did you try, "adminadmin"? You can reset the pw in the command line with `python3 manage.py rchangepassword admin`, but it's still strange that it didn't work.

**Comment by rolandgeider** [comment]
Ahhh, you probably followed the docs at readthedocs, I just noticed that the old default password was mentioned there. Just fixed it.

Optimistically closing this issue, if that wasn't the case, feel free to reopen

**Comment by tomasrojasc** [comment]
Yep, that worked. Thanks!
