### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [wger-project/wger#628]
I am thinking https://hosted.weblate.org/projects/wger/#information should be
AGPLv3+ and not GPLv3+.

**Comment by rolandgeider** [comment]
The mobile app is GPL, the web one AGPL since it is a web service

**Comment by comradekingu** [comment]
Isn't the server component to be AGPLV3+?
In any event, why not make everything AGPLv3+ to not have any issues?

**Comment by rolandgeider** [comment]
yeah, the server component is AGPL+. I'm not sure if it would make any difference for the flutter app, since the only difference with regular GPL is when the software is accessed over a network (there probably are other subtleties)

**Comment by comradekingu** [comment]
There are more differences with AGPL3, but that is beside the point.
To consider just the practicality and the for sure legal way to do things, is there anything wrong with doing everything AGPLv3+?

**Comment by rolandgeider** [comment]
Not really, I just didn't want to use a license that too "network" focused or (possibly) proves somehow impractical when the software is not a service. Other than that I would have no problems changing it

**Comment by comradekingu** [comment]
The network part is just a provision for ~if you do the exact same thing in a network.
It would have been in GPLv3+ if they had the foresight to put it in there.
The practicality of using one license is IMO. better because it is just one set of rules, and not part of the "does this part also concern the strong copyleft" flowchart/considerations.

**Comment by 12people** [comment]
It's also worth noting that, since Flutter allows building for the web, the Flutter-based app could potentially be made to run server-side with relative ease. IMHO, the AGPL seems like a safer license to use for Flutter projects too.

**Comment by rolandgeider** [comment]
I hadn't thought of that. Even if we don't plan on using it ourselves, we should close that loophole. I'm closing here and moving the conversation to the issue on the flutter repo
