### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by stefanorossiti** [wger-project/wger#632]
## Use case

Enable the italian language,

I finished translating the remaining strings and italian is now 100% translated on transiflex.

## Proposal

I never worked with django and i have no idea how to implement it myself. But i gave a look at the project and if i have understood correctly django needs a .mo file that is a binary file. 
I rapidly checked at the django doc for instruction on how to generate this file but i found nothing.
If you tells me how to do it (i have the .po file from transiflex) i can do it myself.
I am native in Italian so i can test it and later send a pull request once its fine.

**Comment by rolandgeider** [comment]
Awesome! I will copy the translation from transifex into the project and compile it (this process will be automated in the future). I will try to update the website next week so you can take a look

**Comment by stefanorossiti** [comment]
Would be great. Thank you. I'll wait.
