### ISSUE TITLE
Found many harcoded strings

### ISSUE THREAD

**Issue by stefanorossiti** [wger-project/wger#635]
I found many hard coded string. This strings wont be translated and will then stay in english.

Overall all input fields' error strings and tool tips are hard coded in english. It is possible that there is a localization script to install for the library used.

To avoid writing too much i just screened everything i found.

![Screenshot from 2021-03-18 23-02-03](https://user-images.githubusercontent.com/25284995/111707424-50d19c00-8844-11eb-85a2-e2674a8b8e4a.png)
![Screenshot from 2021-03-18 23-10-44](https://user-images.githubusercontent.com/25284995/111707428-5202c900-8844-11eb-89d2-cbd66c418c3b.png)
![Screenshot from 2021-03-18 23-20-17](https://user-images.githubusercontent.com/25284995/111707431-529b5f80-8844-11eb-9963-ceb1e3b1f437.png)
![Screenshot from 2021-03-18 23-28-39](https://user-images.githubusercontent.com/25284995/111707433-529b5f80-8844-11eb-8633-3f662b38d588.png)
![Screenshot from 2021-03-18 23-33-19](https://user-images.githubusercontent.com/25284995/111707436-5333f600-8844-11eb-95bd-2234b36a05df.png)
![Screenshot from 2021-03-18 23-38-31](https://user-images.githubusercontent.com/25284995/111707438-53cc8c80-8844-11eb-99cb-b3e80eddf8f9.png)

**Comment by rolandgeider** [comment]
Some of those might come from javascript, which is currently is not translated, but I'll check the rest
