### ISSUE TITLE
Centrally managed workout plans / templates

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#639]
## Use case

Gym trainers need to create individual workout plans for every member, even if they are the same.

## Proposal

It would be useful if there could be centrally managed workout routines that the trainers could assign to the members. Additionally, there could be app-wide plans that all users could just use. These plans would need to have some setting controlling whether the user could edit the plan once copied or not

**Comment by stefanorossiti** [comment]
i though the same, having to recreate a workout for each use is a very slow workflow. 
i dont know how much work is needed to change to a many-to-many relation.

An alternative would be to implement a template system.
Would be nice to extend this future at the nutrition plan too.

**Comment by rolandgeider** [comment]
the problem will be changing the ownership, at the moment all the workout plans must have a user as the owner. We will need to change that to allow for "system" plans that are common and everybody can access and possibly add a flag indicating that those are templates (while we're at it, users should be able to have their own list of templates)

**Comment by Wartz** [comment]
This feature would be a huge quality of life upgrade for me.

**Comment by stefanorossiti** [comment]
> the problem will be changing the ownersh

What about using a "templates" user. wich is not a real usable user. But all wokout assigned at this user are actually templates for a workout. when someone select a template, it will be cloned as workout with user's ownership.

Could be created a page to list all template. 

Could also be added a column to define a "public domain" to let certain templates to be assigned and visble only to certaines gyms or users.

Could even add tags to better filter a search query.

Only general managers and template's creators should be able to modify a template.

**Comment by rolandgeider** [comment]
That would be possible, but it's a bit of a dirty solution, we'll change the model 😄

But the idea that the user can define a template as "public" is nice, then others could benefit from it as well (perhaps only for accounts older than 15 days or something to avoid spam?)

**Comment by rolandgeider** [comment]
To summarize, there should be template workouts for
* the system (visible to all users)
* the user's gym (visible to members of that gym)
* the user (either private or, at the users choice, visible to other users)

Templates are created like regular workouts, but they don't have logs, can't start the gym mode (in the app), etc. They are really just a template.

After selecting a template, it would be copied over to the user where it would behave like a regular workout plan does now. We could potentially add a flag indicating that the workout is "locked" and could not be changed, but I'm not sure if that would be useful.

**Comment by rolandgeider** [comment]
Note: the first version only has user templates, still need to think about how to integrate this in the gym module. "System" templates can simply be saved by the admin user.


* Chnages to workout model:
  - new field template (bool)
  - new field public (bool)

* Add custom manager to workout table, e.g. "templates". It returns all workouts that have the flag template and are either public or belong to that user. The default manager should only return "regular" workouts. https://docs.djangoproject.com/en/3.2/topics/db/managers/

* Allow user to mark a workout as a template, alternatively as a public template (other users can use it). A template can't be edited anymore

* Add template overview. At the moment a list with date, name and description is enough, no search, etc.

* When the user clicks on a template, show a read-only view (do we need a property in the model?) with a "use this template" button, it will then be copied over (there is already a copy method, should have the required functionality, but perhaps this could be better moved to the model?)

* Should there be a new endpoint in the API for templates or do we just filter the workout one? Possibly add a new read-only template endpoind. Also, we need to trigger a "copy" over the API.

**Comment by rolandgeider** [comment]
This is basically 90% done, just needs a bit of polishing, help texts, etc.
