### ISSUE TITLE
More flexible logs

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#64]
When adding a log, either in the log view or in the gym view, it should be possible to exchange one exercise with another. This can be useful e.g. when a machine is occupied or the user can't do the planed exercise for other reasons.

**Comment by rolandgeider** [comment]
From user feedback: it should be possible to skip exercises. This makes sense, it should be possible to quickly navigate to a specific exercise (or skip it, etc.)

**Comment by rolandgeider** [comment]
Add explicit "on the fly workout" option, so that there are no initial exercises and the user can select on each step what they want to do

**Comment by rolandgeider** [comment]
Other ideas:

* Show the exercise images, if any.
* Show the exercise description and tips
* When selecting the repetitions, use a dropdown, not an input field, this is faster in mobile devices
* Even better, since the user has probably already done that specific exercise weight-repetions combination, the page could present somehow the last ones, when the user selects one, both the repetitions and the weight are filled in.

**Comment by rolandgeider** [comment]
Adding the needs dicussion tag, since it's not clear (to me) exactly how some of these ideas could actually look like (if they are useful at all)

**Comment by rolandgeider** [comment]
From a user request: should the timer page reload for whatever reason (this can happen more easily on the mobile version), it should be possible to resume the session.

**Comment by dometto** [comment]
> Add explicit "on the fly workout" option, so that there are no initial exercises and the user can select on each step what they want to do

:+1:

Other apps (like thesquatrack.com) also allow adding exercises to a day that are not coupled to a routine, "workout day", or whatever. This is essential to some users. I haven't looked at the code yet, but I would be interested in contributing to this if it wouldn't require a complete rewrite of the app. :)

**Comment by rolandgeider** [comment]
hi @dometto !

I know, there have been many days where I wish I could do this! The positive side is that it's not necessary to rewrite the whole application, the backend can already support this, what's needed is to make the frontend more flexible. If you want the technical details: currently the gym mode is made with jquery, we plan to add angularJS to the application to allow for more dynamic pages (starting with #284, but this issue would be the second thing to attack). It wouldn't make much sense to add now the flexible logs and then rewrite everything and re-implement it again. If you are fit with angular you'd be more than welcome to contribute, @illegalnumbers is on board as well

**Comment by dometto** [comment]
It's been a while but am interested in using wger again -- what is the general status of the project, and of this issue (and the angular implementation) in specific?

**Comment by dometto** [comment]
Was this feature introduced, and can I test it anywhere?

**Comment by rolandgeider** [comment]
Not yet, this is tracked in #1066 which we will try to do for the next version
