### ISSUE TITLE
Query params not working properly?

### ISSUE THREAD

**Issue by travismoulton** [wger-project/wger#642]
## Steps to Reproduce

Hi,
Has anyone else run into querying the API to search for exercises by category not working properly this morning? All query params besides language seem to be ignored.

https://wger.de/api/v2/exercise/?muscles=1&equipment=3 returns all workouts
https://wger.de/api/v2/exercise/?id=345 returns all workouts
https://wger.de/api/v2/exercise/?language=2 only returns workouts in English
https://wger.de/api/v2/exercise/?language=2&category=10 returns all workouts in English 

Thanks everyone, btw this API is great!

**Comment by rolandgeider** [comment]
You're right, something is seems wrong, I'll take a look

**Comment by rolandgeider** [comment]
Fixed in master, will update the website shortly.

And as a special present, you can now do ``?category=1,2`` and it will search for exercises in categories 1 OR 2

**Comment by travismoulton** [comment]
Thanks!
