### ISSUE TITLE
Cannot set sender address for emails, which is disallowed by my email provider

### ISSUE THREAD

**Issue by irate-badger** [wger-project/wger#650]
## Steps to Reproduce

Tested with RESET PASSWORD functionality in stock Docker image

1. Use an email provider that requires a valid from address to send. I used Gandi for this.
2. On home page, select "FORGOT PASSWORD"
3. Wait for request to fail and 504 error to be displayed.

**Expected results:**

An email sent to me, and a success message on the page

**Actual results:**
504 page is displayed.

The stack trace displayed on the page is below.

<details>
  <summary>Logs</summary>

SMTPRecipientsRefused at /en/user/password/reset/
Request Method: | POST
-- | --
http://wger.my-domain.uk/en/user/password/reset/
3.1.8
SMTPRecipientsRefused
{'mail@email.me': (504, b'5.5.2 <webmaster@localhost>: Sender address rejected: need fully-qualified address')}
/usr/lib/python3.8/smtplib.py, line 885, in sendmail
/usr/bin/python3
3.8.5
['/usr/local/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/dist-packages',  '/home/wger/src',  '/usr/lib/python3/dist-packages']
Mon, 12 Apr 2021 08:48:10 +0100
</details>

Have set the following environment variables in the prod.env file without success.
FROM_EMAIL - As per Discord
EMAIL_FROM - As per `python3 manage.py diffsettings |grep EMAIL` and seeing an `EMAIL_FROM` field
DEFAULT_FROM_EMAIL - As per Django https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-DEFAULT_FROM_EMAIL

**Comment by rolandgeider** [comment]
TODO: check that everywhere where we send emails, the FROM address is correctly set (and document how to set it)

**Comment by rolandgeider** [comment]
This should be fixed in master but currently there's a problem with our github actions for docker and no new images can be built
