### ISSUE TITLE
Use postgres' full text search

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#652]
## Use case

Get better results for exercises and specially ingredients with full text search

## Proposal

If using postgres, we should use its full text search capabilities so that we get better results and smooth out typos (search in `exercises.api.views` and `nutrition.api.views`). A short check of the connection engine should make easy to use the current filter if that's not the case. We should also document how to add an index to the db.

https://docs.djangoproject.com/en/3.2/ref/contrib/postgres/search/

```python
from django.db import connection
if 'postgres' in connection.settings_dict['ENGINE']:
    ...
else:
    ...
```

**Comment by rolandgeider** [comment]
While the docker images and the docs use postgres, I wouldn't want to make it the only option (and e.g. during development I only use sqlite as it is very easy to work with). Does django support writing backend specific migrations? That would be probably the easiest

**Comment by Alig1493** [comment]
Not sure about backend specific migrations but django does have post migration [signals](https://docs.djangoproject.com/en/3.0/ref/signals/#post-migrate) as far as I know. So based on this signal we can check the db type and run our own custom migrations. better yet add our own migration files which run some aspect of the code if it has a specific db backend type.

**Comment by rolandgeider** [comment]
I've looked around a bit and found... little, but I think it's possible to detect, e.g. this answer on [stackoverflow](https://stackoverflow.com/questions/32384547/django-migration-runsql-conditional-on-database-type) or we could probably do something [like this](https://docs.djangoproject.com/en/3.2/ref/migration-operations/#writing-your-own) and filter out non-postgres dbs

**Comment by rolandgeider** [comment]
https://pganalyze.com/blog/full-text-search-django-postgres

**Comment by rolandgeider** [comment]
Some prototyping can be found in the branch `feature/pg-fulltext-search`

**Comment by uzza1hossain** [comment]
Is anyone working on this issue? If not, I want to work on it.

**Comment by rolandgeider** [comment]
Sure @uzza1hossain , go ahead

**Comment by vbsh123** [comment]
Hey, whats the status?
if its open i can give it a try

**Comment by rolandgeider** [comment]
Hi @vbsh123 I don't think much has happened since then. If you want to try, go ahead, this would be really useful!

**Comment by eriklolson** [comment]
Hi, I would love to work on this issue. This would be my first as a contributor dev. I've had some experience working with PostgreSQL on the back-end of web apps. I look forward to giving it a shot, if that's alright.

**Comment by rolandgeider** [comment]
@eriklolson it's yours

**Comment by rolandgeider** [comment]
@eriklolson Hi! Any news? :)

**Comment by eriklolson** [comment]
@rolandgeider Hi there! As a relative newbie to Django I've been doing some tutorials to familiarize myself with the ins and outs of the framework. I focused on those that use Postgres database. I've also read the Postgres full text search documentation and that for Django. I'm now nearly finished with a full text search tutorial. After this, I will be fully prepared to tackle this issue in a more effective manner.

 I should also mention I was able to rebase the master thread onto the Postgres branch, after resolving some conflicts. I did this because the Postgres branch was very behind the master.

**Comment by rolandgeider** [comment]
awesome! If I can assist you in any way, just ping me

I also wanted to mention that a rebase would be needed, but you already did that :)

**Comment by rolandgeider** [comment]
There is a PR that simply uses a trigram search, which seems to return better results for our use case such as simple typos, different spellings (pullup / pull-up / pull up).

For posterity, there is this mostly working code for the "real thing" will full text search in this commit: https://github.com/wger-project/wger/pull/1594/commits/8b0e3870a37754ea2229853a83c64d1a67dab1ab
