### ISSUE TITLE
Add images to ingredients

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#653]
Add images to ingredients

**Comment by rolandgeider** [comment]
Implementing images has been started in this branch: https://github.com/wger-project/wger/tree/feature/ingredient-images

**Comment by rolandgeider** [comment]
There is already working code that fetches the images from Open Food Facts and saves them to the local database (`get_image` in the ingredient model). This is fine for nutritional plans or such since after the first fetch the images are known locally, but when using the autocompleter this process can take a lot of time since we need to perform two request per ingredient. What needs to be done:

- return the local image for the autocompleter
- add a management command that iterates over all ingredients that are currently used in a nutritional plan and accesses the get_image property so that those are downloaded initially

**Comment by rolandgeider** [comment]
Hi! Sure, it's yours. Yes, exactly, we can access the image in the model and return that if it exists

**Comment by rolandgeider** [comment]
Backend is done, we just need to show the images in the autocompleter

**Comment by ImTheTom** [comment]
I can see if I can the autocompleter soon.

**Comment by ImTheTom** [comment]
Unless you wanted to finish it off @olijzenga

**Comment by rolandgeider** [comment]
Note that this is not merged yet because we still need to think about performance issues.

Ideally we would download all images that have been used somewhere, so e.g. ingredients that are used in meals or logged to the diary, for this we will need to make sure this also works when using the rest api, since more and more parts of the application will be using it. I would also prefer to use something like celery (which we will need anyway if we implement data synchronization for other fitness services) so that this can happen in the background

**Comment by aryandgandhi** [comment]
Hey @rolandgeider I'd like to work on this if it's still open, also reading through some of the comments, I'd like to implement a button below [no workouts found] which some pre-made workouts. Let me know what issues are good for first timers and that you still need help with.

**Comment by rolandgeider** [comment]
hi @aryandgandhi ! This issue is almost done, just need to do some polishing and tweak a bit how we store license information. 

Any of the issues in the milestone [for version 2.2](https://github.com/wger-project/wger/milestone/11) would be very useful. Perhaps something like 817, 1003 or 1012?
