### ISSUE TITLE
Allow for easier translation of exercises

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#654]
## Use case

Allow for easier translation of exercises

## Proposal

After successfully splitting common exercise data such as equipment or category (ExerciseBase model) and translatable content such as name or description (Exercise model), we need a GUI to finally take advange of it.

**Comment by rolandgeider** [comment]
Perhaps even do this in weblate? We would need some process to keep the data in sync but that should be doable. How did you do it with your exercises @12people ?

**Comment by 12people** [comment]
I am using Weblate for this. My exercise translations used to be AGPLv3 licensed and translated along with UI strings, but I've recently asked contributors to relicense them to CC BY-SA 4.0 and split the translations up into their own [Weblate subproject](https://hosted.weblate.org/projects/feeel/exercises/).

However, I'm not sure this would be appropriate for wger, both from a UX and a licensing perspective:

**Licensing**

Right now, wger allows choosing from these licenses for exercises: two versions of CC BY-SA (3.0 and 4.0), CC BY, CC0, and ODbL. Both ODbL and CC BY-SA require derivative works to use the same license or a newer version of such. And it seems like [ODbL is incompatible with CC BY-SA](https://wiki.osmfoundation.org/wiki/Licence/Licence_Compatibility#Licences_that_are_not_compatible_with_the_.22Produced_Work.22_concept_of_the_ODbL).

AFAIK, Weblate only allows one license per subproject, though you can make as many subprojects as you'd like. If you decided to use Weblate, you'd need to separate exercise translations into at least two subprojects — CC BY SA 4.0-licensed translations (which could cover translations of strings under all of the allowed CC licenses) and ODbL-licensed translations. Do note that this would lead to an exercise contributed under a CC0 license having all translations under a CC BY-SA license.

Alternatively, you could have 5 subprojects for each of the allowed licenses, where translations would respect the original contribution's translation. Still, even this approach seems relatively chaotic to me.

Another thing to consider is that, right now, it seems like exercises can be submitted under any language. Using Weblate would mean requiring all exercise contributions to be in English. (I think this would be a good thing, though, as there'd be a single source of truth as well as a clear choice for a fallback language.)

**UX**

From a UX point of view, having the UI for contributing translations in wger could have its benefits. Users would only need a single account to both contribute and tweak exercises as well as translations for them. The method for proposing changes to a translation would be the same as proposing changes to an exercise. Users could directly make things when using wger online. And more.

At the same time, I understand that adding translations to the wger UI would take some effort, especially if the UI is to be user-friendly. As I am not a web developer, I honestly don't know how much effort it would take or if it's worth it, though.



Let me know if you'd like to have a call about this.

**Comment by 12people** [comment]
Looking more into ODbL, it seems that it pertains to an entire database. As such, it seems like you'd have to separate all ODbL-licensed content into a separate database, as it's not compatible with CC BY-SA. As IANAL, I've posted this as a [question to the Open Source StackExchange](https://opensource.stackexchange.com/questions/11553/can-a-database-include-both-odbl-and-cc-by-sa-works).

**Comment by rolandgeider** [comment]
Making the UI simple to use was one reason why I suggested weblate, as it already has all the tools to help translators, e.g. see at a glance what changed in the original string, and adding such helper views would be a bit complex in wger. Adding sub-projects for each license would somehow go against that, though (I haven't checked, but I don't think there are exercises under all licenses, so we probably wouldn't need 5 sub projects). If you have any ideas on how to make the UI, please let me hear about it :)

And as for the ODBL, tt the moment the only data under that license are the ingredients imported from openfoodfacts, If push comes to shove it would be relatively easy to add a second DB where they would be stored (django supports using several databases at once), but let's hope we don't need to.

**Comment by 12people** [comment]
OK, that makes sense. I guess it mainly depends on what approach you'd like to take with exercises — whether a top-down approach, where there's a reference English translation, or a "decentralized" approach (like on Wikipedia), where there's no reference language and anyone can start with any translation. I think currently wger uses a decentralized approach, but I'd definitely be in favor of moving to a top-down approach.

As for ODbL, I'd recommend removing it as an option for exercises now, so that: 1. you don't have to have 2 separate exercise databases in the future, and 2. you can have a single CC BY-SA Weblate project for translations. I created a request for this at #658 .

**Comment by 12people** [comment]
Oh, and having a single Weblate project under the CC BY-SA 4.0 license would make most sense to me.

**Comment by rolandgeider** [comment]
A top down would make many things easier, but will be also a lot of (initial) work.

At the moment there is a single table with licenses for everything, we'd need a filter so that not all  an be used for exercises. I'll look later in the db and see how many entries there are for each license and language

**Comment by rolandgeider** [comment]
```sql
SELECT COUNT(1), l.short_name FROM exercises_exercisebase AS b LEFT JOIN exercises_exercise AS e ON b.id = e.exer
cise_base_id LEFT JOIN core_license AS l ON e.license_id = l.id WHERE b.status = '2'  GROUP BY l.short_name;

 count | short_name
-------+------------
   133 | CC-BY-SA 4
    28 | CC0
   245 | CC-BY-SA 3
```

So it seens most are CC3, followed by CC4. Since CC0 is public domain, we could relicense those if we go ahead and try to make everything CC4

**Comment by 12people** [comment]
Great!
It's worth noting that you wouldn't be relicensing the originals (which can't be done easily — see this [Stack Exchange thread](https://opensource.stackexchange.com/questions/7430/can-i-upgrade-the-version-of-cc-by-sa-from-3-0-to-4-0-in-my-modification)), but for Weblate, that doesn't matter, as all the translations, which are derivative works, can be licensed under CC BY-SA 4.

**Comment by 12people** [comment]
If you'd like to relicense the exercises in wger as well for the sake of simplicity, I imagine you could disallow adding new exercises under any other license and automatically license all edits to original exercises under CC BY-SA 4.0. Over time, all exercises would eventually be CC BY-SA 4.0 (and you could speed up the process by just making edits to all the differently-licensed exercises and adding yourself as the author of the edits).

**Comment by rolandgeider** [comment]
I'm closing this issue as this is already being implemented and the cleanup/polishing that still needs to be done is happening in other smaller tickets
