### ISSUE TITLE
Remove ODbL as a possible license for exercises

### ISSUE THREAD

**Issue by 12people** [wger-project/wger#658]
## Use case

ODbL is [incompatible with CC BY-SA](https://wiki.osmfoundation.org/wiki/Licence/Licence_Compatibility#Licences_that_are_not_compatible_with_the_.22Produced_Work.22_concept_of_the_ODbL) and applies to an entire database rather than just certain entries.

As such, it seems likely that CC BY-SA entries can't be inside a database that contains ODbL entries. (That is, if my interpretation of these licenses is correct — I asked about this in [this Stack Exchange thread](https://opensource.stackexchange.com/questions/11553/can-a-database-include-both-odbl-and-cc-by-sa-works) and we'll see what the answers are).

## Proposal

Remove the ODbL license as an option for exercises, as to prevent having to have to entirely separate databases for exercises.

**Comment by rolandgeider** [comment]
Newly submitted exercises and ingredients should be CC-BY-SA-4, without the possibility to select licenses. This is still acceptable but makes many things easier for us

**Comment by rolandgeider** [comment]
All exercises created over the API (which will be all of them, apart from the ones added directly on the server via admin commands or similar) are CC-BY-SA 4, closing
