### ISSUE TITLE
Name workouts

### ISSUE THREAD

**Issue by M123-dev** [wger-project/wger#666]
Probably I am just blind, but I can't see a way to name/rename a workout,..

**Comment by rolandgeider** [comment]
it's in the options button :)

![image](https://user-images.githubusercontent.com/2280729/116862754-84566300-ac05-11eb-8f5b-763811868201.png)


closing here, but just open again if the button is missing or something

**Comment by M123-dev** [comment]
@rolandgeider, then we should rename, "Description" is missleading. Also why is there a bigger header with the creation date, I dont think its that important. 

![wger](https://user-images.githubusercontent.com/39344769/116872871-01d69f00-ac17-11eb-8d1f-71dccba4fd36.PNG)

**Comment by rolandgeider** [comment]
I could imagine renaming description to "name" and restricting the length more than it is now (and perhaps adding a real description which could be longer and would be useful for #639)
