### ISSUE TITLE
Direct access to new created exercises

### ISSUE THREAD

**Issue by M123-dev** [wger-project/wger#670]
## Use case

I have a workout plan with pretty rare exercises, many of them are not in wger yet, I would be willing to enter them, but this:

>  Once it is reviewed, it will be added to the database. Till this happens, it will not be visible in the overview or the search.

scares me off. 

## Proposal
Newly added exercises should be directly available to the creator.

**Comment by rolandgeider** [comment]
Adding this to 2.1 for discussion. While our goal is to make crowdsourcing exercises more easy so that everybody can benefit, I can also see the benefits of having a list with private exercises.

**Comment by rolandgeider** [comment]
Newly submitted exercises will be inmediately (plus some caching time) available once we finish this, hopefully in the next two weeks. Closing here
