### ISSUE TITLE
Avoid double exercise entries

### ISSUE THREAD

**Issue by M123-dev** [wger-project/wger#671]
## Proposal

When adding a new exercise there should be a popup for similar exercises, to avoid double entries. 

Here how it is on stackoverflow:
![wger](https://user-images.githubusercontent.com/39344769/116790512-ca4fe180-aab4-11eb-88ee-d01287510e4d.PNG)

**Comment by rolandgeider** [comment]
At the moment only a simple name check is performed so that no two exercises with the same name are saved to the db, but this is obviously not very fault tolerant (one exercise can have different names, etc.). This should be done together with the exercise submition overhaul

**Comment by rolandgeider** [comment]
There's a now a quick filter when adding exercises that searches the db, this should make it less likely to add a duplicate. I'm closing this issue till we see how well this will work in the real world

![image](https://user-images.githubusercontent.com/2280729/185639180-dfbb0907-188b-4aa3-b787-71cf8adff154.png)
