### ISSUE TITLE
Can't save total daily calories

### ISSUE THREAD

**Issue by gkkulik** [wger-project/wger#689]
I can't add save the total daily calories on my self hosted wger. I'm using the current version of wger that was installed a couple of hours ago. However, I created an account on wger.de and got exactly the same results.

## Steps to Reproduce

1. Install according to the official instructions.
2. Input total caloric intake.
3. Click "Save total calories to profile"

**Expected results:** 

Total caloric intake saved.

**Actual results:** 

Seemingly nothing happens, see log.

<details>
  <summary>Logs</summary>

```
[26/May/2021 20:36:49] "GET /api/v2/userprofile/ HTTP/1.0" 200 575
Not Found: /api/v2/userprofile/undefined/
[26/May/2021 20:36:49] "PATCH /api/v2/userprofile/undefined/ HTTP/1.0" 404 28
```
</details>

**Comment by rolandgeider** [comment]
Fixed in #697
