### ISSUE TITLE
Posting Data through API

### ISSUE THREAD

**Issue by yannickh2** [wger-project/wger#690]
## Use case

    
I want to automatically track my workouts with self developed hardware like gyroscope and weight sensors connected to a microcontroller.

Is your feature request related to a problem? 
No

## Proposal

 Is the API open for posting data like repetitions and weights lifted, or bodyweight? I saw how to get those data this data 
but did not find if there is a way to post data too. If its not open maybe you can open it? Can you point me in the right direction? I am just going to install my own version on a server to experiment.

Best,
Yannick

**Comment by rolandgeider** [comment]
Hi! That sounds cool!

Sure, you can post new entries to `/api/v2/workoutlog/` For the different units, take a look at `/api/v2/setting-repetitionunit/` and `/api/v2/setting-weightunit/` (and of course if you host your own instance, you can edit the list).

**Comment by yannickh2** [comment]
Okay great. Will try! Thank you!
