### ISSUE TITLE
Notes for every exercise

### ISSUE THREAD

**Issue by los2pollos** [wger-project/wger#702]
## Use case

I asked a friend of mine to create a full workout routine for me, but he could not insert notes or suggestions for every exercise.

## Proposal

I would like to have a specific section for every exercise in the workout section to note down impressions, personal goals and other stuff. This should note be something structured, rather just a blank space to write down stuff.

**Comment by rolandgeider** [comment]
I agree that is something that would be useful. Often you want to change the base exercise for that specific workout / set

**Comment by los2pollos** [comment]
Yes, in that specific case, this friend of mine wanted to write down some suggestions, but it was not possible...
