### ISSUE TITLE
New Unit, max reps

### ISSUE THREAD

**Issue by M123-dev** [wger-project/wger#712]
## Use case

There is already the unit, until failure, this refers to the time (how long can I hold planks)

Another thing that would be very interesting is Max Reps (how many pushups can I do in a row) and not how long it takes me to do them.

## Proposal

Add a new unit of Max Reps in addition to "Until failure"

**Comment by rolandgeider** [comment]
Mhh, I'm not sure I get you here. What would the difference between until failure and max reps be?

**Comment by M123-dev** [comment]
@rolandgeider I updated the issue, hopefully its clearer now

**Comment by rolandgeider** [comment]
Ahhh, I get it now. I agree, this sounds useful

**Comment by rolandgeider** [comment]
Also, thanks for the reporting all the bugs :)

**Comment by rolandgeider** [comment]
Max Reps is now available. However, the weight units are cached in the mobile app (I think for 5 days) and if you add them on the web and then open the workout plan in the app it might crash

**Comment by M123-dev** [comment]
Thanks @rolandgeider, I'll check it out right away

**Comment by M123-dev** [comment]
@rolandgeider I updated my workout, the app is not crashing but when I open the workout, the day with the new unit is just not displayed anymore. I think this is fine since there are probably rarely new units

**Comment by rolandgeider** [comment]
Yes, that one was the first one in years 😄 

You might be able to fix this if you go to the app details in android and delete the cache. You'll probably need to login again

**Comment by M123-dev** [comment]
I already tried the cache but it did not work, I try deleting the full data later
