### ISSUE TITLE
Split front-end and back-end

### ISSUE THREAD

**Issue by M123-dev** [wger-project/wger#755]
## Current status
Currently everything (execpt the mobile app of course) is combined in this repo and codebase.

## Problem with that

Coming from openfoodfacts where it is currently still the same I know this will cause multiple problems in the future.
- More code = harder to maintain
- Frontend devs have to also run the backend and find there way to what they want to edit (same the other way around)
- Features may only be implemented to the website and not added to the api. (This has already started #672)
- A larger codebase makes it almost impossible to switch to new languages or frameworks in the future

## Proposal

Splitting the codebase into two (or possibly even more) stand-alone repositories.

**Comment by rolandgeider** [comment]
This has grown quite a bit and there are some candidates that would benefit from getting split into their own repos such as the docs or the initial fixtures. There is now an angular folder, but I'm not sure about that one, the goal is not to replace the complete UI with it, but only some pages.

**Comment by M123-dev** [comment]
Yes but since I am not familiar with the codebase I don't know whether angular is suitable for the frontend or not, but I would definitely recommend to split up the code as early as possible

**Comment by rolandgeider** [comment]
The frontend is being extracted already and I'll move the documentation, closing here
