### ISSUE TITLE
docker compose syntax error

### ISSUE THREAD

**Issue by Gr8ayu** [wger-project/wger#768]
## Steps to Reproduce

Run following command in Ubuntu 20.04 bash terminal 
1. git clone https://github.com/wger-project/wger
2. cd wger/
3. docker-compose -f extras/docker/compose/docker-compose.yml up

**Expected results:** server should start up

**Actual results:** ERROR: In file /home/gr8ayu/Desktop/temp/OS/wger/extras/docker/compose/dev.env: environment variable name 'ALLOW_REGISTRATION ' may not contain whitespace.

**Comment by kuseler** [comment]
I had this problem too, 
You'll probably have something like 
```shell
# Change the secret key to a random string if you are running this instance publicly
SECRET_KEY = wger-docker-secret-key


# Application
ALLOW_REGISTRATION = True
ALLOW_GUEST_USERS = True
```
What you'll want to do is removing the whitespace before the equal sign, it should look like this:

```shell
# Change the secret key to a random string if you are running this instance publicly
SECRET_KEY= wger-docker-secret-key


# Application
ALLOW_REGISTRATION= True
ALLOW_GUEST_USERS= True
```

let me know if it worked, if it did, I'll start a pull request.

**Comment by Gr8ayu** [comment]
Thanks, Yeah It worked.

**Comment by rolandgeider** [comment]
Thanks for reporting this!
