### ISSUE TITLE
WGER DOS/SPAM ATTACK???

### ISSUE THREAD

**Issue by deboy69** [wger-project/wger#789]
## Steps to Reproduce

1. ... Load WGER
2. ...Monitor Pi-hole
3. ...See it ask for DNS requests different sites that aren't tied to WGER

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```bash
```

</details>

![WGER](https://user-images.githubusercontent.com/66630421/131206394-58df720a-2bcb-4150-b2bc-9bb720afde1c.jpg)

**Comment by rolandgeider** [comment]
You mean that the local instance tries to contact those domains?

**Comment by deboy69** [comment]
Correct. Starts also asking for a lot of college domains for some reason too

**Comment by rolandgeider** [comment]
WTF, I'll look into this

**Comment by deboy69** [comment]
Thanks

**Comment by rolandgeider** [comment]
I just setup pi hole and started the latest docker image, so far there's been nothing

**Comment by deboy69** [comment]
Thanks. I think its on my end and not with wger. Think I had smokeping docker running and didnt know it. Just happened to be perfect timing when i fired up wger and it ran its ping test at the same time. checked my logs and all is good. Sorry for the inconvenience.

**Comment by rolandgeider** [comment]
don't worry, better to open an issue too many than have some compromised JS library or whatever running for months :)
