### ISSUE TITLE
Track additional (probably customized?) body measurements

### ISSUE THREAD

**Issue by financelurker** [wger-project/wger#875]
## Use case

I recently stumbled over wger and began using it for tracking my workouts. Since I'm a former Apple Health user to keep track of these things, besides nutrients and workouts there are also other things you can keep track of to have an holistic overview of your health state:
- sleep-data
- body measurements
  - BMI
  - waist circumference (cm)
  - body fat percentage (%)
  - height (cm)
  - body temperature (°C)
  - lean body mass (kg)
  - blood pressure (systolic/diastolic)
  - blood glucose level (mg/dL)
  - BMI
  - heart rate (BPM)
  - heart rate variability (ms)
  - resting heart rate (BPM)
  - walking heart rate average (BPM)
  - cardio fitness (VO2 max)
  - ...

And it would be awesome if you can keep track of this data within wger as well - so people, coming from the Apple ecosystem have a viable self-hosted alternative.

## Proposal

It's probably a lot of work to implement each measurable compartment here, so my proposal is:
- provide a generic way of defining additional body measurement types (name, unit and amount of data points per measurement - the latter one is to enable "blood pressure" and sleep-data "from"-"to")
- provide a generic way for letting people add data to these previously added body measurement type time-series
- provide a generic overview for each defined body measurement type to show the time-series data
- provide some pre-defined body measurement types (like the ones above) that users can add without further customization needed

I know, this is probably a huge feature request, but in my point of view this would fit perfectly into wger and I wouldn't want to have a separated other tool for that to completely switch from Apple Health to wger (besides the lack of an official AppStore app).

**Comment by rolandgeider** [comment]
Hi! This is actually already implemented in the flutter app (more or less the way you describe it), but not yet on the web app. You can define your category and the corresponding unit and then add measurements to it which will be plotted on a chart. All of this is pretty simple at the moment, but the base is there :)

**Comment by financelurker** [comment]
Wow, that's a great start. I guess that this feature requests just boils down to enabling this functionality in the web ui.

Question: Is my assumption right, that I have to build the flutter app for iOS on my own machine, and then upload it to my iPhone with my own certificates?

**Comment by rolandgeider** [comment]
Rather than just enabling it, implement it 😅

Yes, you'll have to build it yourself for now. I'd love to publish it on the app store, but that will have to wait

**Comment by jiany18** [comment]
Hi! We are trying to implement this function but we've been unable to find the backend codes for this part. Do you have any suggestions what files we should look at in order to fully implement this function?

**Comment by rolandgeider** [comment]
Hi @jiany18 !

Currently there isn't any code for this for the web UI, only for the flutter app (e.g. [here](https://github.com/wger-project/flutter/blob/master/lib/providers/measurement.dart) or [here](https://github.com/wger-project/flutter/blob/master/lib/screens/measurement_categories_screen.dart)).

We want to implement new features directly in react to allow for more dynamic content, so if you want to help with this (🙌), that's where to start, take a look at [the react repo](https://github.com/wger-project/react) This feature isn't very complicated, there's two endpoints, `/api/v2/measurement-category/` and `/api/v2/measurement/`. The category has a name and a unit, such as "body fat" and "%" and the entries just reference a category and are plotted.

**Comment by rolandgeider** [comment]
https://github.com/wger-project/react/issues/13

**Comment by matteopolleschi** [comment]
What is your strategy eventually? Flutter or react?

**Comment by rolandgeider** [comment]
Well, both. The mobile app uses flutter and the website react

**Comment by matteopolleschi** [comment]
Have you tried flutter web? Awfully slow but really "write once, deploy everywhere"...

**Comment by rolandgeider** [comment]
Yeah. I still feel it's not quite there yet

**Comment by rolandgeider** [comment]
Forgot to close this issue. This is available on the web app
