### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [wger-project/wger#879]
Hey there!

I belong to an open source security research community, and a member (@asura-n) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by rolandgeider** [comment]
Hi! Thanks for reaching out! You can reach me over email, I'll add a security file as soon as I can

**Comment by rolandgeider** [comment]
I have added a security.md, if you contact me via email or such we can discuss what you found (and fix it!)

**Comment by JamieSlome** [comment]
@rolandgeider - you should have just received an e-mail! 🎉

**Comment by rolandgeider** [comment]
got it

**Comment by JamieSlome** [comment]
@rolandgeider - was the report valid or invalid?

Just for reference:
https://huntr.dev/bounties/a8f0499a-1cae-44cd-b74d-3e00cb498f48/

**Comment by rolandgeider** [comment]
We were using a GET request to delete objects (yes I know...). We'll rework that whole module to use a proper REST API so this won't be possible anymore. I'll comment in your issue as well

**Comment by JamieSlome** [comment]
@rolandgeider - thanks 👍
