### ISSUE TITLE
[Enhancement] Add Helm charts for deploying to Kubernetes

### ISSUE THREAD

**Issue by sedadas** [wger-project/wger#887]
## Use case
wger is already containerized, so the next logical step in the path of the project is to make it deployable on Kubernetes.
I wanted to do so, as Kuberntes takes care of the whole orchestration of the stack and brings high-availability out of the box. Unfortunately, I couldn't find any available resources for performing the deployment.
This brought me to the idea that a common solution should be available for all users who want to deploy wger on a Kubernetes cluster: Helm charts.

## Proposal

I am proposing that wger adds Helm charts to the project either as an additional repo (in a fashion similar to the docker repo) or as a subdirectory in the main repository (for example, `contrib/charts` or something of the sort).

Either way, I can support you by providing and expanding on my current Helm charts which support the following:
* wger, Redis and PostgreSQL stack
* configurable persistent volume claims
* configurable pod resources for all parts of the stack
* configurable ports
* wger is configured completely over environment variables

What is missing:
* switch between SQLite and PostgreSQL
* configurable ingresses - type of ingress, whether the ingress should be created (OpenShift uses routes)
* migrations need to be checked on each start
* the exercise and nutrition data need to be made easily available for download - either by using a cronjob or on each container restart

**Comment by rolandgeider** [comment]
This sounds great. I would tend to add a new repo for this, but a sub folder might be enough. What are the best practices with Kubernetes? I don't have enough experience

As for the TODOs, I would say that we keep postgresql, sqlite is only for developement. There is also already an issue for performing migrations and downloading exercise and ingredient data automatically (https://github.com/wger-project/docker/issues/15 and https://github.com/wger-project/docker/issues/13)

**Comment by sedadas** [comment]
Thank you for your quick response!

I have seen both, actually. For example, Mattermost have their helm charts in [another repository](https://github.com/mattermost/mattermost-helm), whereas Banzai Cloud have theirs in [a subdirectory](https://github.com/banzaicloud/bank-vaults/tree/master/charts) of the main repository.

One of the advantages for a separate repo is the fact that issues will be more easily searchable and the main pipeline will not increase in complexity. Otherwise, it is not that big of a deal.

**Comment by rolandgeider** [comment]
Then let's make a new repo, I'd go with something like "helms"

**Comment by sedadas** [comment]
Yeah, "helms" sounds good.

**Comment by rolandgeider** [comment]
went with helm charts: https://github.com/wger-project/helm-charts

**Comment by rolandgeider** [comment]
https://github.com/wger-project/helm-charts/pull/1

**Comment by rolandgeider** [comment]
Closing here since we already have a PR, discussions can continue there
