### ISSUE TITLE
Cannot log back into the app after resetting password with desktop interface.

### ISSUE THREAD

**Issue by JamieBort** [wger-project/wger#891]
## Steps to Reproduce

1. I installed the app on my google pixal 4a with android 12. 
2. Using the app I created an account. The ID is/was a 9-digit pascal case string consisting of only letters
3. Within 5 or 10 minutes of creating my account I then attempted to log into the same account via my laptop. Using
a. MacBook Pro (Retina, 13-inch, Early 2015)
b. 2.9 GHz Dual-Core Intel Core i5
c. 16 GB 1867 MHz DDR3
d. Macintosh HD
e. Intel Iris Graphics 6100 1536 MB
f. and Updating Chrome Version 95.0.4638.69 (Official Build) (x86_64)
4. This was unsuccessful. So I initiated a password reset via the laptop/Chrome interface. This was successful. The new password is 32 characters long and consisting of an assortment of ascii characters.
5. I can now log into the account via my laptop/Chrome. But only with my email address as the id.
6. I cannot log back into the app with either the new nor old password, nor with the initial 9-character password nor my email address.

**Expected results:** 

I expected to be able to log into my account via the app. So that I could access my information.

**Actual results:** 

<details>
  <summary>Logs</summary>
I don't have any.
Please advise if you need them.
I'll need instructions on how to obtain them.

```bash
```

</details>

**Comment by rolandgeider** [comment]
Hi! That does sound indeed strange, the login process has no "magic" so if the username and password match you should get in. Are you getting an error message or something while logging in or does it fail silently? And are you using your own instance? In that case you need to check that the correct server is set

**Comment by JamieBort** [comment]
Hi. Thank you for the quick response.
I am seeing this now. Please disregard the more recent email.
I am using the default server.
I'm not sure what else to do differently.

Thanks again.

Jamie

**Comment by rolandgeider** [comment]
I also don't know what else I could tell you to try 😅. In any case I'll see if I can reproduce it

**Comment by rolandgeider** [comment]
Found the bug! The website let's you login with either username or email, the app required email. I've updated the server so now both are always accepted.

And thanks for reporting this

**Comment by JamieBort** [comment]
This is fantastic news. Thank you very much for taking the time to address
this. I am sorry I never responded to your previous email.

Jamie

**Comment by rolandgeider** [comment]
don't worry man!

I'm closing the issue, if this happens again (or something else) just open a new issue
