### ISSUE TITLE
ProgrammingError at /en/software/features

### ISSUE THREAD

**Issue by jakec-dev** [wger-project/wger#934]
Using the docker-compose.yml and prod.env from https://github.com/wger-project/docker results in the following error:

[error screnshot](https://i.imgur.com/XgTxCKv.png)

Only changes made are:

1. Modified prod.env with my domain, secret key, email address, etc.
2. Removed nginx service from the docker-compose.yml
3. Used caddy server as reverse-proxy
4. Added `network: default: external: name: caddy_server` to docker-compose.yml

Also, if I refresh the page the error message occasionally changes to:

[error #2 screenshot](https://i.imgur.com/wFqzBwh.png)

I haven't changed the db credentials at all - the username and password are both still set as the default `wger`

**Comment by rolandgeider** [comment]
Hi! This could be #930. I don't know when you pulled the image, but we fixed something recently there. Can you drop the containers and volumes and try again? If there was some problem connecting to the database, it's no wonder the tables could not be created
