### ISSUE TITLE
Editing an exercise's targeted muscle groups doesn't update muscle diagram.

### ISSUE THREAD

**Issue by dugite-code** [wger-project/wger#961]
## Steps to Reproduce

1. ... Create a new exercise selecting the targeted muscle groups and save.
2. ... Edit the exercise adding or removing the muscle groups.
3. ... View the exercise details page

**Expected results:** Muscle diagram on the detail page should show the currently selected muscle groups.

**Actual results:** Muscle diagram only reflects the selected muscle groups when initially creating the exercise.

**Comment by rolandgeider** [comment]
you mean in the detail page? I think there is some caching done on that page, it might be that it's not reset when updating the exercise entries

**Comment by dugite-code** [comment]
It looks like you are correct, restarting my wger docker instance and nginx cleared the image. I have some aggressive caching settings on my nginx proxy so that might be the main cause.

Sorry for the noise
