### ISSUE TITLE
Problem with `wger load-online-fixtures` command when using docker-compose

### ISSUE THREAD

**Issue by jpatrickpark** [wger-project/wger#969]
## Steps to Reproduce

On Ubuntu 20.04.3 LTS, using Docker version 20.10.12, build e91ed57 & docker-compose version 1.29.2, build 5becea4c, install wger and run optional commands as described in https://github.com/wger-project/wger/blob/master/extras/docker/compose/README.md:

1. docker-compose -f extras/docker/compose/docker-compose.yml up
2. docker-compose -f extras/docker/compose/docker-compose.yml exec web python3 manage.py sync-exercises
3. docker-compose -f extras/docker/compose/docker-compose.yml exec web python3 manage.py download-exercise-images
4. docker-compose -f extras/docker/compose/docker-compose.yml exec web wger load-online-fixtures

**Expected results:** 

I expected the last command to download optional files

**Actual results:** 

The last command throws an error.

I attached the full error message below.

<details>
  <summary>Logs</summary>

```bash
$ docker-compose -f extras/docker/compose/docker-compose.yml exec web wger load-online-fixtures
*** No settings given, using /home/wger/src/settings.py
Downloading fixture data from https://github.com/wger-project/data/raw/master/fixtures/ingredients.json.zip...
-> fixture size: 5.34 MB
-> saving to temp file /tmp/tmpen2b49r6.json.zip
Traceback (most recent call last):
  File "/home/wger/.local/bin/wger", line 33, in <module>
    sys.exit(load_entry_point('wger', 'console_scripts', 'wger')())
  File "/home/wger/src/wger/__main__.py", line 40, in main
    run(invoke_cmd + ' '.join(args), pty=True)
  File "/usr/local/lib/python3.9/dist-packages/invoke/__init__.py", line 48, in run
    return Context().run(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/context.py", line 95, in run
    return self._run(runner, command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/context.py", line 102, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'invoke load-online-fixtures'

Exit code: -9

Stdout: already printed

Stderr: n/a (PTYs have no stderr)

```

</details>

**Comment by rolandgeider** [comment]
Thanks for reporting this, will try to reproduce it

**Comment by rolandgeider** [comment]
Sorry, took a bit to look into this. I've decided to remove the docker-compose for development as it was basically a copy of this one [wger-project/docker](https://github.com/wger-project/docker) and the config was getting a bit out of sync. The production compose file can be used for development as well, I have added a comment in the file on how to do it (and there the sync commands work)
